import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const CORS={"access-control-allow-origin":"*","access-control-allow-headers":"content-type,x-client-provisioner-key","access-control-allow-methods":"POST,OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...CORS,"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const clip=(v:unknown,n=1500)=>String(v??"").slice(0,n);
const errText=(e:any)=>clip(e instanceof Error?`${e.name}: ${e.message}`:JSON.stringify(e)||String(e));
function safeEqual(a:string,b:string){const aa=new TextEncoder().encode(a),bb=new TextEncoder().encode(b);if(aa.length!==bb.length)return false;let d=0;for(let i=0;i<aa.length;i++)d|=aa[i]^bb[i];return d===0;}
function slugify(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/&/g," e ").replace(/[^a-z0-9]+/g,"").slice(0,60);}
function randomPassword(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%";const bytes=crypto.getRandomValues(new Uint8Array(28));let out="";for(const b of bytes)out+=chars[b%chars.length];return out;}
function b64ToBytes(v:string){const x=atob(v);return Uint8Array.from(x,c=>c.charCodeAt(0));}
function bytesToB64(v:Uint8Array){let s="";for(let i=0;i<v.length;i+=0x8000)s+=String.fromCharCode(...v.subarray(i,i+0x8000));return btoa(s);}
function maybeFolderId(text:string){try{const p=JSON.parse(text);for(const v of [p?.folder_id,p?.folderId,p?.id,p?.data?.folder_id,p?.data?.folderId,p?.data?.id])if(typeof v==="string"&&/^[A-Za-z0-9_-]{15,}$/.test(v))return v;}catch{}const m=text.match(/drive\.google\.com\/drive\/(?:u\/\d+\/)?folders\/([A-Za-z0-9_-]{15,})/i)||text.match(/(?:folder[_ -]?id|folderId)["'\s:=]+([A-Za-z0-9_-]{15,})/i);return m?.[1]||null;}

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});
 if(req.method!=="POST")return json({ok:false,error:"method_not_allowed"},405);
 const url=Deno.env.get("SUPABASE_URL")||"", serviceRole=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
 if(!url||!serviceRole)return json({ok:false,error:"server_configuration"},500);
 const db=createClient(url,serviceRole,{auth:{persistSession:false,autoRefreshToken:false}}),ops=db.schema("agency_ops");
 const [{data:secretRow},body]=await Promise.all([ops.from("automation_settings").select("value").eq("key","CLIENT_PROVISIONER_SECRET").maybeSingle(),req.json().catch(()=>({}))]);
 const expected=typeof secretRow?.value==="string"?secretRow.value:"",presented=req.headers.get("x-client-provisioner-key")||"";
 if(!expected||!presented||!safeEqual(expected,presented))return json({ok:false,error:"unauthorized"},401);
 const mode=String(body?.mode||"LIVE").toUpperCase();if(mode==="HEALTHCHECK")return json({ok:true,version:"CLIENT_PROVISIONER_V2",mode});
 const requestedClientId=typeof body?.client_id==="string"?body.client_id:null, workerId=`client-provisioner-v2:${crypto.randomUUID()}`, now=new Date().toISOString();
 async function setting(k:string){const {data}=await ops.from("automation_settings").select("value").eq("key",k).maybeSingle();return typeof data?.value==="string"?data.value:"";}
 async function claim(){let q=ops.from("client_provisioning_jobs").select("*").in("status",["PENDING","RETRY","PARTIAL"]).lte("next_attempt_at",now).order("next_attempt_at",{ascending:true}).limit(requestedClientId?1:8);if(requestedClientId)q=q.eq("client_id",requestedClientId);const {data,error}=await q;if(error)throw error;const out:any[]=[];for(const r of data||[]){const {data:x}=await ops.from("client_provisioning_jobs").update({status:"RUNNING",locked_at:new Date().toISOString(),locked_by:workerId,updated_at:new Date().toISOString()}).eq("id",r.id).in("status",["PENDING","RETRY","PARTIAL"]).select("*").maybeSingle();if(x)out.push(x);}return out;}
 async function uniqueUsername(clientId:string,name:string){let base=slugify(name)||`cliente${clientId.replace(/-/g,"").slice(0,8)}`,candidate=base;for(let i=0;i<6;i++){const {data}=await db.from("briefing_provisioning_map").select("client_id").eq("username",candidate).maybeSingle();if(!data||data.client_id===clientId)return candidate;candidate=`${base.slice(0,50)}${clientId.replace(/-/g,"").slice(0,6)}${i||""}`;}return `${base.slice(0,44)}${crypto.randomUUID().replace(/-/g,"").slice(0,10)}`;}
 async function vaultKey(){const {data,error}=await ops.rpc("get_client_vault_key");if(error||!data)throw new Error(`vault_key_missing:${errText(error)}`);const raw=b64ToBytes(String(data));if(raw.byteLength!==32)throw new Error("vault_key_invalid_length");return crypto.subtle.importKey("raw",raw,{name:"AES-GCM"},false,["encrypt"]);}
 async function encryptValue(key:CryptoKey,value:string|null){if(!value)return {ciphertext:null,iv:null};const iv=crypto.getRandomValues(new Uint8Array(12));const encrypted=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,new TextEncoder().encode(value));return {ciphertext:bytesToB64(new Uint8Array(encrypted)),iv:bytesToB64(iv)};}
 async function savePortalCredential(clientId:string,username:string,password:string){const key=await vaultKey();const [loginEnc,passEnc,notesEnc]=await Promise.all([encryptValue(key,username),encryptValue(key,password),encryptValue(key,"Conta criada automaticamente pelo onboarding. Senha temporária; orientar troca no primeiro acesso.")]);const {data:existing}=await ops.from("client_access_vault").select("id").eq("client_id",clientId).eq("category","PORTAL").eq("system_name","Briefing Hub").order("created_at",{ascending:false}).limit(1).maybeSingle();const payload={client_id:clientId,category:"PORTAL",system_name:"Briefing Hub",login_url:"https://agency-briefing-hub.lakassessoriadigital.workers.dev/cliente",login_ciphertext:loginEnc.ciphertext,login_iv:loginEnc.iv,password_ciphertext:passEnc.ciphertext,password_iv:passEnc.iv,notes_ciphertext:notesEnc.ciphertext,notes_iv:notesEnc.iv,encryption_version:1,created_by_person:"SYSTEM - Client Provisioner",updated_by_person:"SYSTEM - Client Provisioner",updated_at:new Date().toISOString()};if(existing?.id){const {error}=await ops.from("client_access_vault").update(payload).eq("id",existing.id);if(error)throw error;return existing.id;}const {data,error}=await ops.from("client_access_vault").insert(payload).select("id").single();if(error||!data)throw error||new Error("vault_insert_failed");return data.id;}
 async function ensureBriefing(client:any){let {data:mapping,error}=await db.from("briefing_provisioning_map").select("username,client_id,auth_email,legacy_name,linked_at").eq("client_id",client.id).limit(1).maybeSingle();if(error)throw new Error(`mapping_read:${errText(error)}`);if(!mapping){const username=await uniqueUsername(client.id,client.display_name),auth_email=`${username}@briefing.local`;const ins=await db.from("briefing_provisioning_map").insert({username,client_id:client.id,legacy_name:client.display_name,auth_email}).select("username,client_id,auth_email,legacy_name,linked_at").single();if(ins.error)throw new Error(`mapping_insert:${errText(ins.error)}`);mapping=ins.data;}else if(!mapping.auth_email){const auth_email=`${mapping.username}@briefing.local`;const fixed=await db.from("briefing_provisioning_map").update({auth_email}).eq("client_id",client.id).select("username,client_id,auth_email,legacy_name,linked_at").single();if(fixed.error)throw new Error(`mapping_email_backfill:${errText(fixed.error)}`);mapping=fixed.data;}
  const {data:profile,error:pe}=await db.from("briefing_client_profile").select("client_id").eq("client_id",client.id).maybeSingle();if(pe)throw new Error(`profile_read:${errText(pe)}`);if(!profile){const {error:e}=await db.from("briefing_client_profile").insert({client_id:client.id,metadata:{provisioned_by:"agency-ops-client-provisioner",provisioned_at:new Date().toISOString()},visibility:"SHARED",updated_by_type:"SYSTEM"});if(e)throw new Error(`profile_insert:${errText(e)}`);}
  const email=String(mapping.auth_email).toLowerCase();const lookup=await db.rpc("briefing_auth_user_by_email",{p_email:email}).maybeSingle();if(lookup.error)throw new Error(`auth_lookup:${errText(lookup.error)}`);let userId=lookup.data?.user_id as string|undefined,createdUser=false,tempPassword:string|null=null,vaultItemId:string|null=null;
  if(!userId){tempPassword=randomPassword();const created=await db.auth.admin.createUser({email,password:tempPassword,email_confirm:true,user_metadata:{briefing_username:mapping.username,briefing_client_id:client.id,display_name:client.display_name,onboarding_provisioned:true,must_change_password:true}});if(created.error||!created.data.user)throw new Error(`auth_create:${errText(created.error)}`);userId=created.data.user.id;createdUser=true;vaultItemId=await savePortalCredential(client.id,mapping.username,tempPassword);}
  const membership=await db.from("briefing_client_users").upsert({user_id:userId,client_id:client.id,role:"owner",is_active:true},{onConflict:"user_id,client_id"});if(membership.error)throw new Error(`membership:${errText(membership.error)}`);if(!mapping.linked_at)await db.from("briefing_provisioning_map").update({linked_at:new Date().toISOString()}).eq("username",mapping.username);
  return {ready:true,username:mapping.username,auth_email:email,user_id:userId,created_user:createdUser,credential_vault_item_id:vaultItemId,credential_state:createdUser?"STORED_IN_CLIENT_ACCESS_VAULT":"EXISTING_USER_UNCHANGED"};}
 async function ensureDrive(client:any,job:any){const {data:existing,error}=await ops.from("client_integrations").select("id,external_id,external_name,is_primary,metadata").eq("client_id",client.id).eq("system","DRIVE").order("is_primary",{ascending:false}).limit(1).maybeSingle();if(error)throw new Error(`drive_read:${errText(error)}`);if(existing?.external_id)return {ready:true,folder_id:existing.external_id,folder_name:existing.external_name,reused:true};const webhook=await setting("CLIENT_DRIVE_CREATE_WEBHOOK_URL");if(!webhook)return {ready:false,state:"WAITING_DRIVE_WEBHOOK_CONFIG"};let groupName=`[MARKETING] - ${client.display_name}`;if(job.chat_id){const {data:chat}=await ops.from("whatsapp_chat_registry").select("chat_name").eq("chat_id",job.chat_id).maybeSingle();if(chat?.chat_name)groupName=chat.chat_name;}const response=await fetch(webhook,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({cliente:client.display_name,nome_grupo:groupName}),signal:AbortSignal.timeout(25000)});const text=await response.text();if(!response.ok)throw new Error(`DRIVE_WEBHOOK_HTTP_${response.status}:${clip(text,500)}`);const folderId=maybeFolderId(text);if(folderId){const ins=await ops.from("client_integrations").upsert({client_id:client.id,system:"DRIVE",external_id:folderId,external_name:client.display_name,confidence:"ALTA",matched_by:"CLIENT_PROVISIONER_DRIVE_WEBHOOK",is_primary:true,metadata:{provisioned_at:new Date().toISOString(),provisioned_by:"agency-ops-client-provisioner"}},{onConflict:"system,external_id"});if(ins.error)throw new Error(`drive_link:${errText(ins.error)}`);return {ready:true,folder_id:folderId,created_external:true};}return {ready:false,state:"WAITING_DRIVE_LINK",webhook_accepted:true,response:clip(text,250)};}
 async function fail(job:any,step:string,e:unknown){const attempts=Number(job.attempt_count||0)+1,terminal=attempts>=Number(job.max_attempts||8),delay=Math.min(60,Math.max(2,Math.pow(2,Math.min(attempts,5))));await ops.from("client_provisioning_jobs").update({status:terminal?"FAILED":"RETRY",current_step:step,attempt_count:attempts,next_attempt_at:new Date(Date.now()+delay*60000).toISOString(),last_error:errText(e),locked_at:null,locked_by:null,updated_at:new Date().toISOString()}).eq("id",job.id);if(!terminal)try{await ops.rpc("schedule_client_provisioning_wakeup");}catch{}}
 async function processJob(job:any){const {data:client,error}=await ops.from("clients").select("id,display_name,lifecycle,metadata").eq("id",job.client_id).maybeSingle();if(error||!client)return fail(job,"RESOLVE_CLIENT",error||new Error("client_not_found"));if(!["ACTIVE","ONBOARDING"].includes(String(client.lifecycle))){await ops.from("client_provisioning_jobs").update({status:"SKIPPED",current_step:"DONE",completed_at:new Date().toISOString(),locked_at:null,locked_by:null,details:{...(job.details||{}),skipped_reason:`lifecycle:${client.lifecycle}`},updated_at:new Date().toISOString()}).eq("id",job.id);return;}let briefing:any;try{briefing=await ensureBriefing(client);}catch(e){return fail(job,"ENSURE_BRIEFING",e);}let drive:any;try{drive=await ensureDrive(client,job);}catch(e){return fail(job,"ENSURE_DRIVE",e);}const details={...(job.details||{}),briefing,drive,last_run_at:new Date().toISOString(),worker_version:"CLIENT_PROVISIONER_V2"};if(!drive.ready){await ops.from("client_provisioning_jobs").update({status:"PARTIAL",current_step:"ENSURE_DRIVE",next_attempt_at:new Date(Date.now()+365*86400000).toISOString(),last_error:drive.state||"drive_not_linked",details,locked_at:null,locked_by:null,updated_at:new Date().toISOString()}).eq("id",job.id);return;}await ops.from("client_provisioning_jobs").update({status:"DONE",current_step:"DONE",completed_at:new Date().toISOString(),last_error:null,details,locked_at:null,locked_by:null,updated_at:new Date().toISOString()}).eq("id",job.id);}
 try{const jobs=await claim();for(const j of jobs)await processJob(j);return json({ok:true,version:"CLIENT_PROVISIONER_V2",claimed:jobs.length});}catch(e){return json({ok:false,error:errText(e)},500);}
});