import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const CORS={"access-control-allow-origin":"*","access-control-allow-headers":"authorization,apikey,content-type","access-control-allow-methods":"GET,POST,OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...CORS,"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const ALLOWED=new Set(["Adler Furtado","Leonardo Augusto"]);
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});if(!["GET","POST"].includes(req.method))return json({ok:false,error:"method_not_allowed"},405);
 const url=Deno.env.get("SUPABASE_URL")||"",anon=Deno.env.get("SUPABASE_ANON_KEY")||"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"",ah=req.headers.get("Authorization")||"";if(!url||!anon||!service||!ah.startsWith("Bearer "))return json({ok:false,error:"unauthorized"},401);
 const auth=createClient(url,anon,{global:{headers:{Authorization:ah}},auth:{persistSession:false,autoRefreshToken:false}});const {data:u}=await auth.auth.getUser();if(!u?.user)return json({ok:false,error:"unauthorized"},401);
 const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}}),ops=db.schema("agency_ops");const {data:pref}=await ops.from("user_preferences").select("collaborator_person").eq("user_key",u.user.id).maybeSingle();const person=String(pref?.collaborator_person||"").trim();if(!ALLOWED.has(person))return json({ok:false,error:"forbidden"},403);
 if(req.method==="POST"){
  const body=await req.json().catch(()=>({})),action=String(body?.action||"").toUpperCase();
  if(action==="CREATE"){
   const title=String(body?.title||"").trim();if(!title)return json({ok:false,error:"title_required"},400);const clientId=body.client_id?String(body.client_id):null;
   let client:any=null;if(clientId){const r=await ops.from("clients").select("id,display_name,cs_owner,gt_owner,designer_owner").eq("id",clientId).maybeSingle();client=r.data;if(!client)return json({ok:false,error:"client_not_found"},404);}
   const type=["ESCALATION","CREATIVE_REQUEST","TECHNICAL","CLIENT_FOLLOWUP","CLICKUP","GENERAL"].includes(String(body.type))?String(body.type):"GENERAL";const priority=["CRITICAL","HIGH","MEDIUM","LOW"].includes(String(body.priority))?String(body.priority):"MEDIUM";const targetRole=String(body.target_role||"CS").slice(0,40);let targetPerson=body.target_person?String(body.target_person).slice(0,160):null;
   if(!targetPerson&&client){targetPerson=targetRole==="CS"?client.cs_owner:targetRole==="GT"?client.gt_owner:targetRole==="DESIGN"?client.designer_owner:targetRole==="MGMT"?"Adler Furtado":null;}
   const metadata:any={leadership_created:true};let clickup:any=null;
   if(body.create_clickup===true||type==="CLICKUP"){
    const cfg:any=(await ops.rpc("get_clickup_config")).data||{};if(!cfg?.token)return json({ok:false,error:"clickup_not_configured"},503);const listByRole:Record<string,string>={GT:"901317155229",DESIGN:"901317155418",CS:"1000210000004387",MGMT:"901326095338",AI:"901326095338"};const listId=listByRole[targetRole]||"901326095338";const assignees:number[]=[];
    if(targetPerson){const {data:r}=await ops.from("team_roster").select("clickup_user").eq("person",targetPerson).maybeSingle();if(r?.clickup_user){const {data:a}=await ops.from("clickup_task_assignees").select("user_id,username").ilike("username",r.clickup_user).limit(1);const id=Number(a?.[0]?.user_id);if(Number.isFinite(id))assignees.push(id);}}
    const resp=await fetch(`https://api.clickup.com/api/v2/list/${listId}/task`,{method:"POST",headers:{Authorization:cfg.token,"content-type":"application/json"},body:JSON.stringify({name:(client?.display_name?`[${client.display_name}] ${title}`:title).slice(0,240),description:String(body.description||"").slice(0,4000)||undefined,assignees,due_date:body.due_at?new Date(body.due_at).getTime():undefined})});if(!resp.ok)return json({ok:false,error:"clickup_create_failed"},502);clickup=await resp.json();metadata.clickup_task_id=String(clickup.id);metadata.clickup_url=clickup.url||null;metadata.clickup_list_id=listId;
   }
   const {data,error}=await ops.from("work_items").insert({client_id:clientId,type,priority,title:title.slice(0,240),description:String(body.description||"").slice(0,4000)||null,source:"leadership_work_center",source_id:clickup?.id?String(clickup.id):null,created_by_user_key:u.user.id,created_by_person:person,target_role:targetRole,target_person:targetPerson,due_at:body.due_at||null,metadata}).select().single();if(error)return json({ok:false,error:"create_failed"},500);return json({ok:true,item:data,clickup:clickup?{id:String(clickup.id),url:clickup.url||null}:null});
  }
  if(action==="UPDATE"){
   const id=String(body?.id||"");if(!id)return json({ok:false,error:"id_required"},400);const {data:current}=await ops.from("work_items").select("*").eq("id",id).maybeSingle();if(!current)return json({ok:false,error:"not_found"},404);const status=["OPEN","IN_PROGRESS","WAITING","SNOOZED","COMPLETED","DISMISSED"].includes(String(body.status))?String(body.status):current.status;const resolution=typeof body.resolution==="string"?body.resolution.slice(0,4000):current.resolution;const patch:any={status,resolution,snoozed_until:status==="SNOOZED"?(body.snoozed_until||current.snoozed_until||new Date(Date.now()+86400000).toISOString()):null,started_at:status==="IN_PROGRESS"?(current.started_at||new Date().toISOString()):current.started_at,completed_at:status==="COMPLETED"?new Date().toISOString():current.completed_at,completed_by:status==="COMPLETED"?person:current.completed_by};const {data,error}=await ops.from("work_items").update(patch).eq("id",id).select().single();if(error)return json({ok:false,error:"update_failed"},500);return json({ok:true,item:data});
  }
  return json({ok:false,error:"unknown_action"},400);
 }
 const [itemsRes,clientsRes,rosterRes]=await Promise.all([ops.from("work_items").select("*,clients(display_name,gt_owner,cs_owner,designer_owner)").order("created_at",{ascending:false}).limit(1000),ops.from("clients").select("id,display_name,lifecycle,cs_owner,gt_owner,designer_owner").in("lifecycle",["ACTIVE","ONBOARDING"]).order("display_name"),ops.from("team_roster").select("person,role").eq("is_former",false).order("person")]);if(itemsRes.error||clientsRes.error||rosterRes.error)return json({ok:false,error:"query_failed"},500);const items=itemsRes.data||[],open=items.filter((r:any)=>!["COMPLETED","DISMISSED"].includes(String(r.status))),now=Date.now();return json({ok:true,person,items,clients:clientsRes.data||[],roster:rosterRes.data||[],summary:{open:open.length,critical:open.filter((r:any)=>r.priority==="CRITICAL").length,overdue:open.filter((r:any)=>r.due_at&&new Date(r.due_at).getTime()<now).length,waiting:open.filter((r:any)=>["WAITING","SNOOZED"].includes(String(r.status))).length,completed_30d:items.filter((r:any)=>r.status==="COMPLETED"&&r.completed_at&&new Date(r.completed_at).getTime()>=now-30*86400000).length},generated_at:new Date().toISOString()});
});