from pathlib import Path
p=Path(r"C:\Users\Adler\agency-ops-dashboard\supabase\functions\agency-ops-client-provisioner\index.ts")
s=p.read_text(encoding="utf-8")
anchor=' async function savePortalCredential(clientId:string,username:string,password:string)'
helpers=''' async function decryptValue(key:CryptoKey,ciphertext:string|null,iv:string|null){if(!ciphertext||!iv)return null;const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:b64ToBytes(iv)},key,b64ToBytes(ciphertext));return new TextDecoder().decode(plain);}\n async function portalCredential(clientId:string){const {data,error}=await ops.from("client_access_vault").select("login_ciphertext,login_iv,password_ciphertext,password_iv").eq("client_id",clientId).eq("category","PORTAL").eq("system_name","Briefing Hub").order("created_at",{ascending:false}).limit(1).maybeSingle();if(error||!data)return null;const key=await vaultKey();const [login,password]=await Promise.all([decryptValue(key,data.login_ciphertext,data.login_iv),decryptValue(key,data.password_ciphertext,data.password_iv)]);return login&&password?{login,password}:null;}\n function driveIdFromUrl(v:string){const s=String(v||"");for(const re of [/\\/folders\\/([A-Za-z0-9_-]{10,})/i,/[?&]id=([A-Za-z0-9_-]{10,})/i,/^([A-Za-z0-9_-]{20,})$/]){const m=s.match(re);if(m?.[1])return m[1];}return null;}\n async function resolveDriveViaBriefing(client:any){try{const cred=await portalCredential(client.id);if(!cred)return null;const base="https://agency-briefing-hub.lakassessoriadigital.workers.dev";const lr=await fetch(base+"/api/client/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:cred.login,password:cred.password}),signal:AbortSignal.timeout(20000)});if(!lr.ok)return null;const cookie=(lr.headers.get("set-cookie")||"").split(";")[0];if(!cookie)return null;const mr=await fetch(base+"/api/client/materials",{headers:{cookie},signal:AbortSignal.timeout(25000)});const x=await mr.json().catch(()=>({}));if(!mr.ok||x?.ready!==true)return null;const folderId=driveIdFromUrl(String(x.folder_url||""));return folderId?{folder_id:folderId,folder_name:String(x.folder_name||client.display_name),source:"BRIEFING_DRIVE_BRIDGE"}:null;}catch{return null;}}\n async function persistDrive(client:any,folderId:string,folderName:string,matchedBy:string){const {error}=await ops.from("client_integrations").upsert({client_id:client.id,system:"DRIVE",external_id:folderId,external_name:folderName||client.display_name,confidence:"ALTA",matched_by:matchedBy,is_primary:true,metadata:{provisioned_at:new Date().toISOString(),provisioned_by:"agency-ops-client-provisioner"}},{onConflict:"system,external_id"});if(error)throw new Error(`drive_link:${errText(error)}`);return {ready:true,folder_id:folderId,folder_name:folderName||client.display_name};}\n'''
if anchor not in s: raise SystemExit('anchor missing')
s=s.replace(anchor,helpers+anchor,1)
start=s.index(' async function ensureDrive(client:any,job:any){')
end=s.index('\n async function fail(',start)
new=''' async function ensureDrive(client:any,job:any){const {data:existing,error}=await ops.from("client_integrations").select("id,external_id,external_name,is_primary,metadata").eq("client_id",client.id).eq("system","DRIVE").order("is_primary",{ascending:false}).limit(1).maybeSingle();if(error)throw new Error(`drive_read:${errText(error)}`);if(existing?.external_id)return {ready:true,folder_id:existing.external_id,folder_name:existing.external_name,reused:true};const {data:binding}=await ops.from("client_drive_bindings").select("drive_folder_id,binding_status,source").eq("client_id",client.id).maybeSingle();if(binding?.drive_folder_id&&String(binding.binding_status||"").toUpperCase()==="VERIFIED"){const saved=await persistDrive(client,String(binding.drive_folder_id),client.display_name,"CLIENT_DRIVE_BINDING");return {...saved,reused:true,source:binding.source||"CLIENT_DRIVE_BINDING"};}const bridged=await resolveDriveViaBriefing(client);if(bridged){const saved=await persistDrive(client,bridged.folder_id,bridged.folder_name,bridged.source);return {...saved,reused:true,source:bridged.source};}const alreadyRequested=Boolean(job?.details?.drive?.webhook_accepted);if(alreadyRequested)return {ready:false,state:"WAITING_DRIVE_LINK",webhook_accepted:true};const webhook=await setting("CLIENT_DRIVE_CREATE_WEBHOOK_URL");if(!webhook)return {ready:false,state:"WAITING_DRIVE_WEBHOOK_CONFIG"};let groupName=`[MARKETING] - ${client.display_name}`;if(job.chat_id){const {data:chat}=await ops.from("whatsapp_chat_registry").select("chat_name").eq("chat_id",job.chat_id).maybeSingle();if(chat?.chat_name)groupName=chat.chat_name;}const response=await fetch(webhook,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({cliente:client.display_name,nome_grupo:groupName}),signal:AbortSignal.timeout(25000)});const text=await response.text();if(!response.ok)throw new Error(`DRIVE_WEBHOOK_HTTP_${response.status}:${clip(text,500)}`);const folderId=maybeFolderId(text);if(folderId){const saved=await persistDrive(client,folderId,client.display_name,"CLIENT_PROVISIONER_DRIVE_WEBHOOK");return {...saved,created_external:true};}await new Promise(r=>setTimeout(r,1800));const after=await resolveDriveViaBriefing(client);if(after){const saved=await persistDrive(client,after.folder_id,after.folder_name,after.source);return {...saved,created_external:true,source:after.source};}return {ready:false,state:"WAITING_DRIVE_LINK",webhook_accepted:true,response:clip(text,250)};}'''
s=s[:start]+new+s[end:]
old='if(!drive.ready){await ops.from("client_provisioning_jobs").update({status:"PARTIAL",current_step:"ENSURE_DRIVE",next_attempt_at:new Date(Date.now()+365*86400000).toISOString(),last_error:drive.state||"drive_not_linked",details,locked_at:null,locked_by:null,updated_at:new Date().toISOString()}).eq("id",job.id);return;}'
newp='if(!drive.ready){const waits=Number(job?.details?.drive_wait_attempts||0)+1;const terminal=waits>=12;details.drive_wait_attempts=waits;await ops.from("client_provisioning_jobs").update({status:terminal?"FAILED":"PARTIAL",current_step:"ENSURE_DRIVE",next_attempt_at:new Date(Date.now()+5*60000).toISOString(),last_error:drive.state||"drive_not_linked",details,locked_at:null,locked_by:null,updated_at:new Date().toISOString()}).eq("id",job.id);if(!terminal)try{await ops.rpc("schedule_client_provisioning_wakeup");}catch{}return;}'
if old not in s: raise SystemExit('partial block missing')
s=s.replace(old,newp,1)
p.write_text(s,encoding='utf-8')
print('drive patch done')