import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const CORS = {
  "access-control-allow-origin": "*",
  "access-control-allow-headers": "authorization,apikey,content-type",
  "access-control-allow-methods": "POST,OPTIONS",
};
const V3_PATH = "/functions/v1/agency-ops-ai-ask-team-v3";
const MAX_CONTEXT = 105_000;
const AI_TIMEOUT_MS = 70_000;

const reply = (body: unknown, status = 200) => new Response(JSON.stringify(body), {
  status,
  headers: { ...CORS, "content-type": "application/json; charset=utf-8", "cache-control": "no-store" },
});
const norm = (value: unknown) => String(value ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
const clip = (value: unknown, max = 420) => { const text = String(value ?? "").trim().replace(/\s+/g, " "); return text.length > max ? `${text.slice(0, max)}…` : text; };
const daysAgo = (days: number) => new Date(Date.now() - days * 86_400_000).toISOString();
const teamWide = (role: string) => ["MGMT", "AI", "CS"].includes(role);

const ADVANCED = /\b(antes|depois|comecou|primeiro sinal|sequencia|causa|causou|impacto|efeito|provavelmente|indicio|correlacao|piorou|melhorou|promessa|promessas|compromisso|compromissos|descumpr|cobrou duas|mensagens consecutivas|resposta rapida|resposta util|nao resolve|vou verificar|retorno posterior|veio do trafego|origem da venda|atribuicao|duplicad|dois corretores|distribuicao de leads|equilibrada|demora mais|fora do horario|fadiga|frequencia alta|aumento de orcamento|mudanca de criativo|abriu publico|limitada por orcamento|limitada por criativo|lead barato|lead caro|queda do funil|desperdicio|corrigir comercial|corrigir trafego|qualidade de lead|reagendad|mais tentativas|cedo demais|etapa mais atrasa|tempo medio|rompe o sla|retrabalho|erro de criativo|mudou de opiniao|culpa|horas de design|prestes|proximos 7 dias|piorando semana|vai gerar cobranca|atencao demais|atencao de menos|depende demais|se um gt faltasse|automatizado primeiro|se voce fosse|decisoes tomaria|nao percebi)\b/;

function safeAnswer(body: any, raw: string) {
  for (const value of [body?.answer, body?.response, body?.output, body?.result, body?.text, body?.message]) if (typeof value === "string" && value.trim()) return value.trim();
  if (raw.trim() && !raw.trim().startsWith("<")) return raw.trim();
  return null;
}

function resolveEntity(question: string, rows: any[], field: string, minPart = 4) {
  const q = ` ${norm(question)} `;
  let best: any = null, bestScore = 0;
  for (const row of rows) {
    const value = norm(row?.[field]);
    if (!value) continue;
    let score = q.includes(` ${value} `) ? 1000 + value.length : 0;
    if (!score) score = value.split(" ").filter((part) => part.length >= minPart && q.includes(` ${part} `)).reduce((sum, part) => sum + part.length, 0);
    if (score > bestScore) { best = row; bestScore = score; }
  }
  return bestScore >= minPart ? best : null;
}

function scopedClients(role: string, person: string, clients: any[]) {
  if (role === "GT") return clients.filter((c) => c.gt_owner === person);
  if (role === "DESIGN") return clients.filter((c) => c.designer_owner === person);
  return clients;
}

function compact(rows: any[], fields: string[], max = 200) {
  return (rows ?? []).slice(0, max).map((row) => {
    const result: Record<string, unknown> = {};
    for (const field of fields) {
      const value = row?.[field];
      if (value === null || value === undefined || value === "") continue;
      result[field] = typeof value === "string" ? clip(value, 520) : value;
    }
    return result;
  });
}

function percentile(values: number[], p: number) {
  if (!values.length) return null;
  const sorted = [...values].sort((a, b) => a - b);
  return Number(sorted[Math.min(sorted.length - 1, Math.max(0, Math.ceil(sorted.length * p) - 1))].toFixed(1));
}

function responseStats(rows: any[]) {
  const grouped = new Map<string, number[]>();
  for (const row of rows ?? []) {
    const value = Number(row.response_minutes); if (!Number.isFinite(value)) continue;
    const person = String(row.cs_person || "Sem CS"); if (!grouped.has(person)) grouped.set(person, []); grouped.get(person)!.push(value);
  }
  return [...grouped.entries()].map(([person, values]) => ({ person, replies: values.length, avg_minutes: Number((values.reduce((a,b)=>a+b,0)/values.length).toFixed(1)), median_minutes: percentile(values,.5), p90_minutes: percentile(values,.9) })).sort((a,b)=>b.avg_minutes-a.avg_minutes);
}

function mediaSummary(rows: any[], clientNames: Map<string,string>) {
  const now = Date.now(); const grouped = new Map<string, any>();
  for (const row of rows ?? []) {
    if (!row.client_id) continue;
    if (!grouped.has(row.client_id)) grouped.set(row.client_id, { client_id: row.client_id, client: clientNames.get(row.client_id) || row.client_id, d7:{spend:0,leads:0,clicks:0,impressions:0}, p7:{spend:0,leads:0,clicks:0,impressions:0}, d30:{spend:0,leads:0,clicks:0,impressions:0} });
    const item = grouped.get(row.client_id); const age = Math.floor((now - new Date(`${row.date}T12:00:00Z`).getTime())/86_400_000);
    const add=(b:any)=>{b.spend+=Number(row.spend||0);b.leads+=Number(row.leads||0);b.clicks+=Number(row.clicks||0);b.impressions+=Number(row.impressions||0);};
    if(age>=0&&age<7)add(item.d7); if(age>=7&&age<14)add(item.p7); if(age>=0&&age<30)add(item.d30);
  }
  return [...grouped.values()].map((item)=>{for(const k of ["d7","p7","d30"]){const b=item[k];b.spend=Number(b.spend.toFixed(2));b.cpl=b.leads?Number((b.spend/b.leads).toFixed(2)):null;b.ctr=b.impressions?Number((b.clicks/b.impressions*100).toFixed(2)):null;}item.leads_delta_pct=item.p7.leads?Number(((item.d7.leads-item.p7.leads)/item.p7.leads*100).toFixed(1)):null;item.cpl_delta_pct=item.p7.cpl&&item.d7.cpl?Number(((item.d7.cpl-item.p7.cpl)/item.p7.cpl*100).toFixed(1)):null;return item;});
}

function healthSummary(rows: any[], clientNames: Map<string,string>) {
  const grouped = new Map<string, any[]>();
  for (const row of rows ?? []) { if (!row.client_id) continue; if(!grouped.has(row.client_id))grouped.set(row.client_id,[]);grouped.get(row.client_id)!.push(row); }
  return [...grouped.entries()].map(([id,list])=>{list.sort((a,b)=>new Date(a.captured_at||a.observed_at).getTime()-new Date(b.captured_at||b.observed_at).getTime());const first=list[0],last=list[list.length-1],a=Number(first?.health_score),b=Number(last?.health_score);return{client_id:id,client:clientNames.get(id)||last?.client_name_raw||id,first_at:first?.captured_at||first?.observed_at,last_at:last?.captured_at||last?.observed_at,first_score:Number.isFinite(a)?a:null,last_score:Number.isFinite(b)?b:null,score_delta:Number.isFinite(a)&&Number.isFinite(b)?Number((b-a).toFixed(1)):null,first_risk:first?.risk_level,last_risk:last?.risk_level,last_summary:clip(last?.summary,280)};}).sort((a,b)=>(a.score_delta??0)-(b.score_delta??0));
}

function dispatchSummary(rows: any[]) {
  const recipients = new Map<string, any>(); const leads = new Map<string, Set<string>>();
  for (const row of rows ?? []) {
    const dest=String(row.recipient_phone||"sem_destino"); const key=`${row.expected_client_id||row.recipient_client_id||"none"}|${dest}`;
    if(!recipients.has(key))recipients.set(key,{client_id:row.expected_client_id||row.recipient_client_id||null,recipient_phone:dest,dispatches:0,routing_problems:0});
    const r=recipients.get(key);r.dispatches++;if(!/MATCH|OK|CORRECT/i.test(String(row.routing_status||"")))r.routing_problems++;
    const lk=norm(`${row.lead_phone||""}|${row.lead_email||""}|${row.product_label||""}`);if(lk){if(!leads.has(lk))leads.set(lk,new Set());leads.get(lk)!.add(dest);}
  }
  return { by_recipient:[...recipients.values()].sort((a,b)=>b.dispatches-a.dispatches), possible_multi_recipient:[...leads.entries()].filter(([,d])=>d.size>1).slice(0,100).map(([lead_key,d])=>({lead_key,recipients:[...d]})) };
}

async function loadAdvancedEvidence(ops:any, role:string, person:string, question:string, clients:any[], roster:any[]) {
  const permitted=scopedClients(role,person,clients); const ids=permitted.map(c=>c.id); const unrestricted=teamWide(role); const client=resolveEntity(question,permitted,"display_name",4); const mentioned=resolveEntity(question,roster,"person",3); const names=new Map(clients.map(c=>[c.id,c.display_name]));
  const coverage:Record<string,string>={}; const pack:any={context:{client:client?{id:client.id,name:client.display_name,lifecycle:client.lifecycle,entrada:client.entrada,saida:client.saida,gt_owner:client.gt_owner,cs_owner:client.cs_owner,designer_owner:client.designer_owner}:null,mentioned_person:mentioned?{person:mentioned.person,role:mentioned.role}:null,user:{person,role}},generated_at:new Date().toISOString()};
  const run=async(label:string,factory:()=>any)=>{try{const{data,error}=await factory();if(error)throw error;coverage[label]="OK";return data??[];}catch(error){coverage[label]=`UNAVAILABLE:${clip(error instanceof Error?error.message:error,100)}`;return[];}};
  const scopeQ=(q:any)=>client?q.eq("client_id",client.id):(!unrestricted?(ids.length?q.in("client_id",ids):q.eq("client_id","00000000-0000-0000-0000-000000000000")):q);
  const jobs:Promise<void>[]=[];

  jobs.push((async()=>{let q=scopeQ(ops.from("client_operational_snapshot").select("*")).order("last_activity_at",{ascending:false});pack.operational=compact(await run("operational",()=>q.limit(client?12:180)),["client_id","priority","waiting_direction","summary_today","current_subject","action_owner","next_step","next_step_due","open_commitments","overdue_commitments","open_complaints","pending_approvals","blockers","data_coverage","confidence","evidence","last_activity_at","snapshot_at"],client?12:180);})());
  jobs.push((async()=>{let q=scopeQ(ops.from("client_health_external_history").select("client_id,client_name_raw,health_status,health_score,risk_level,satisfaction_avg,risk_avg,summary,recommended_action,observed_at,captured_at")).gte("captured_at",daysAgo(45)).order("captured_at",{ascending:true});pack.health_velocity=healthSummary(await run("health_history",()=>q.limit(client?350:2600)),names).slice(0,client?10:180);})());
  jobs.push((async()=>{let q=scopeQ(ops.from("commitments").select("*")).order("due_at",{ascending:true,nullsFirst:false});pack.commitments=compact(await run("commitments",()=>q.limit(client?220:1000)),["client_id","origem","descricao","owner","due_at","status","task_id","evidencia","confirmed_by_human","created_at","updated_at"],client?220:1000);})());
  jobs.push((async()=>{let q=scopeQ(ops.from("work_items").select("*")).order("priority",{ascending:false});pack.work_items=compact(await run("work_items",()=>q.limit(client?320:1000)),["client_id","type","status","priority","title","description","source","created_by_person","target_role","target_person","due_at","started_at","completed_at","completed_by","resolution","created_at","updated_at"],client?320:1000);})());
  jobs.push((async()=>{let q=scopeQ(ops.from("media_metrics_daily").select("client_id,date,spend,impressions,clicks,leads,cpl,ctr,cpc,campaign_count,source")).gte("date",daysAgo(35).slice(0,10));pack.media_trends=mediaSummary(await run("media",()=>q.limit(client?2200:8500)),names).slice(0,client?10:200);})());
  jobs.push((async()=>{let q=scopeQ(ops.from("meta_campaign_insights").select("client_id,campaign_id,campaign_name,campaign_status,objective,date_start,date_stop,spend,impressions,clicks,ctr,cpc,cpm,reach,frequency,leads_estimate,cost_per_lead_estimate,checked_at,result_type,result_count,cost_per_result,result_source")).gte("checked_at",daysAgo(35)).order("checked_at",{ascending:false});pack.campaigns=compact(await run("campaigns",()=>q.limit(client?900:1800)),["client_id","campaign_id","campaign_name","campaign_status","objective","date_start","date_stop","spend","impressions","clicks","ctr","cpc","cpm","reach","frequency","leads_estimate","cost_per_lead_estimate","checked_at","result_type","result_count","cost_per_result","result_source"],client?900:1400);})());
  if(role!=="DESIGN") jobs.push((async()=>{let q=scopeQ(ops.from("weekly_commercial_reports").select("*")).order("week_end",{ascending:false});pack.commercial=compact(await run("commercial",()=>q.limit(client?100:500)),["client_id","week_start","week_end","commercial_leads","meta_leads","meta_cross_status","meta_difference","meta_difference_pct","confidence_level","metrics","previous_metrics","reporters","context","internal_warning","source_summary","generated_at"],client?100:500);let lr=scopeQ(ops.from("lead_reconciliation").select("*")).order("period_end",{ascending:false});pack.lead_reconciliation=compact(await run("lead_reconciliation",()=>lr.limit(client?80:300)),["client_id","period_start","period_end","meta_leads","crm_leads","delta","ratio","source_crm","status","metadata"],client?80:300);let w=scopeQ(ops.from("client_won_events").select("dedupe_key,client_id,occurred_at,initial_source,confidence,evidence").not("client_id","is",null)).order("occurred_at",{ascending:false});pack.linked_sales=compact(await run("linked_sales",()=>w.limit(client?200:800)),["dedupe_key","client_id","occurred_at","initial_source","confidence","evidence"],client?200:800);})());
  jobs.push((async()=>{let q=scopeQ(ops.from("onboarding_sla_board").select("*")).order("due_at",{ascending:true});pack.onboarding_sla=compact(await run("onboarding_sla",()=>q.limit(client?150:800)),["client_id","display_name","event_type","status","responsible_role","responsible_person","started_at","due_at","completed_at","evidence","sla_status","overdue_minutes"],client?150:800);})());
  jobs.push((async()=>{let q=scopeQ(ops.from("client_adjustments").select("*")).gte("occurred_at",daysAgo(180)).order("occurred_at",{ascending:false});pack.adjustments=compact(await run("adjustments",()=>q.limit(client?550:1800)),["client_id","tipo","descricao","occurred_at","responsible_person","category_code","subcategory_code","reason","request_origin","responsible_area","status","severity","resolution","is_recurrent","created_at","updated_at","resolved_at"],client?550:1800);})());
  jobs.push((async()=>{let q=scopeQ(ops.from("weekly_traffic_reports").select("client_id,week_start,week_end,client_name,gt_owner,summary,report_text,data_status,review_status,generated_at")).order("week_end",{ascending:false});pack.traffic_reports=compact(await run("traffic_reports",()=>q.limit(client?60:300)),["client_id","week_start","week_end","client_name","gt_owner","summary","report_text","data_status","review_status","generated_at"],client?60:300);let e=scopeQ(ops.from("traffic_experiments").select("*")).order("start_at",{ascending:false});pack.traffic_experiments=compact(await run("traffic_experiments",()=>e.limit(client?100:400)),["client_id","title","experiment_type","hypothesis","variable_tested","control_description","variant_description","primary_metric","baseline_value","result_value","start_at","end_at","status","conclusion","result_summary","learning","campaign_ids"],client?100:400);})());

  if(client) jobs.push((async()=>{const chats=await run("client_chats",()=>ops.from("whatsapp_chat_registry").select("chat_id,chat_name,scope,last_seen_at,message_count").eq("client_id",client.id).limit(120));const chatIds=chats.map((r:any)=>r.chat_id).filter(Boolean);pack.chats=chats;const [daily,timeline,events]=await Promise.all([run("daily",()=>ops.from("client_daily_summary").select("*").eq("client_id",client.id).gte("summary_date",daysAgo(90).slice(0,10)).order("summary_date",{ascending:true}).limit(120)),run("timeline",()=>ops.from("client_timeline").select("event_type,at,detail,source").eq("client_id",client.id).gte("at",daysAgo(180)).order("at",{ascending:true}).limit(800)),run("events",()=>ops.from("client_event_activity").select("*").eq("client_id",client.id).gte("occurred_at",daysAgo(180)).order("occurred_at",{ascending:true}).limit(600))]);pack.daily=compact(daily,["summary_date","priority","waiting_direction","summary","deliveries","approvals","pending_items","promises","blockers","next_steps","evidence"],120);pack.timeline=compact(timeline,["event_type","at","detail","source"],800);pack.events=compact(events,["event_type","event_status","severity","title","details","occurred_at","due_at","resolved_at","responsible_employee_name","responsible_employee_role","source_key"],600);if(chatIds.length){const[sem,state,msg]=await Promise.all([run("semantic",()=>ops.from("conversation_semantic_state").select("*").in("chat_id",chatIds).limit(120)),run("conversation_state",()=>ops.from("conversation_state").select("*").in("chat_id",chatIds).limit(120)),run("whatsapp",()=>ops.from("whatsapp_messages").select("message_id,chat_id,chat_name,sender_name,from_me,event_at,message_type,text_body,caption").in("chat_id",chatIds).gte("event_at",daysAgo(120)).order("event_at",{ascending:false}).limit(550))]);pack.semantic=compact(sem,["chat_id","priority","waiting_direction","current_subject","today_summary","client_requests","team_actions","deliveries","decisions","approvals","pending_items","next_steps","blockers","complaints","promises","confidence","processed_at"],120);pack.conversation_state=compact(state,["chat_id","last_client_message_at","last_team_message_at","waiting_for_agency","waiting_since","waiting_for_client","open_question","conversation_status","sla_level","last_summary","last_actor","last_message_requires_response"],120);pack.whatsapp=compact(msg,["message_id","chat_name","sender_name","from_me","event_at","message_type","text_body","caption"],550);}})());
  else jobs.push((async()=>{let q=ops.from("conversation_semantic_state").select("client_id,priority,waiting_direction,current_subject,today_summary,client_requests,team_actions,pending_items,next_steps,blockers,complaints,promises,confidence,processed_at").order("priority",{ascending:false});if(!unrestricted)q=ids.length?q.in("client_id",ids):q.eq("client_id","00000000-0000-0000-0000-000000000000");pack.semantic=compact(await run("semantic",()=>q.limit(420)),["client_id","priority","waiting_direction","current_subject","today_summary","client_requests","team_actions","pending_items","next_steps","blockers","complaints","promises","confidence","processed_at"],420);})());

  if(role!=="DESIGN") jobs.push((async()=>{let q=ops.from("meta_lead_dispatches").select("message_id,event_at,recipient_phone,product_label,lead_name,lead_phone,lead_email,recipient_client_id,expected_client_id,routing_status").gte("event_at",daysAgo(60)).order("event_at",{ascending:false});if(client)q=q.or(`recipient_client_id.eq.${client.id},expected_client_id.eq.${client.id}`);let rows=await run("lead_dispatches",()=>q.limit(client?1600:5000));if(!client&&!unrestricted)rows=rows.filter((r:any)=>ids.includes(r.expected_client_id)||ids.includes(r.recipient_client_id));pack.lead_dispatch=dispatchSummary(rows);})());

  jobs.push((async()=>{let tq=ops.from("op_perf_task_facts").select("person,role,task_name,status,date_created,date_closed,due_date,completed,is_adjustment,hours_to_close,on_time").gte("date_created",daysAgo(30)).order("date_created",{ascending:false});let wq=ops.from("op_perf_current_workload").select("person,role,open_tasks,overdue_tasks");let rq=ops.from("op_perf_cs_response_times").select("cs_person,response_minutes,client_msg_at,reply_at").gte("client_msg_at",daysAgo(30));if(!teamWide(role)){tq=tq.eq("person",person);wq=wq.eq("person",person);rq=role==="CS"?rq.eq("cs_person",person):rq.eq("cs_person","__NO_MATCH__");}else if(mentioned){tq=tq.eq("person",mentioned.person);wq=wq.eq("person",mentioned.person);if(mentioned.role==="CS")rq=rq.eq("cs_person",mentioned.person);}const[tasks,workload,responses]=await Promise.all([run("task_perf",()=>tq.limit(5000)),run("workload",()=>wq.limit(200)),run("response_times",()=>rq.limit(6000))]);pack.task_performance=compact(tasks,["person","role","task_name","status","date_created","date_closed","due_date","completed","is_adjustment","hours_to_close","on_time"],mentioned||!teamWide(role)?1200:2000);pack.workload=workload;pack.response_stats=responseStats(responses);})());

  if((role==="MGMT"||person==="Adler Furtado")&&(client||/contrato|renovacao|vigencia|vencimento/i.test(question))) jobs.push((async()=>{let q=scopeQ(ops.from("client_contract_status").select("*")).order("days_remaining",{ascending:true});pack.contracts=compact(await run("contracts",()=>q.limit(client?30:260)),["client_id","display_name","document_name","document_status","contract_start_date","contract_end_date","days_remaining","contract_state","renewal_pending","tasks_last_30d","last_task_at","inconsistency"],client?30:260);})());

  await Promise.all(jobs);pack.coverage=coverage;pack.data_gaps={google_sheets_direct:"NOT_CONNECTED — sem credencial Google/Sheets no backend; aderência diária por corretor não pode ser confirmada diretamente pela planilha ainda.",legacy_sales:"Eventos legados de venda sem client_id são ignorados para não atribuir venda ao cliente errado.",experiments:Array.isArray(pack.traffic_experiments)&&pack.traffic_experiments.length===0?"EMPTY — sem experimentos estruturados; causa em mídia/criativo só pode ser tratada como indício temporal.":"AVAILABLE_OR_NOT_REQUESTED"};return{pack,client,mentioned};
}

function prompt(question:string,person:string,role:string,pack:any,previous:any){let ctx=JSON.stringify(pack);if(ctx.length>MAX_CONTEXT)ctx=`${ctx.slice(0,MAX_CONTEXT)}\n[CONTEXTO TRUNCADO]`;const prior=previous?.question?`Pergunta anterior: ${clip(previous.question,450)}\nResposta anterior: ${clip(previous.answer,800)}`:"Sem contexto anterior relevante.";return `Você é o OpsQuestion v4, copiloto de gestão operacional da Leonardo Imobi. Esta é uma pergunta avançada: raciocine sobre tempo, causa, tendência, qualidade e decisão usando as evidências.\n\nREGRAS ABSOLUTAS:\n1. Cruze as fontes; ausência em uma fonte não prova ausência do fato.\n2. Reconstrua antes/depois quando houver histórico, piora, melhora, churn, mudança de responsável, campanha ou criativo.\n3. Causalidade: use CONFIRMADO somente com evidência explícita/experimento; INDÍCIO FORTE para sequência temporal coerente em múltiplas fontes; HIPÓTESE quando só houver coincidência plausível.\n4. Venda: quantidade exige relatório comercial ou evento vinculado ao cliente. Mensagem explícita confirma ocorrência, não contagem total. Não atribua ao tráfego sem origem comprovada.\n5. Diferencie lead Meta, disparado, recebido/trabalhado, visita, proposta e venda. Não invente nome de corretor a partir de telefone.\n6. Meta: compare períodos equivalentes e considere CPL, CTR, frequência, volume, entrega e comercial. Um dia isolado não justifica decisão de orçamento.\n7. Atendimento: tempo de resposta não basta; cruze reclamação, pergunta aberta, promessa, retorno e reincidência.\n8. Performance: volume de tasks não basta; cruze prazo, atraso, carga, retrabalho e função.\n9. Retrabalho: diferencie erro interno, pedido estético, mudança de opinião e briefing incompleto. Não atribua culpa sem evidência.\n10. Previsão: fale em risco/tendência, não certeza, e cite sinais antecedentes.\n11. Se fontes divergirem, diga. Se faltar dado essencial, diga exatamente o que falta.\n12. Não exponha nomes técnicos de tabelas ou schemas.\n13. Datas relativas usam America/Sao_Paulo.\n14. Para perguntas de diagnóstico/gestão, finalize com “Próximos passos” e 1 a 3 ações em ordem, com responsável provável e motivo. Se não houver nome comprovado, use a função (CS, GT, Designer, Operações).\n15. SOMENTE LEITURA: não diga que executou ações.\n16. Se a pergunta for “se você fosse o Adler”, priorize churn, SLA, resultado, receita, cliente e capacidade da equipe.\n17. Se a confiança não for alta, finalize com “Confiança: média” ou “Confiança: baixa” e o motivo.\n\nUsuário: ${person} (${role})\n${prior}\n\nPERGUNTA:\n${question}\n\nEVIDÊNCIAS:\n${ctx}\n\nResponda direto, com a conclusão primeiro.`;}

async function callAi(ops:any,promptText:string,question:string,person:string,role:string,requestId:string){const[{data:endpointRow},{data:secretRow}]=await Promise.all([ops.from("automation_settings").select("value").eq("key","AI_ASK_ENDPOINT_URL").maybeSingle(),ops.from("automation_settings").select("value").eq("key","AI_ASK_READ_SECRET").maybeSingle()]);const endpoint=typeof endpointRow?.value==="string"?endpointRow.value:null;const secret=typeof secretRow?.value==="string"?secretRow.value:null;if(!endpoint||!secret)throw new Error("direct_ai_not_configured");const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),AI_TIMEOUT_MS);try{const res=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json","x-ai-read-secret":secret},body:JSON.stringify({question:promptText,original_question:question,source:"OpsQuestionCausalV4",request_id:requestId,user:{person,role,scope:"causal_read_only"},constraints:{read_only:true,timezone:"America/Sao_Paulo",no_invention:true,temporal_reasoning:true,causal_labels:true,action_plan:true}}),signal:controller.signal});const raw=await res.text();let body:any=null;try{body=raw?JSON.parse(raw):null;}catch{}if(!res.ok)throw new Error(`ai_${res.status}:${clip(raw,180)}`);const answer=safeAnswer(body,raw);if(!answer)throw new Error("empty_ai");return answer;}finally{clearTimeout(timeout);}}

async function proxyV3(url:string,anon:string,authorization:string,body:any){const res=await fetch(`${url}${V3_PATH}`,{method:"POST",headers:{Authorization:authorization,apikey:anon,"content-type":"application/json"},body:JSON.stringify(body)});return{res,raw:await res.text()};}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});if(req.method!=="POST")return reply({ok:false,error:"method_not_allowed"},405);const url=Deno.env.get("SUPABASE_URL")??"",anon=Deno.env.get("SUPABASE_ANON_KEY")??"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";if(!url||!anon||!service)return reply({ok:false,error:"server_configuration"},500);const authorization=req.headers.get("Authorization")??"";if(!authorization.startsWith("Bearer "))return reply({ok:false,error:"unauthorized"},401);const body=await req.json().catch(()=>({}));const question=typeof body?.question==="string"?body.question.trim():"";if(!question)return reply({ok:false,error:"missing_question"},400);if(question.length>2500)return reply({ok:false,error:"question_too_long"},400);
  if(!ADVANCED.test(norm(question))){const{res,raw}=await proxyV3(url,anon,authorization,body);return new Response(raw,{status:res.status,headers:{...CORS,"content-type":res.headers.get("content-type")||"application/json; charset=utf-8","cache-control":"no-store","x-opsquestion-route":"v3-fast"}});}
  const auth=createClient(url,anon,{global:{headers:{Authorization:authorization}},auth:{persistSession:false,autoRefreshToken:false}});const{data:userData}=await auth.auth.getUser();const user=userData?.user;if(!user)return reply({ok:false,error:"unauthorized"},401);const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const ops=db.schema("agency_ops");const[{data:pref},{data:approvals},{data:roster},{data:clients}]=await Promise.all([ops.from("user_preferences").select("collaborator_person").eq("user_key",user.id).maybeSingle(),ops.from("access_requests").select("kind,status").eq("user_key",user.id).eq("kind","SIGNUP").eq("status","APPROVED"),ops.from("team_roster").select("person,role,access_level,is_former").eq("is_former",false),ops.from("clients").select("id,display_name,lifecycle,gt_owner,cs_owner,designer_owner,entrada,saida").in("lifecycle",["ACTIVE","ONBOARDING","CHURNED"]).limit(600)]);const person=pref?.collaborator_person??null;const member=(roster??[]).find((r:any)=>r.person===person);if(!person||!member||!(approvals??[]).length)return reply({ok:false,error:"OpsQuestion indisponível: conta ainda não liberada."},403);const role=String(member.role||"");const requestId=crypto.randomUUID(),started=Date.now();const{data:previousRows}=await ops.from("opsquestion_interactions").select("question,answer,created_at").eq("user_key",user.id).eq("status","SUCCESS").order("created_at",{ascending:false}).limit(1);try{const{pack,client,mentioned}=await loadAdvancedEvidence(ops,role,String(person),question,clients??[],roster??[]);const answer=await callAi(ops,prompt(question,String(person),role,pack,previousRows?.[0]),question,String(person),role,requestId);const latency=Date.now()-started;await ops.from("opsquestion_interactions").insert({user_key:user.id,person,role,access_level:String(member.access_level||"RESTRICTED"),question,status:"SUCCESS",source:"CAUSAL_EVIDENCE_V4",answer:answer.slice(0,20000),request_id:requestId,latency_ms:latency,answered_at:new Date().toISOString()});return reply({ok:true,name:"OpsQuestion",answer,source:"Base operacional · inteligência causal",read_only:true,mode:"CAUSAL_EVIDENCE_V4",client:client?.display_name??null,person_mentioned:mentioned?.person??null,coverage:pack.coverage,data_gaps:pack.data_gaps,request_id:requestId,latency_ms:latency,generated_at:new Date().toISOString()});}catch(error){console.error("[opsquestion-v4]",error);const{res,raw}=await proxyV3(url,anon,authorization,body);return new Response(raw,{status:res.status,headers:{...CORS,"content-type":res.headers.get("content-type")||"application/json; charset=utf-8","cache-control":"no-store","x-opsquestion-fallback":"v3"}});}});
