import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const CORS={"access-control-allow-origin":"*","access-control-allow-headers":"authorization,apikey,content-type","access-control-allow-methods":"POST,OPTIONS"};
const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const norm=(v:unknown)=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
function isAiDemand(body:any){const m=body?.metadata??{};if(m.ai_workspace===true||m.n8n_verified===true||m.ai_classified===true)return true;const h=norm(`${body?.title??""} ${body?.description??""}`);if(/\bagente\b|\bn8n\b|chatbot|bot de atendimento|automacao|webhook|prompt|llm|openai|assistente virtual|fluxo de atendimento/.test(h))return true;return /\bia\b.{0,80}(lead|atendimento|agente|fluxo|whatsapp|automacao|integracao|prompt|resposta)|(?:lead|atendimento|agente|fluxo|whatsapp|automacao|integracao|prompt|resposta).{0,80}\bia\b/.test(h);}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});if(req.method!=="POST")return reply({error:"method_not_allowed"},405);
 const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const auth=req.headers.get("Authorization")??"";if(!auth.startsWith("Bearer "))return reply({error:"unauthorized"},401);
 const ac=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const{data:ud}=await ac.auth.getUser();if(!ud?.user)return reply({error:"unauthorized"},401);const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const ops=db.schema("agency_ops");
 const[{data:pref},{data:approval}]=await Promise.all([ops.from("user_preferences").select("collaborator_person").eq("user_key",ud.user.id).maybeSingle(),ops.from("access_requests").select("id").eq("user_key",ud.user.id).eq("kind","SIGNUP").eq("status","APPROVED").limit(1)]);if(pref?.collaborator_person!=="Gabriel Castro"||!(approval??[]).length)return reply({error:"forbidden"},403);
 const body=await req.json().catch(()=>null);if(!body)return reply({error:"invalid_json"},400);const clientId=String(body.client_id??"");if(!clientId)return reply({error:"client_required"},400);const{data:aiRows,error:aiError}=await ops.rpc("ai_ours_active_client_ids");if(aiError)return reply({error:"ai_scope_failed"},500);const allowed=new Set((aiRows??[]).map((r:any)=>String(r.client_id)));if(!allowed.has(clientId))return reply({error:"forbidden_client_scope"},403);if(!isAiDemand(body))return reply({error:"not_ai_demand",detail:"A Central de Trabalho do Gabriel aceita somente demandas identificadas como alteração/manutenção da IA da agência."},422);
 const forwarded={...body,client_id:clientId,type:"TECHNICAL",target_role:"AI",target_person:"Gabriel Castro",metadata:{...(body.metadata??{}),ai_workspace:true,n8n_verified:true,ai_classified:true,ai_scope_model:"AI_N8N_CLIENTS"}};
 const response=await fetch(`${url}/functions/v1/agency-ops-work-item-create-api`,{method:"POST",headers:{Authorization:auth,apikey:anon,"content-type":"application/json"},body:JSON.stringify(forwarded)});return new Response(response.body,{status:response.status,headers:{...CORS,"content-type":response.headers.get("content-type")||"application/json","cache-control":"no-store"}});
});
