import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import postgres from "npm:postgres@3.4.5";

const sql=postgres(Deno.env.get("SUPABASE_DB_URL")!,{prepare:false,max:2});
const BASE="https://www.googleapis.com/drive/v3";
const SB=Deno.env.get("SUPABASE_URL")||"";
const SR=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const ACCOUNT="lakassessoriadigital";
const ROOT="1-FIIyg51Wbe5GbMXagDcB6XxWhKmdY9A";
const CALLBACK=`${SB}/functions/v1/drive-change-webhook`;
type B={client_id:string;drive_folder_id:string;display_name:string};

const js=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
const clip=(v:unknown,n=600)=>String(v??"").slice(0,n);
function eq(a:string,b:string){const x=new TextEncoder().encode(a),y=new TextEncoder().encode(b);if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0;}
function b64u(v:string|Uint8Array){const a=typeof v==="string"?new TextEncoder().encode(v):v;let s="";for(let i=0;i<a.length;i+=0x8000)s+=String.fromCharCode(...a.subarray(i,i+0x8000));return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
function pem(v:string){const s=v.replace(/-----BEGIN [^-]+-----/g,"").replace(/-----END [^-]+-----/g,"").replace(/\s+/g,"");return Uint8Array.from(atob(s),c=>c.charCodeAt(0));}
async function vault(n:string){const r=await sql`select decrypted_secret from vault.decrypted_secrets where name=${n} limit 1`;return r.length&&r[0].decrypted_secret?String(r[0].decrypted_secret):null;}
async function setting(n:string){const r=await sql`select value #>> '{}' as v from agency_ops.automation_settings where key=${n} limit 1`;return r.length&&r[0].v?String(r[0].v):null;}
async function mode(){const [sa,id,sec,ref]=await Promise.all([vault("drive_google_service_account_json"),vault("drive_google_oauth_client_id"),vault("drive_google_oauth_client_secret"),vault("drive_google_oauth_refresh_token")]);if(sa)return"SERVICE_ACCOUNT";if(id&&sec&&ref)return"OAUTH_REFRESH";return"UNCONFIGURED";}
async function token(){
 const saRaw=await vault("drive_google_service_account_json");
 if(saRaw){const sa=JSON.parse(saRaw),now=Math.floor(Date.now()/1000);if(!sa.client_email||!sa.private_key)throw new Error("service_account_invalid");const h=b64u(JSON.stringify({alg:"RS256",typ:"JWT"})),p=b64u(JSON.stringify({iss:sa.client_email,scope:"https://www.googleapis.com/auth/drive",aud:sa.token_uri||"https://oauth2.googleapis.com/token",iat:now,exp:now+3600}));const k=await crypto.subtle.importKey("pkcs8",pem(sa.private_key),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",k,new TextEncoder().encode(`${h}.${p}`));const r=await fetch(sa.token_uri||"https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion:`${h}.${p}.${b64u(new Uint8Array(sig))}`})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.access_token)throw new Error(`google_sa_token_${r.status}:${clip(j?.error_description||j?.error)}`);return String(j.access_token);}
 const [id,sec,ref]=await Promise.all([vault("drive_google_oauth_client_id"),vault("drive_google_oauth_client_secret"),vault("drive_google_oauth_refresh_token")]);if(!id||!sec||!ref)throw new Error("google_credentials_missing");const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:id,client_secret:sec,refresh_token:ref,grant_type:"refresh_token"})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.access_token)throw new Error(`google_oauth_${r.status}:${clip(j?.error_description||j?.error)}`);return String(j.access_token);
}
async function g(tok:string,url:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{...(init.headers||{}),authorization:`Bearer ${tok}`}});if(r.status===404||r.status===410)return{ok:false,data:null,status:r.status};const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`drive_${r.status}:${clip(j?.error?.message||j?.error||JSON.stringify(j))}`);return{ok:true,data:j,status:r.status};}
async function state(){const r=await sql`select * from agency_ops.drive_change_watch_state where account_key=${ACCOUNT} limit 1`;return r[0]||null;}
async function bindings(root:string){const r=await sql`select b.client_id::text,b.drive_folder_id,c.display_name from agency_ops.client_drive_bindings b join agency_ops.clients c on c.id=b.client_id where b.binding_status='VERIFIED' and b.drive_root_id=${root}`;const m=new Map<string,B>();for(const x of r as any[])m.set(String(x.drive_folder_id),{client_id:String(x.client_id),drive_folder_id:String(x.drive_folder_id),display_name:String(x.display_name||"Cliente")});return m;}
async function file(tok:string,id:string){const r=await g(tok,`${BASE}/files/${encodeURIComponent(id)}?fields=id,name,mimeType,parents,trashed&supportsAllDrives=true`);return r.ok?r.data:null;}
async function bound(tok:string,parents:string[],map:Map<string,B>,root:string){const q=(parents||[]).map(id=>({id,depth:0})),seen=new Set<string>();while(q.length){const c=q.shift()!;if(seen.has(c.id)||c.depth>10)continue;seen.add(c.id);const b=map.get(c.id);if(b)return b;if(c.id===root)continue;const f=await file(tok,c.id);if(!f)continue;for(const p of f.parents||[])q.push({id:String(p),depth:c.depth+1});}return null;}
async function ingest(f:any,b:B){const s=await setting("MATERIAL_INGEST_SECRET");if(!s)throw new Error("material_ingest_secret_missing");const r=await fetch(`${SB}/functions/v1/raw-material-upload-ingest`,{method:"POST",headers:{"content-type":"application/json","x-material-ingest-secret":s},body:JSON.stringify({drive_file_id:f.id,file_name:f.name||f.id,client_folder_name:b.display_name,mime_type:f.mimeType||null,file_size_bytes:f.size?Number(f.size):null,drive_folder_id:b.drive_folder_id,drive_uploaded_at:f.createdTime||f.modifiedTime||new Date().toISOString()})});const j=await r.json().catch(()=>({}));if(!r.ok||j?.ok!==true)throw new Error(`raw_ingest_${r.status}:${clip(j?.error||JSON.stringify(j))}`);}
async function advance(old:string,next:string){const r=await sql`update agency_ops.drive_change_watch_state set page_token=${next},last_success_at=now(),last_error=null,status='ACTIVE',updated_at=now() where account_key=${ACCOUNT} and page_token=${old} returning page_token`;return r.length>0;}
async function drain(tok:string,eventId?:number){const st=await state();if(!st?.page_token)throw new Error("page_token_missing");const root=String(st.root_folder_id||ROOT),map=await bindings(root);let pt=String(st.page_token),changes=0,ingested=0,skipped=0;for(let pg=0;pg<20;pg++){const p=new URLSearchParams({pageToken:pt,pageSize:"200",spaces:"drive",includeRemoved:"true",includeItemsFromAllDrives:"true",supportsAllDrives:"true",fields:"nextPageToken,newStartPageToken,changes(fileId,removed,time,file(id,name,mimeType,size,createdTime,modifiedTime,parents,trashed))"});const r=await g(tok,`${BASE}/changes?${p}`),d=r.data||{};for(const ch of d.changes||[]){changes++;const f=ch.file;if(ch.removed||!f||f.trashed||f.mimeType==="application/vnd.google-apps.folder"){skipped++;continue;}const b=await bound(tok,(f.parents||[]).map(String),map,root);if(!b){skipped++;continue;}await ingest(f,b);ingested++;}const next=String(d.nextPageToken||d.newStartPageToken||"");if(!next)throw new Error("drive_change_token_missing");if(!await advance(pt,next))break;pt=next;if(!d.nextPageToken)break;}if(eventId)await sql`update agency_ops.drive_change_watch_events set processed_at=now(),changes_count=${changes},ingested_count=${ingested},skipped_count=${skipped},error=null where id=${eventId}`;return{changes_count:changes,ingested_count:ingested,skipped_count:skipped};}
async function register(force:boolean){const md=await mode();if(md==="UNCONFIGURED")throw new Error("google_credentials_missing");const tok=await token(),old=await state();if(!force&&old?.status==="ACTIVE"&&old.channel_expires_at&&new Date(old.channel_expires_at).getTime()-Date.now()>36*3600_000)return{ok:true,renewed:false,reason:"not_due",expires_at:old.channel_expires_at};let pt=old?.page_token?String(old.page_token):"";if(!pt){const s=await g(tok,`${BASE}/changes/startPageToken?supportsAllDrives=true`);pt=String(s.data?.startPageToken||"");if(!pt)throw new Error("start_page_token_missing");}const ct=await vault("drive_change_channel_token");if(!ct)throw new Error("channel_token_missing");const id=crypto.randomUUID(),exp=Date.now()+6*24*3600_000;const w=await g(tok,`${BASE}/changes/watch?${new URLSearchParams({pageToken:pt,spaces:"drive",supportsAllDrives:"true"})}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,type:"web_hook",address:CALLBACK,token:ct,expiration:String(exp)})});const rid=String(w.data?.resourceId||"");if(!rid)throw new Error("watch_resource_id_missing");const at=new Date(Number(w.data?.expiration||exp)).toISOString();await sql`update agency_ops.drive_change_watch_state set page_token=${pt},channel_id=${id},resource_id=${rid},channel_expires_at=${at}::timestamptz,status='ACTIVE',last_error=null,metadata=coalesce(metadata,'{}'::jsonb)||${sql.json({auth_mode:md,provider:"GOOGLE_DRIVE_CHANGES_WATCH"})},updated_at=now() where account_key=${ACCOUNT}`;if(old?.channel_id&&old?.resource_id&&String(old.channel_id)!==id){try{await g(tok,`${BASE}/channels/stop`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:String(old.channel_id),resourceId:String(old.resource_id)})});}catch(e){console.error("stop_old",clip(e));}}return{ok:true,renewed:true,status:"ACTIVE",expires_at:at,auth_mode:md};}
async function admin(req:Request){const h=req.headers.get("x-drive-watch-admin")||"",v=await vault("drive_change_admin_token");if(v&&h&&eq(v,h))return true;const a=req.headers.get("authorization")||"";return !!SR&&a.startsWith("Bearer ")&&eq(a.slice(7),SR);}

Deno.serve(async(req:Request)=>{const u=new URL(req.url);if(req.method==="GET"&&u.searchParams.get("health")==="1"){try{const st=await state(),md=await mode();return js({ok:true,service:"drive-change-webhook",version:"1.1.0",status:st?.status||"UNCONFIGURED",channel_active:st?.status==="ACTIVE"&&!!st?.channel_id&&(!st.channel_expires_at||new Date(st.channel_expires_at).getTime()>Date.now()),expires_at:st?.channel_expires_at||null,google_auth:md,root_folder_configured:!!st?.root_folder_id});}catch{return js({ok:false,service:"drive-change-webhook"},500);}}
 const a=u.searchParams.get("action");if(a==="register"||a==="renew"||a==="drain"){if(!await admin(req))return js({ok:false,error:"unauthorized"},401);try{if(a==="drain")return js({ok:true,...await drain(await token())});return js(await register(a==="register"));}catch(e){const m=clip(e instanceof Error?e.message:e);if(m==="google_credentials_missing")await sql`update agency_ops.drive_change_watch_state set status='UNCONFIGURED',last_error=null,updated_at=now() where account_key=${ACCOUNT}`;else await sql`update agency_ops.drive_change_watch_state set status='ERROR',last_error=${m},updated_at=now() where account_key=${ACCOUNT}`;return js({ok:false,error:m},m==="google_credentials_missing"?409:500);}}
 if(req.method!=="POST")return js({ok:false,error:"method_not_allowed"},405);const got=req.headers.get("x-goog-channel-token")||"",want=await vault("drive_change_channel_token");if(!want||!got||!eq(want,got))return js({ok:false,error:"unauthorized_channel"},401);const st=await state(),cid=req.headers.get("x-goog-channel-id")||"",rid=req.headers.get("x-goog-resource-id")||"",rs=req.headers.get("x-goog-resource-state")||"unknown",mn=req.headers.get("x-goog-message-number")||"";if(st?.channel_id&&cid&&String(st.channel_id)!==cid)return new Response(null,{status:204});if(st?.resource_id&&rid&&String(st.resource_id)!==rid)return new Response(null,{status:204});const ins=await sql`insert into agency_ops.drive_change_watch_events(channel_id,resource_state,resource_id,message_number,metadata) values(${cid||null},${rs},${rid||null},${/^\d+$/.test(mn)?Number(mn):null},${sql.json({user_agent:clip(req.headers.get("user-agent"),120)})}) returning id`,eid=Number(ins[0].id);await sql`update agency_ops.drive_change_watch_state set last_notification_at=now(),updated_at=now() where account_key=${ACCOUNT}`;if(rs==="sync"){await sql`update agency_ops.drive_change_watch_events set processed_at=now() where id=${eid}`;return new Response(null,{status:204});}try{return js({ok:true,...await drain(await token(),eid)});}catch(e){const m=clip(e instanceof Error?e.message:e);await sql`update agency_ops.drive_change_watch_events set processed_at=now(),error=${m} where id=${eid}`;await sql`update agency_ops.drive_change_watch_state set status='ERROR',last_error=${m},updated_at=now() where account_key=${ACCOUNT}`;return js({ok:false,error:"processing_failed"},503);}});
