import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';
const $=id=>document.getElementById(id),BASE='/reader';
let pdf=null,page=1,fileMeta=null,renderToken=0,pageLoadToken=0,preloadGeneration=0,activeDocHash='',activeDocProfile=null;
let speaking=false,paused=false,sentenceIndex=0,currentSegments=[],pendingSentenceIndex=null,pendingSentenceOffset=0,currentSentenceOffset=0,pendingVoice=null;
let audioContext=null,currentSource=null,currentBuffer=null,audioTimeline=[],audioScheduleGeneration=0,audioFillRunning=false,highlightRaf=0,lastOffsetPersist=0;
let audiobookMode=localStorage.getItem('readerpro:audiobook')==='1',wakeLock=null;
let bookAnalysis={ready:false,repeated:new Set(),chapters:[]},analysisRunning=false;
let knownBookProfile=null,knownBookId='',knownBookSha256='';
let libraryBooks=[];
let pdfTextGeometry=[],sourceRanges=[];
let currentHighlightProgress=0,lastHighlightPaint=0;
const pageTextCache=new Map(),pdfContentCache=new Map(),translationCache=new Map(),translationPending=new Map();
const audioCache=new Map(),audioPending=new Map(),decodedAudioCache=new Map(),decodedAudioPending=new Map(),pageAudioWarmPending=new Map();
function setStatus(t){$('status').textContent=t;}
function setBuffer(t,ready=false){$('bufferBadge').textContent=t;$('bufferBadge').style.color=ready?'#7ee2b8':'#9ba7bd';}
function documentKey(){return fileMeta?`${activeDocHash||fileMeta.name}:${fileMeta.size}`:'';}
function bookKey(){return fileMeta?`readerpro:${documentKey()}`:null;}
function hashText(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(36);}
async function sha256Bytes(bytes){const view=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),digest=await crypto.subtle.digest('SHA-256',view);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function resolveDocumentProfile(bytes){activeDocHash=await sha256Bytes(bytes);try{const r=await fetch(BASE+'/api/document-profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sha256:activeDocHash,size:fileMeta?.size||0,pageCount:pdf?.numPages||0})});const d=await r.json();activeDocProfile=d?.known?d.profile:null;}catch{activeDocProfile=null;}return activeDocProfile;}
function docId(){return knownBookId||activeDocProfile?.id||'';}
function isNativeBook(){return !!knownBookProfile?.nativeText||String(knownBookProfile?.language||'').toLowerCase().startsWith('pt');}
function updateLanguageUi(){const native=isNativeBook(),el=document.querySelector('.readerHeader .eyebrow');if(el)el.textContent=native?'Leitura original • PT-BR':'Tradução simultânea • EN → PT-BR';}
async function sha256Hex(bytes){const view=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes),digest=await crypto.subtle.digest('SHA-256',view);return[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function detectKnownBook(bytes){knownBookProfile=null;knownBookId='';knownBookSha256='';try{knownBookSha256=await sha256Hex(bytes);activeDocHash=knownBookSha256;const r=await fetch(BASE+'/api/document-profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sha256:knownBookSha256})});const d=await r.json();if(r.ok&&d.known&&d.profile){knownBookProfile=d.profile;knownBookId=String(d.profile.id||'');activeDocHash=knownBookSha256;activeDocProfile=d.profile;if(Array.isArray(d.profile.chapters)&&d.profile.chapters.length)bookAnalysis.chapters=d.profile.chapters;return d.profile;}}catch(e){console.warn('book_profile_failed',e);}return null;}
const dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('readerpro-v2',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('kv'))r.result.createObjectStore('kv');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
async function dbGet(key){try{const db=await dbPromise;return await new Promise((r,j)=>{const q=db.transaction('kv').objectStore('kv').get(key);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});}catch{return undefined;}}
async function dbPut(key,value){try{const db=await dbPromise;await new Promise((r,j)=>{const tx=db.transaction('kv','readwrite');tx.objectStore('kv').put(value,key);tx.oncomplete=r;tx.onerror=()=>j(tx.error);});}catch{}}

function libraryProgress(book){try{const raw=localStorage.getItem(`readerpro:${book.sha256}:${book.size}`),p=JSON.parse(raw||'{}'),pg=Math.max(1,Math.min(Number(book.pageCount)||1,Number(p.page)||1));return{page:pg,pct:Math.max(0,Math.min(100,pg/Math.max(1,Number(book.pageCount)||1)*100)),has:!!raw};}catch{return{page:1,pct:0,has:false};}}
function coverUrl(book){return book?.coverUrl||(`${BASE}/assets/${book?.id?.startsWith('kotler')?'cover-kotler.jpg':book?.id?.startsWith('greene')?'cover-greene.jpg':'cover-zikmund.jpg'}`);}
function renderLibrary(){const grid=$('libraryGrid');if(!grid)return;if(!libraryBooks.length){grid.innerHTML='<div class="libraryEmpty">Nenhum livro disponível no acervo.</div>';return;}grid.innerHTML=libraryBooks.map(b=>{const p=libraryProgress(b),author=(b.authors||[]).join(' • ');return `<article class="bookCard"><div class="bookCoverFrame"><img class="bookCoverImg" src="${coverUrl(b)}" alt="Capa de ${b.title||'livro'}"></div><div><div class="bookTitle">${b.title||'Livro'}</div><div class="bookAuthors">${author}</div><div class="bookDesc">${b.description||'Livro pré-analisado no ReaderPro.'}</div><div class="bookProgress"><i style="width:${p.pct}%"></i></div><div class="bookMeta"><span>${p.has?`Página ${p.page} de ${b.pageCount}`:'Ainda não iniciado'}</span><span>${b.pageCount||0} páginas</span></div><div class="bookActions"><button class="btn primary" data-book-id="${b.id}" ${b.available?'':'disabled'}>${p.has?'Continuar leitura':'Ler agora'}</button></div></div></article>`;}).join('');grid.querySelectorAll('[data-book-id]').forEach(btn=>btn.addEventListener('click',()=>openLibraryBook(btn.dataset.bookId)));}
function showLibrary(){renderLibrary();$('libraryOverlay')?.classList.add('show');}
function hideLibrary(){$('libraryOverlay')?.classList.remove('show');}
async function loadLibrary(){try{const r=await fetch(BASE+'/api/library'),d=await r.json();libraryBooks=Array.isArray(d.books)?d.books:[];renderLibrary();}catch(e){console.warn('library_load_failed',e);}}
function activateProfile(profile){knownBookProfile=profile||null;knownBookId=String(profile?.id||'');knownBookSha256=String(profile?.sha256||'');activeDocHash=knownBookSha256;activeDocProfile=profile||null;if(Array.isArray(profile?.chapters))bookAnalysis.chapters=profile.chapters;updateLanguageUi();}

function saveProgress(){if(!bookKey())return;localStorage.setItem(bookKey(),JSON.stringify({page,sentenceIndex,sentenceOffset:currentSentenceOffset,rate:$('rate').value,voice:$('voice').value,audiobook:audiobookMode}));}
function restoreProgress(){if(!bookKey())return;try{const p=JSON.parse(localStorage.getItem(bookKey())||'{}');if(p.page)page=Math.min(Math.max(1,p.page),pdf.numPages);if(Number.isInteger(p.sentenceIndex))pendingSentenceIndex=p.sentenceIndex;if(Number.isFinite(p.sentenceOffset))pendingSentenceOffset=Math.max(0,p.sentenceOffset);if(p.rate)$('rate').value=p.rate;if(p.voice)pendingVoice=p.voice;if(typeof p.audiobook==='boolean')audiobookMode=p.audiobook;}catch{}}
function splitSentences(text,lang='pt-BR'){const normalized=String(text||'').replace(/\s*\n+\s*/g,' ').replace(/\s+/g,' ').trim();if(!normalized)return[];if(Intl?.Segmenter){const seg=new Intl.Segmenter(lang,{granularity:'sentence'});return[...seg.segment(normalized)].map(x=>x.segment.trim()).filter(Boolean);}return(normalized.match(/[^.!?…]+(?:[.!?…]+(?=\s|$)|$)/g)||[normalized]).map(x=>x.trim()).filter(Boolean);}
function isStructuralHeading(line){const s=String(line||'').trim();if(!s||s.length>180)return false;return /^(?:PREFÁCIO|O INVERSO|PARTE\s+(?:[IVX]+|\d+)|LEI\s+\d+)\b/i.test(s)||(s.length>=6&&s.length<=150&&s===s.toUpperCase()&&/[A-ZÁÉÍÓÚÃÕÂÊÔÇ]/.test(s)&&!/[.!?]$/.test(s));}
function splitNarrationChunks(text,lang='pt-BR',maxChars=180){const out=[];for(const sentence of splitSentences(text,lang)){if(sentence.length<=maxChars){out.push(sentence);continue;}const clauses=sentence.split(/(?<=[;:,.!?…])\s+/).filter(Boolean);let chunk='';const flush=()=>{if(chunk.trim())out.push(chunk.trim());chunk='';};for(const clause of clauses){if(clause.length>maxChars){flush();const words=clause.split(/\s+/);let part='';for(const w of words){if(part&&(`${part} ${w}`).length>maxChars){out.push(part);part=w;}else part=part?`${part} ${w}`:w;}if(part)out.push(part);continue;}if(chunk&&(`${chunk} ${clause}`).length>maxChars)flush();chunk=chunk?`${chunk} ${clause}`:clause;}flush();}return out;}
function nativeRecordFromText(original){const parts=[];for(const block of String(original||'').split(/\n+/)){const s=block.trim();if(!s)continue;if(isStructuralHeading(s))parts.push(s);else parts.push(...splitNarrationChunks(s,'pt-BR',180));}return{sourceText:original,translatedText:original,segments:parts.map((x,i)=>({id:i,source:x,target:x})),engine:'native-ptbr-v4',savedAt:Date.now()};}
function fallbackSegments(source,target){const a=splitSentences(source,'en-US'),b=splitSentences(target);if(!a.length||!b.length)return[];if(a.length===b.length)return a.map((x,i)=>({id:i,source:x,target:b[i]}));const out=[];for(let i=0;i<Math.max(a.length,b.length);i++){const si=Math.min(a.length-1,Math.floor(i*a.length/Math.max(a.length,b.length))),ti=Math.min(b.length-1,Math.floor(i*b.length/Math.max(a.length,b.length)));if(!out.some(x=>x.source===a[si]&&x.target===b[ti]))out.push({id:out.length,source:a[si],target:b[ti]});}return out;}
function renderSegments(record){currentSegments=(record?.segments?.length?record.segments:fallbackSegments(record?.sourceText||'',record?.translatedText||'')).filter(x=>String(x?.target||'').trim());sentenceIndex=pendingSentenceIndex===null?0:Math.min(Math.max(0,pendingSentenceIndex),Math.max(0,currentSegments.length-1));pendingSentenceIndex=null;currentSentenceOffset=pendingSentenceOffset||0;pendingSentenceOffset=0;const host=$('translation');host.innerHTML='';currentSegments.forEach((seg,i)=>{const span=document.createElement('span');span.className='sentence';span.dataset.index=i;span.dataset.segmentId=String(seg.id??i);span.textContent=String(seg.target).trim()+' ';span.addEventListener('click',()=>{stopSpeech();sentenceIndex=i;currentSentenceOffset=0;currentHighlightProgress=0;startSpeech();});host.appendChild(span);});refreshSourceRanges();updateHighlights();}
function updateHighlights(){document.querySelectorAll('.sentence').forEach((el,i)=>{el.classList.toggle('active',i===sentenceIndex&&speaking);el.classList.toggle('done',i<sentenceIndex);});const active=document.querySelector('.sentence.active');if(active){const pane=$('translation'),r=active.getBoundingClientRect(),pr=pane.getBoundingClientRect();if(r.top<pr.top+36||r.bottom>pr.bottom-72)active.scrollIntoView({behavior:'auto',block:'center'});}const pct=currentSegments.length?Math.min(100,(sentenceIndex/currentSegments.length)*100):0;$('progressBar').style.width=pct+'%';$('progressText').textContent=currentSegments.length?`Trecho ${Math.min(sentenceIndex+1,currentSegments.length)} de ${currentSegments.length} • página ${page}`:`Página ${page}`;updatePdfHighlight();}

function normArtifact(line){return String(line||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\d+/g,'#').replace(/[^a-z#]+/g,' ').replace(/\s+/g,' ').trim();}
async function contentForPage(n){if(pdfContentCache.has(n))return pdfContentCache.get(n);const pg=await pdf.getPage(n),content=await pg.getTextContent();pdfContentCache.set(n,content);return content;}
function linesFromContent(content){const lines=[];let line='',lastY=null;for(const item of content.items){const y=item.transform?.[5];if(lastY!==null&&Math.abs(y-lastY)>6){if(line.trim())lines.push(line.replace(/\s+/g,' ').trim());line='';}line+=(line?' ':'')+item.str;lastY=y;}if(line.trim())lines.push(line.replace(/\s+/g,' ').trim());return lines;}
function cleanLines(lines){return lines.filter(line=>{const key=normArtifact(line);if(bookAnalysis.ready&&bookAnalysis.repeated.has(key))return false;if(/^(?:page|página)?\s*\d+(?:\s*(?:of|de)\s*\d+)?$/i.test(line))return false;if(/^(?:https?:\/\/|www\.|file:\/\/)/i.test(line))return false;if(/(?:https?:\/\/|www\.|file:\/\/)/i.test(line)&&line.length<180)return false;if(/^\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}(?:[, ]+\d{1,2}:\d{2})?$/i.test(line))return false;if(/^[-–—•|_\s\d]+$/.test(line)&&line.length<20)return false;return true;});}
function linesToText(lines){let out='';for(const raw of lines){const line=String(raw||'').replace(/[\uFFFD\uFFFE\uFEFF\u00AD]/g,'').trim();if(!line)continue;const bullet=/^[•▪◦\-*]\s+/.test(line),heading=isNativeBook()&&isStructuralHeading(line);if(!out)out=line;else out+=(heading||bullet?'\n':' ')+line;}return out.replace(/([A-Za-zÀ-ÿ])-\s+(?=[A-Za-zÀ-ÿ])/g,'$1').replace(/[ \t]+/g,' ').replace(/ *\n */g,'\n').replace(/\s+([,.!?;:])/g,'$1').trim();}
async function extractPageText(n){if(pageTextCache.has(n))return pageTextCache.get(n);const content=await contentForPage(n),text=linesToText(cleanLines(linesFromContent(content)));pageTextCache.set(n,text);return text;}
async function analyzeDocumentBackground(){if(!pdf||analysisRunning||bookAnalysis.ready)return;analysisRunning=true;try{const saved=await dbGet(`analysis:${documentKey()}`);if(saved?.repeated){bookAnalysis={ready:true,repeated:new Set(saved.repeated),chapters:saved.chapters||[]};return;}const sampleCount=Math.min(pdf.numPages,28),counts=new Map(),chapters=[...(knownBookProfile?.chapters||[])];for(let n=1;n<=sampleCount;n++){const lines=linesFromContent(await contentForPage(n));for(const line of lines){const k=normArtifact(line);if(k&&line.length<120)counts.set(k,(counts.get(k)||0)+1);if(/^(chapter|part|preface|introduction|capítulo|parte)\b/i.test(line)&&line.length<140)chapters.push({page:n,title:line});}await new Promise(r=>setTimeout(r,0));}const repeated=[...counts.entries()].filter(([,c])=>c>=3).map(([k])=>k);bookAnalysis={ready:true,repeated:new Set(repeated),chapters};dbPut(`analysis:${documentKey()}`,{repeated,chapters,savedAt:Date.now()});}catch(e){console.warn('book_analysis_failed',e);}finally{analysisRunning=false;}}

async function fetchTranslation(original,context,mode,timeoutMs){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(BASE+'/api/translate',{method:'POST',headers:{'Content-Type':'application/json'},signal:c.signal,body:JSON.stringify({text:original,context,source:'en',target:'pt',mode,docId:knownBookId})});const d=await r.json();if(!r.ok)throw new Error(d.detail||d.error||'Falha na tradução');return d;}finally{clearTimeout(timer);}}
async function translatePage(n,{foreground=true}={}){if(translationCache.has(n))return translationCache.get(n);if(translationPending.has(n))return translationPending.get(n);const job=(async()=>{const cacheVersion=isNativeBook()?'native-v4-segmented-headingfix':'v9-source-punctuation-fidelity';const key=`translation:${cacheVersion}:${documentKey()}:${n}`,saved=await dbGet(key);if(saved?.translatedText){translationCache.set(n,saved);return saved;}const original=await extractPageText(n);if(!original){const empty={sourceText:'',translatedText:'',segments:[]};translationCache.set(n,empty);return empty;}if(isNativeBook()){const record=nativeRecordFromText(original);translationCache.set(n,record);dbPut(key,record);return record;}let context='';if(n>1){try{context=(await extractPageText(n-1)).slice(-2800);}catch{}}let data;try{data=await fetchTranslation(original,context,'structured',foreground?14000:26000);}catch(err){if(foreground)setStatus(`Página ${n}: usando tradução rápida...`);data=await fetchTranslation(original,context,'literal',22000);}const translated=String(data.translatedText||'').replace(/\*\*/g,'').replace(/^#{1,6}\s*/gm,'').replace(/`/g,'').trim();const record={sourceText:original,translatedText:translated,segments:Array.isArray(data.segments)&&data.segments.length?data.segments:fallbackSegments(original,translated),engine:data.engine||'unknown',savedAt:Date.now()};translationCache.set(n,record);dbPut(key,record);return record;})();translationPending.set(n,job);try{return await job;}finally{translationPending.delete(n);}}
function requiredAudioAhead(){return Math.min(3,Math.max(0,currentSegments.length-1-sentenceIndex));}
function voiceNeedsPriority(){if(!speaking||$('voice').value==='system:browser')return false;return audioFillRunning||audioAheadCount()<requiredAudioAhead();}
async function waitBackground(generation){while(generation===preloadGeneration&&voiceNeedsPriority())await new Promise(r=>setTimeout(r,320));}
async function warmNextPages(fromPage,count=(knownBookProfile?.prefetchPages||10)){const generation=++preloadGeneration,targets=[];for(let n=fromPage+1;n<=Math.min(pdf.numPages,fromPage+count);n++)if(!translationCache.has(n))targets.push(n);if(!targets.length){if(!speaking)setBuffer(`pr\u00f3ximas ${Math.min(count,pdf.numPages-fromPage)} prontas`,true);return;}let ready=0;if(!speaking)setBuffer(`buffer 0/${targets.length} p\u00e1ginas`);for(const n of targets){if(generation!==preloadGeneration)return;try{await translatePage(n,{foreground:false});ready++;}catch(e){console.warn('prefetch_failed',n,e);}if(!speaking)setBuffer(`buffer ${ready}/${targets.length} p\u00e1ginas`,ready===targets.length);await new Promise(r=>setTimeout(r,speaking?220:90));}}

function normalizePdfToken(text){return String(text||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9'’]+/g,'').replace(/’/g,"'");}
function tokenSpans(text){const out=[],raw=String(text||''),re=/[A-Za-z0-9À-ÿ]+(?:['’][A-Za-z0-9À-ÿ]+)?/g;let m;while((m=re.exec(raw))){const token=normalizePdfToken(m[0]);if(token)out.push({token,start:m.index,end:m.index+m[0].length});}return out;}
function normTokens(text){return tokenSpans(text).map(x=>x.token);}
function buildSourceItemRanges(segments,items){const flat=[];items.forEach((it,itemIndex)=>tokenSpans(it.str).forEach(t=>flat.push({...t,itemIndex})));const ranges=[];let cursor=0;for(const seg of segments){const wanted=normTokens(seg.source);if(!wanted.length){ranges.push([]);continue;}let best=-1;for(let i=cursor;i<flat.length;i++){if(flat[i].token!==wanted[0])continue;let ok=0,j=i;while(j<flat.length&&ok<wanted.length){if(flat[j].token===wanted[ok])ok++;j++;}if(ok>=Math.min(wanted.length,Math.max(3,Math.floor(wanted.length*.78)))){best=i;break;}}if(best<0){ranges.push([]);continue;}let j=best,ok=0,last=best,matched=[];while(j<flat.length&&ok<wanted.length){if(flat[j].token===wanted[ok]){matched.push(flat[j]);ok++;last=j;}j++;}ranges.push(matched);cursor=last+1;}return ranges;}
function refreshSourceRanges(){const content=pdfContentCache.get(page);sourceRanges=content?buildSourceItemRanges(currentSegments,content.items):[];updatePdfHighlight();}
function tokenGeometry(ref){const base=pdfTextGeometry[ref.itemIndex],content=pdfContentCache.get(page),item=content?.items?.[ref.itemIndex];if(!base||!item)return null;const raw=String(item.str||''),len=Math.max(1,raw.length),a=Math.max(0,Math.min(1,ref.start/len)),b=Math.max(a,Math.min(1,ref.end/len));return{x:base.x+base.w*a,y:base.y,w:Math.max(2,base.w*(b-a)),h:base.h};}
function updatePdfHighlight(){const layer=$('pdfHighlightLayer');if(!layer)return;layer.innerHTML='';if(!speaking||sentenceIndex<0)return;const allRefs=sourceRanges[sentenceIndex]||[];const progress=Math.max(0,Math.min(.985,currentHighlightProgress||0));const consumed=Math.min(Math.max(0,allRefs.length-1),Math.floor(allRefs.length*progress));const refs=allRefs.slice(consumed),boxes=refs.map(tokenGeometry).filter(Boolean);if(!boxes.length)return;const lines=[];for(const b of boxes){let line=lines.find(x=>Math.abs(x.y-b.y)<Math.max(3,Math.min(x.h,b.h)*.58));if(!line){line={x:b.x,y:b.y,w:b.w,h:b.h,right:b.x+b.w};lines.push(line);}else{line.x=Math.min(line.x,b.x);line.y=Math.min(line.y,b.y);line.right=Math.max(line.right,b.x+b.w);line.h=Math.max(line.h,b.h);line.w=line.right-line.x;}}for(const b of lines){const el=document.createElement('div');el.className='pdfSourceMark';Object.assign(el.style,{left:`${b.x-1}px`,top:`${b.y-1}px`,width:`${b.w+2}px`,height:`${b.h+3}px`});layer.appendChild(el);}const pane=document.querySelector('.pdfPane'),wrap=document.querySelector('.pdfWrap'),top=wrap.offsetTop+Math.min(...lines.map(x=>x.y)),bottom=wrap.offsetTop+Math.max(...lines.map(x=>x.y+x.h));if(top<pane.scrollTop+55||bottom>pane.scrollTop+pane.clientHeight-55)pane.scrollTop=Math.max(0,top-pane.clientHeight*.28);}

async function renderPdfPage(n){const token=++renderToken;$('pdfLoading').classList.add('show');const pg=await pdf.getPage(n),content=await contentForPage(n),v0=pg.getViewport({scale:1}),pane=document.querySelector('.pdfPane'),mobile=matchMedia('(max-width:900px)').matches,maxW=mobile?Math.max(280,(pane?.clientWidth||390)-12):Math.max(420,(pane?.clientWidth||900)-44),scale=Math.min(document.body.classList.contains('pdf-focus')?3.25:2.2,maxW/v0.width),viewport=pg.getViewport({scale}),ratio=Math.min(devicePixelRatio||1,2),fresh=document.createElement('canvas');fresh.width=Math.ceil(viewport.width*ratio);fresh.height=Math.ceil(viewport.height*ratio);fresh.style.width=`${viewport.width}px`;fresh.style.height=`${viewport.height}px`;const ctx=fresh.getContext('2d',{alpha:false});ctx.setTransform(ratio,0,0,ratio,0,0);await pg.render({canvasContext:ctx,viewport}).promise;if(token!==renderToken)return;const wrap=document.querySelector('.pdfWrap'),old=wrap.querySelector('canvas');fresh.id='canvas';if(old)old.replaceWith(fresh);else wrap.appendChild(fresh);let layer=wrap.querySelector('#pdfHighlightLayer');if(!layer){layer=document.createElement('div');layer.id='pdfHighlightLayer';layer.className='pdfHighlightLayer';wrap.appendChild(layer);}layer.style.width=`${viewport.width}px`;layer.style.height=`${viewport.height}px`;pdfTextGeometry=content.items.map(item=>{const tx=pdfjsLib.Util.transform(viewport.transform,item.transform),h=Math.max(5,Math.hypot(tx[2],tx[3]));return{x:tx[4],y:tx[5]-h,w:Math.max(2,(item.width||0)*viewport.scale),h};});if(n===page)refreshSourceRanges();$('pdfLoading').classList.remove('show');}

const voiceGroups={p:'🇧🇷 Português',a:'🇺🇸 Inglês americano',b:'🇬🇧 Inglês britânico',e:'🇪🇸 Espanhol',f:'🇫🇷 Francês',h:'🇮🇳 Hindi',i:'🇮🇹 Italiano',j:'🇯🇵 Japonês',z:'🇨🇳 Mandarim'};
async function populateVoices(){const s=$('voice');s.innerHTML='<option>Carregando vozes...</option>';try{const r=await fetch(BASE+'/api/voices'),d=await r.json();if(!r.ok)throw new Error(d.detail||d.error||'TTS indisponível');const list=Array.isArray(d.voices)?d.voices:[],groups={};for(const v of list){const g=(v.id||'a')[0];(groups[g]??=[]).push(v);}s.innerHTML='';for(const g of ['p','a','b','e','f','h','i','j','z']){if(!groups[g]?.length)continue;const og=document.createElement('optgroup');og.label=voiceGroups[g]||g;for(const v of groups[g]){const o=document.createElement('option');o.value=v.id;o.textContent=`${v.id} — ${v.description||''}`;og.appendChild(o);}s.appendChild(og);}const og=document.createElement('optgroup');og.label='💻 Navegador';const o=document.createElement('option');o.value='system:browser';o.textContent='Voz padrão do Windows/Chrome';og.appendChild(o);s.appendChild(og);const wanted=pendingVoice||localStorage.getItem('reader:lastVoice')||'pm_jarvis';if([...s.options].some(x=>x.value===wanted))s.value=wanted;else if([...s.options].some(x=>x.value==='pm_alex'))s.value='pm_alex';pendingVoice=null;}catch(e){s.innerHTML='<option value="system:browser">Voz do navegador</option>';setStatus(`Voz local indisponível: ${e.message||e}`);}}
function prepareNarrationText(text){return String(text||'').replace(/[•▪◦]/g,'. ').replace(/US\$\s*([\d.,]+)/gi,'$1 dólares').replace(/R\$\s*([\d.,]+)/gi,'$1 reais').replace(/([\d.,]+)\s*%/g,'$1 por cento').replace(/\s*&\s*/g,' e ').replace(/\bn[º°]\s*/gi,'número ').replace(/\bvs\.?(?=\s|$)/gi,'versus').replace(/[—–]+/g,', ').replace(/\s+/g,' ').trim();}
async function getLocalAudio(text,{background=false}={}){const voice=$('voice').value,spoken=prepareNarrationText(text),key=`${knownBookId}|${voice}|${spoken}`,pendingKey=`${key}|${background?'bg':'fg'}`;if(audioCache.has(key))return audioCache.get(key);if(audioPending.has(pendingKey))return audioPending.get(pendingKey);const job=(async()=>{const pk=`audio:${knownBookId||'generic'}:${voice}:${hashText(spoken)}:${spoken.length}`,saved=await dbGet(pk);if(saved instanceof Blob){audioCache.set(key,saved);return saved;}const r=await fetch(BASE+'/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:spoken,voice,speed:1,docId:knownBookId,background})});if(!r.ok){let d={};try{d=await r.json();}catch{}throw new Error(d.detail||d.error||`TTS ${r.status}`);}const blob=await r.blob();audioCache.set(key,blob);dbPut(pk,blob);if(audioCache.size>100)audioCache.delete(audioCache.keys().next().value);return blob;})();audioPending.set(pendingKey,job);try{return await job;}finally{audioPending.delete(pendingKey);}}
async function warmCurrentAudio(record,count=4,startIndex=sentenceIndex){if($('voice').value==='system:browser')return;const all=(record?.segments?.length?record.segments:fallbackSegments(record?.sourceText||'',record?.translatedText||'')).filter(x=>String(x?.target||'').trim()),start=Math.max(0,Math.min(startIndex,Math.max(0,all.length-1))),segs=all.slice(start,start+Math.max(1,count));if(!segs.length)return;let ready=0;if(!speaking)setBuffer(`pr\u00e9-aquecendo Jarvis 0/${segs.length}`);for(const seg of segs){try{await getDecodedAudio(String(seg.target||''));ready++;if(!speaking)setBuffer(`Jarvis pronto ${ready}/${segs.length}`,ready===segs.length);}catch(e){console.warn('warm_audio_failed',e);break;}await new Promise(r=>setTimeout(r,25));}}
function ensureAudioContext(){if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();return audioContext.state==='suspended'?audioContext.resume():Promise.resolve();}
function trimAudioBuffer(buffer){const threshold=.0035,rate=buffer.sampleRate,total=buffer.length;let first=0,last=total-1,found=false;for(let i=0;i<total&&!found;i++)for(let c=0;c<buffer.numberOfChannels;c++)if(Math.abs(buffer.getChannelData(c)[i])>threshold){first=i;found=true;break;}found=false;for(let i=total-1;i>=0&&!found;i--)for(let c=0;c<buffer.numberOfChannels;c++)if(Math.abs(buffer.getChannelData(c)[i])>threshold){last=i;found=true;break;}first=Math.max(0,first-Math.floor(rate*.018));last=Math.min(total-1,last+Math.floor(rate*.045));if(last<=first||last-first>total*.98)return buffer;const out=audioContext.createBuffer(buffer.numberOfChannels,last-first+1,rate);for(let c=0;c<buffer.numberOfChannels;c++)out.copyToChannel(buffer.getChannelData(c).subarray(first,last+1),c);return out;}
async function getDecodedAudio(text,{background=false}={}){const voice=$('voice').value,spoken=prepareNarrationText(text),key=`${knownBookId}|${voice}|${spoken}`,pendingKey=`${key}|${background?'bg':'fg'}`;if(decodedAudioCache.has(key))return decodedAudioCache.get(key);if(decodedAudioPending.has(pendingKey))return decodedAudioPending.get(pendingKey);const job=(async()=>{const blob=await getLocalAudio(spoken,{background});await ensureAudioContext();const bytes=await blob.arrayBuffer(),buffer=trimAudioBuffer(await audioContext.decodeAudioData(bytes.slice(0)));decodedAudioCache.set(key,buffer);if(decodedAudioCache.size>120)decodedAudioCache.delete(decodedAudioCache.keys().next().value);return buffer;})();decodedAudioPending.set(pendingKey,job);try{return await job;}finally{decodedAudioPending.delete(pendingKey);}}
function narrationGap(text){return/[!?]$/.test(text)?.13:/[.…]$/.test(text)?.08:.035;}
function audioAheadCount(){const tail=audioTimeline[audioTimeline.length-1];return tail?Math.max(0,tail.idx-sentenceIndex):0;}
function primeUpcomingCurrent(start,count=2){if(!speaking||paused||$('voice').value==='system:browser')return;for(let i=start;i<Math.min(currentSegments.length,start+count);i++){const text=String(currentSegments[i]?.target||'');if(text)void getDecodedAudio(text).catch(()=>{});}}
async function waitForForegroundBuffer(minAhead=2){while(speaking&&!paused&&audioFillRunning&&audioAheadCount()<Math.min(minAhead,Math.max(1,requiredAudioAhead())))await new Promise(r=>setTimeout(r,70));}
async function warmPageAudio(n,count=10){if(!pdf||n<1||n>pdf.numPages||$('voice').value==='system:browser')return;const key=`${documentKey()}|${$('voice').value}|${n}|${count}|bg`;if(pageAudioWarmPending.has(key))return pageAudioWarmPending.get(key);const job=(async()=>{const record=await translatePage(n,{foreground:false}),segs=(record?.segments?.length?record.segments:fallbackSegments(record?.sourceText||'',record?.translatedText||'')).filter(x=>String(x?.target||'').trim()).slice(0,Math.max(1,count));for(const seg of segs){try{await getDecodedAudio(String(seg.target||''),{background:true});}catch(e){console.warn('warm_page_audio_failed',n,e);break;}await new Promise(r=>setTimeout(r,30));}})();pageAudioWarmPending.set(key,job);try{return await job;}finally{pageAudioWarmPending.delete(key);}}
async function warmAheadAudio(fromPage){if(!pdf||$('voice').value==='system:browser')return;if(fromPage+1<=pdf.numPages)await warmPageAudio(fromPage+1,10);if(fromPage+2<=pdf.numPages)await warmPageAudio(fromPage+2,4);}

function clearScheduledAudio(){audioScheduleGeneration++;audioFillRunning=false;if(highlightRaf){cancelAnimationFrame(highlightRaf);highlightRaf=0;}for(const e of audioTimeline){try{e.source.onended=null;e.source.stop();e.source.disconnect();}catch{}}audioTimeline=[];currentSource=null;currentBuffer=null;}
function scheduleHighlightLoop(generation){if(highlightRaf)cancelAnimationFrame(highlightRaf);const tick=()=>{if(generation!==audioScheduleGeneration||!speaking)return;if(!paused&&audioContext){const now=audioContext.currentTime,active=audioTimeline.find(e=>now>=e.start-.015&&now<e.end-.005);if(active){currentSentenceOffset=Math.max(0,active.offset+(now-active.start)*active.rate);const total=Math.max(.05,active.source?.buffer?.duration||0);currentHighlightProgress=Math.max(0,Math.min(.985,currentSentenceOffset/total));if(active.idx!==sentenceIndex){sentenceIndex=active.idx;currentSentenceOffset=active.offset||0;currentHighlightProgress=Math.max(0,Math.min(.985,currentSentenceOffset/total));updateHighlights();}else if(performance.now()-lastHighlightPaint>85){lastHighlightPaint=performance.now();updatePdfHighlight();}if(performance.now()-lastOffsetPersist>1500){lastOffsetPersist=performance.now();saveProgress();}}const tail=audioTimeline[audioTimeline.length-1];if(tail&&tail.idx-sentenceIndex<=2)fillAudioSchedule(generation);}highlightRaf=requestAnimationFrame(tick);};highlightRaf=requestAnimationFrame(tick);}
async function fillAudioSchedule(generation=audioScheduleGeneration){if(audioFillRunning||generation!==audioScheduleGeneration||!speaking||paused)return;audioFillRunning=true;try{while(generation===audioScheduleGeneration&&speaking&&!paused){const last=audioTimeline[audioTimeline.length-1],nextIdx=last?last.idx+1:sentenceIndex;if(nextIdx>=currentSegments.length)break;if(last&&last.idx-sentenceIndex>=4)break;const text=String(currentSegments[nextIdx]?.target||''),buffer=await getDecodedAudio(text);if(generation!==audioScheduleGeneration||!speaking||paused)return;const rate=Number($('rate').value)||1,offset=!last&&nextIdx===sentenceIndex?Math.min(currentSentenceOffset,Math.max(0,buffer.duration-.05)):0;let startAt=last?last.end+narrationGap(String(currentSegments[last.idx]?.target||'')):audioContext.currentTime+.06;if(startAt<audioContext.currentTime+.02)startAt=audioContext.currentTime+.02;const source=audioContext.createBufferSource();source.buffer=buffer;source.playbackRate.value=rate;source.connect(audioContext.destination);const entry={idx:nextIdx,source,start:startAt,end:startAt+(buffer.duration-offset)/rate,rate,offset};source.onended=()=>{if(generation!==audioScheduleGeneration||!speaking)return;if(nextIdx===currentSegments.length-1){currentSentenceOffset=0;if(page<pdf.numPages)loadPage(page+1,{autoplay:true,seamless:true});else{stopSpeech();$('progressBar').style.width='100%';$('progressText').textContent='Fim do documento';}}else if(!paused)fillAudioSchedule(generation);};source.start(startAt,offset);audioTimeline.push(entry);if(nextIdx===sentenceIndex){currentSource=source;currentBuffer=buffer;}primeUpcomingCurrent(nextIdx+1,2);setBuffer(`voz local • fluxo contínuo ${Math.min(5,audioAheadCount()+1)} trechos`,true);}}catch(e){if(generation===audioScheduleGeneration){setStatus(`Voz local: ${e.message||e}`);stopSpeech();}}finally{if(generation===audioScheduleGeneration)audioFillRunning=false;}}
async function startLocalContinuous(){if(!speaking||paused)return;await ensureAudioContext();const generation=audioScheduleGeneration,text=String(currentSegments[sentenceIndex]?.target||''),key=`${knownBookId}|${$('voice').value}|${prepareNarrationText(text)}`,ready=decodedAudioCache.has(key);setBuffer(ready?'voz local \u2022 buffer antecipado pronto':'preparando fluxo cont\u00ednuo',ready);fillAudioSchedule(generation);scheduleHighlightLoop(generation);}
function speakBrowserSegment(){if(!speaking)return;if(sentenceIndex>=currentSegments.length){if(page<pdf.numPages)return loadPage(page+1,{autoplay:true});return stopSpeech();}const u=new SpeechSynthesisUtterance(prepareNarrationText(currentSegments[sentenceIndex].target));u.lang='pt-BR';u.rate=Number($('rate').value)||1;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>/^pt-BR/i.test(v.lang))||voices.find(v=>/^pt/i.test(v.lang))||voices[0];u.onstart=()=>{currentHighlightProgress=0;updateHighlights();};u.onboundary=e=>{if(!speaking||paused)return;const n=Math.max(1,u.text.length),i=Math.max(0,Number(e.charIndex)||0);currentHighlightProgress=Math.min(.985,i/n);updatePdfHighlight();};u.onend=()=>{if(!speaking)return;sentenceIndex++;currentSentenceOffset=0;currentHighlightProgress=0;saveProgress();updateHighlights();speakBrowserSegment();};u.onerror=e=>{if(!['canceled','interrupted'].includes(e.error)){setStatus(`Voz interrompida: ${e.error}`);stopSpeech();}};speechSynthesis.speak(u);}
function startSpeech(){if(!currentSegments.length)return;speaking=true;paused=false;$('play').textContent='⏸ Pausar';$('play').classList.add('playing');updateHighlights();if($('voice').value==='system:browser')speakBrowserSegment();else startLocalContinuous();}
function stopSpeech(){if(speaking)saveProgress();clearScheduledAudio();speechSynthesis.cancel();speaking=false;paused=false;$('play').textContent='▶ Ouvir';$('play').classList.remove('playing');updateHighlights();}
function toggleSpeech(){if(!speaking){if($('voice').value!=='system:browser')ensureAudioContext();startSpeech();return;}if(!paused){paused=true;saveProgress();if($('voice').value==='system:browser')speechSynthesis.pause();else if(audioContext?.state==='running')audioContext.suspend();$('play').textContent='▶ Continuar';}else{paused=false;$('play').textContent='⏸ Pausar';if($('voice').value==='system:browser')speechSynthesis.resume();else ensureAudioContext().then(()=>{if(!audioTimeline.length)startLocalContinuous();});}}

async function loadSavedAnalysis(){const saved=await dbGet(`analysis:${documentKey()}`);if(saved?.repeated)bookAnalysis={ready:true,repeated:new Set(saved.repeated),chapters:(knownBookProfile?.chapters?.length?knownBookProfile.chapters:(saved.chapters||[]))};}
async function loadPage(n,{autoplay=false,preservePending=false,seamless=false}={}){if(!pdf)return;const token=++pageLoadToken;preloadGeneration++;const seamlessLocal=!!(seamless&&autoplay&&speaking&&!paused&&$('voice').value!=='system:browser');if(seamlessLocal)clearScheduledAudio();else stopSpeech();if(!preservePending){pendingSentenceIndex=null;pendingSentenceOffset=0;currentSentenceOffset=0;}currentSegments=[];sourceRanges=[];pdfTextGeometry=[];currentHighlightProgress=0;page=Math.min(Math.max(1,n),pdf.numPages);$('pageNum').value=page;$('pageTotal').textContent=`/ ${pdf.numPages}`;setStatus(isNativeBook()?`P\u00e1gina ${page}: preparando texto original em portugu\u00eas...`:`P\u00e1gina ${page}: preparando tradu\u00e7\u00e3o em portugu\u00eas...`);setBuffer(seamlessLocal?'transi\u00e7\u00e3o de p\u00e1gina \u2022 usando buffer antecipado':'prioridade: p\u00e1gina atual',seamlessLocal);renderPdfPage(page).catch(e=>{$('pdfLoading').classList.remove('show');console.error('pdf_render_failed',e);});try{const target=page,record=await translatePage(target,{foreground:true});if(token!==pageLoadToken||target!==page)return;renderSegments(record);setStatus(isNativeBook()?`P\u00e1gina ${page} pronta \u2022 livro pr\u00e9-analisado \u2022 texto original PT-BR`:`P\u00e1gina ${page} pronta \u2022 ${knownBookProfile?'livro pr\u00e9-analisado \u2022 ':''}${record.engine?.includes('literal')?'tradu\u00e7\u00e3o r\u00e1pida':'tradu\u00e7\u00e3o editorial contextualizada'}`);const prefetch=knownBookProfile?.prefetchPages||10;setBuffer(seamlessLocal?'pr\u00f3xima p\u00e1gina j\u00e1 estava em buffer':`p\u00e1gina atual pronta \u2022 preparando pr\u00f3ximas ${prefetch}`,true);saveProgress();const warmCount=Math.min(4,Number(knownBookProfile?.warmSentences||4));setTimeout(()=>warmCurrentAudio(record,warmCount,sentenceIndex),50);setTimeout(()=>warmAheadAudio(target),130);setTimeout(()=>analyzeDocumentBackground(),100);setTimeout(()=>warmNextPages(target,prefetch),180);if(autoplay&&record.translatedText&&token===pageLoadToken){if(seamlessLocal){speaking=true;paused=false;$('play').textContent='\u23f8 Pausar';$('play').classList.add('playing');updateHighlights();startLocalContinuous();}else startSpeech();}}catch(e){if(token!==pageLoadToken)return;stopSpeech();currentSegments=[];updateHighlights();$('translation').innerHTML='<div class="empty">N\u00e3o consegui traduzir esta p\u00e1gina.<br><br><button class="btn" id="retryTranslation">Tentar novamente</button></div>';setStatus(`Falha na tradu\u00e7\u00e3o: ${String(e.message||e)}`);setBuffer('tradu\u00e7\u00e3o indispon\u00edvel');$('retryTranslation')?.addEventListener('click',()=>{translationCache.delete(page);loadPage(page);});}}
async function requestWakeLock(){if(!audiobookMode||!('wakeLock'in navigator))return;try{wakeLock=await navigator.wakeLock.request('screen');wakeLock.addEventListener('release',()=>{wakeLock=null;});}catch{}}
function updateAudiobookUi(){$('audiobook').classList.toggle('modeOn',audiobookMode);$('audiobook').textContent=audiobookMode?'🎧 Audiobook ON':'🎧 Audiobook';}
async function toggleAudiobook(){audiobookMode=!audiobookMode;localStorage.setItem('readerpro:audiobook',audiobookMode?'1':'0');updateAudiobookUi();saveProgress();if(audiobookMode){await requestWakeLock();if(currentSegments.length&&!speaking)startSpeech();}else if(wakeLock){try{await wakeLock.release();}catch{}wakeLock=null;}}
function restartLocalAtCurrent(){const wasPaused=paused;clearScheduledAudio();if(!wasPaused){paused=false;startLocalContinuous();}}
function updatePdfFocusUi(){const on=document.body.classList.contains('pdf-focus'),b=$('pdfFocus');if(!b)return;b.classList.toggle('pdfFocusOn',on);b.setAttribute('aria-pressed',on?'true':'false');b.textContent=on?'↙ Voltar':'⛶ PDF';b.title=on?'Voltar para PDF + tradução':'Visualização cheia do PDF';}
async function togglePdfFocus(force){const next=typeof force==='boolean'?force:!document.body.classList.contains('pdf-focus');document.body.classList.toggle('pdf-focus',next);updatePdfFocusUi();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));if(pdf){try{await renderPdfPage(page);updateHighlights();}catch(e){console.warn('pdf_focus_render_failed',e);}}}
function isTypingTarget(el){return !!(el&&(el.isContentEditable||/^(INPUT|SELECT|TEXTAREA)$/.test(el.tagName)));}

$('play').addEventListener('click',toggleSpeech);$('audiobook').addEventListener('click',toggleAudiobook);$('prev').addEventListener('click',()=>loadPage(page-1));$('next').addEventListener('click',()=>loadPage(page+1));$('pageNum').addEventListener('change',()=>loadPage(Number($('pageNum').value)||1));$('pdfFocus')?.addEventListener('click',()=>togglePdfFocus());
$('rate').addEventListener('change',()=>{saveProgress();if(!speaking)return;if($('voice').value==='system:browser'){const wasPaused=paused;speechSynthesis.cancel();if(wasPaused){speaking=false;paused=false;$('play').textContent='▶ Ouvir';$('play').classList.remove('playing');}else setTimeout(()=>speakBrowserSegment(),30);return;}restartLocalAtCurrent();});
$('voice').addEventListener('change',()=>{localStorage.setItem('reader:lastVoice',$('voice').value);saveProgress();if(!speaking)return;const wasPaused=paused;clearScheduledAudio();speechSynthesis.cancel();if(wasPaused){speaking=false;paused=false;$('play').textContent='▶ Ouvir';$('play').classList.remove('playing');updateHighlights();return;}if($('voice').value==='system:browser')speakBrowserSegment();else startLocalContinuous();});
async function openPdfSource(source,meta,profileHint=null){stopSpeech();preloadGeneration++;pageTextCache.clear();pdfContentCache.clear();translationCache.clear();audioTimeline=[];bookAnalysis={ready:false,repeated:new Set(),chapters:[]};knownBookProfile=null;knownBookId='';knownBookSha256='';fileMeta=meta;$('docTitle').textContent=String(meta.name||'Livro').replace(/\.pdf$/i,'');setStatus('Identificando livro e carregando pré-análise...');if(profileHint)activateProfile(profileHint);else if(source instanceof Uint8Array){const profile=await detectKnownBook(source);if(profile)activateProfile(profile);}if(knownBookProfile){$('docTitle').textContent=knownBookProfile.title||$('docTitle').textContent;setStatus(`Acervo reconhecido: ${knownBookProfile.title||'livro pré-analisado'}`);}const task=source instanceof Uint8Array?pdfjsLib.getDocument({data:source}):pdfjsLib.getDocument({url:source,disableRange:false,disableStream:false,disableAutoFetch:false});pdf=await task.promise;page=1;pendingSentenceIndex=null;pendingSentenceOffset=0;restoreProgress();updateAudiobookUi();await loadSavedAnalysis();if(pendingVoice&&[...$('voice').options].some(o=>o.value===pendingVoice)){$('voice').value=pendingVoice;pendingVoice=null;}$('pageTotal').textContent=`/ ${pdf.numPages}`;await loadPage(page,{preservePending:true});if(matchMedia('(max-width:900px)').matches)setMobileView('text');}
async function openPdfBytes(bytes,meta,profileHint=null){return openPdfSource(bytes,meta,profileHint);}
async function openLibraryBook(bookId){const book=libraryBooks.find(b=>b.id===bookId);if(!book||!book.available)return;hideLibrary();setStatus(`Abrindo ${book.title} da biblioteca...`);setBuffer('carregando primeira página');try{await openPdfSource(`${BASE}/api/library/book/${encodeURIComponent(bookId)}`,{name:`${book.title}.pdf`,size:book.size,lastModified:0},book);}catch(e){setStatus(`Falha ao abrir livro: ${e.message||e}`);showLibrary();}}
$('file').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;const bytes=new Uint8Array(await f.arrayBuffer());await openPdfBytes(bytes,{name:f.name,size:f.size,lastModified:f.lastModified});});
window.addEventListener('keydown',e=>{if(e.code==='Space'&&!isTypingTarget(e.target)){e.preventDefault();e.stopPropagation();if(e.repeat)return;if(document.activeElement instanceof HTMLElement&&document.activeElement.tagName==='BUTTON')document.activeElement.blur();toggleSpeech();return;}if(e.code==='Escape'&&document.body.classList.contains('pdf-focus')){e.preventDefault();togglePdfFocus(false);return;}if(e.code==='ArrowRight'&&e.altKey){e.preventDefault();loadPage(page+1);}if(e.code==='ArrowLeft'&&e.altKey){e.preventDefault();loadPage(page-1);}},true);
window.addEventListener('keyup',e=>{if(e.code==='Space'&&!isTypingTarget(e.target)){e.preventDefault();e.stopPropagation();}},true);
let resizeTimer=null;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(pdf)renderPdfPage(page).catch(()=>{});},180);});window.addEventListener('beforeunload',saveProgress);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&audiobookMode)requestWakeLock();});

function syncMobileSettingsControls(){const mv=$('mobileVoice'),mr=$('mobileRate'),v=$('voice'),r=$('rate');if(mv&&v){mv.innerHTML=v.innerHTML;mv.value=v.value;}if(mr&&r){mr.innerHTML=r.innerHTML;mr.value=r.value;}}
function showMobileSettings(){syncMobileSettingsControls();const el=$('settingsBackdrop');if(el){el.classList.add('show');el.setAttribute('aria-hidden','false');}}
function hideMobileSettings(){const el=$('settingsBackdrop');if(el){el.classList.remove('show');el.setAttribute('aria-hidden','true');}}
function setMobileView(view){document.body.dataset.mobileView=view;for(const id of ['mobilePdf','mobileText'])$(id)?.classList.toggle('active',(view==='pdf'&&id==='mobilePdf')||(view==='text'&&id==='mobileText'));}
function syncMobilePlay(){const b=$('mobilePlay');if(!b)return;const icon=b.querySelector('span');if(icon)icon.textContent=speaking&&!paused?'⏸':'▶';for(const node of [...b.childNodes])if(node.nodeType===Node.TEXT_NODE)node.textContent=speaking&&!paused?'Pausar':(paused?'Continuar':'Ouvir');}
$('mobileImport')?.addEventListener('click',()=>$('file')?.click());$('mobileLibrary')?.addEventListener('click',showLibrary);$('mobilePdf')?.addEventListener('click',()=>setMobileView('pdf'));$('mobileText')?.addEventListener('click',()=>setMobileView('text'));$('mobileSettings')?.addEventListener('click',showMobileSettings);$('settingsClose')?.addEventListener('click',hideMobileSettings);$('settingsBackdrop')?.addEventListener('click',e=>{if(e.target===$('settingsBackdrop'))hideMobileSettings();});$('mobileVoice')?.addEventListener('change',e=>{const v=$('voice');if(v){v.value=e.target.value;v.dispatchEvent(new Event('change',{bubbles:true}));}});$('mobileRate')?.addEventListener('change',e=>{const r=$('rate');if(r){r.value=e.target.value;r.dispatchEvent(new Event('change',{bubbles:true}));}});$('mobilePlay')?.addEventListener('click',()=>{toggleSpeech();setTimeout(syncMobilePlay,40);});
new MutationObserver(syncMobilePlay).observe($('play'),{childList:true,subtree:true,characterData:true});
let deferredInstallPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;});
$('installApp')?.addEventListener('click',async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;return;}$('installHelp')?.classList.toggle('show');});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/reader/sw.js',{scope:'/reader/'}).catch(e=>console.warn('sw_failed',e)));
syncMobilePlay();

$('libraryBtn')?.addEventListener('click',showLibrary);$('libraryClose')?.addEventListener('click',hideLibrary);$('libraryOverlay')?.addEventListener('click',e=>{if(e.target===$('libraryOverlay'))hideLibrary();});updatePdfFocusUi();updateAudiobookUi();populateVoices().then(syncMobileSettingsControls);loadLibrary().then(()=>{if(!pdf)showLibrary();});
