from pathlib import Path
p=Path(r'C:\Users\Adler\agency-ops-hetzner-worktree\vps\reader-ia\app-v2.mjs')
s=p.read_text(encoding='utf-8-sig')
start=s.index('function normTokens(text)')
end=s.index('\nasync function renderPdfPage', start)
new=r'''function normalizePdfToken(text){return String(text||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9'’]+/g,'').replace(/’/g,"'");}
function tokenSpans(text){const out=[],raw=String(text||''),re=/[A-Za-z0-9À-ÿ]+(?:['’][A-Za-z0-9À-ÿ]+)?/g;let m;while((m=re.exec(raw))){const token=normalizePdfToken(m[0]);if(token)out.push({token,start:m.index,end:m.index+m[0].length});}return out;}
function normTokens(text){return tokenSpans(text).map(x=>x.token);}
function buildSourceItemRanges(segments,items){const flat=[];items.forEach((it,itemIndex)=>tokenSpans(it.str).forEach(t=>flat.push({...t,itemIndex})));const ranges=[];let cursor=0;for(const seg of segments){const wanted=normTokens(seg.source);if(!wanted.length){ranges.push([]);continue;}let best=-1;for(let i=cursor;i<flat.length;i++){if(flat[i].token!==wanted[0])continue;let ok=0,j=i;while(j<flat.length&&ok<wanted.length){if(flat[j].token===wanted[ok])ok++;j++;}if(ok>=Math.min(wanted.length,Math.max(3,Math.floor(wanted.length*.78)))){best=i;break;}}if(best<0){ranges.push([]);continue;}let j=best,ok=0,last=best,matched=[];while(j<flat.length&&ok<wanted.length){if(flat[j].token===wanted[ok]){matched.push(flat[j]);ok++;last=j;}j++;}ranges.push(matched);cursor=last+1;}return ranges;}
function refreshSourceRanges(){const content=pdfContentCache.get(page);sourceRanges=content?buildSourceItemRanges(currentSegments,content.items):[];updatePdfHighlight();}
function tokenGeometry(ref){const base=pdfTextGeometry[ref.itemIndex],content=pdfContentCache.get(page),item=content?.items?.[ref.itemIndex];if(!base||!item)return null;const raw=String(item.str||''),len=Math.max(1,raw.length),a=Math.max(0,Math.min(1,ref.start/len)),b=Math.max(a,Math.min(1,ref.end/len));return{x:base.x+base.w*a,y:base.y,w:Math.max(2,base.w*(b-a)),h:base.h};}
function updatePdfHighlight(){const layer=$('pdfHighlightLayer');if(!layer)return;layer.innerHTML='';if(!speaking||sentenceIndex<0)return;const refs=sourceRanges[sentenceIndex]||[],boxes=refs.map(tokenGeometry).filter(Boolean);if(!boxes.length)return;const lines=[];for(const b of boxes){let line=lines.find(x=>Math.abs(x.y-b.y)<Math.max(3,Math.min(x.h,b.h)*.58));if(!line){line={x:b.x,y:b.y,w:b.w,h:b.h,right:b.x+b.w};lines.push(line);}else{line.x=Math.min(line.x,b.x);line.y=Math.min(line.y,b.y);line.right=Math.max(line.right,b.x+b.w);line.h=Math.max(line.h,b.h);line.w=line.right-line.x;}}for(const b of lines){const el=document.createElement('div');el.className='pdfSourceMark';Object.assign(el.style,{left:`${b.x-1}px`,top:`${b.y-1}px`,width:`${b.w+2}px`,height:`${b.h+3}px`});layer.appendChild(el);}const pane=document.querySelector('.pdfPane'),wrap=document.querySelector('.pdfWrap'),top=wrap.offsetTop+Math.min(...lines.map(x=>x.y)),bottom=wrap.offsetTop+Math.max(...lines.map(x=>x.y+x.h));if(top<pane.scrollTop+55||bottom>pane.scrollTop+pane.clientHeight-55)pane.scrollTop=Math.max(0,top-pane.clientHeight*.28);}
'''
p.write_text(s[:start]+new+s[end:],encoding='utf-8-sig')
print('precise token highlight patched')