from pathlib import Path
p=Path(r'C:\Users\Adler\agency-ops-hetzner-worktree\vps\reader-ia\deploy-reader-app2.ps1')
s=p.read_text(encoding='utf-8-sig')
s=s.replace("$appCfg=New-DockerConfig \"reader-ia-app-v2-$stamp\" (Join-Path $dir 'app-v2.mjs')","$appCfg=New-DockerConfig \"reader-ia-app-v2-$stamp\" (Join-Path $dir 'app-v2-fixed.mjs')",1)
anchor="$zikmundCfg=New-DockerConfig \"reader-ia-zikmund-profile-$stamp\" (Join-Path $dir 'zikmund4_profile.json')\n"
extra="$manifestCfg=New-DockerConfig \"reader-ia-manifest-$stamp\" (Join-Path $dir 'manifest.webmanifest')\n$swCfg=New-DockerConfig \"reader-ia-sw-$stamp\" (Join-Path $dir 'sw.js')\n$coverKotlerCfg=New-DockerConfig \"reader-ia-cover-kotler-$stamp\" (Join-Path $dir 'assets\\cover-kotler.jpg')\n$coverZikmundCfg=New-DockerConfig \"reader-ia-cover-zikmund-$stamp\" (Join-Path $dir 'assets\\cover-zikmund.jpg')\n$appleIconCfg=New-DockerConfig \"reader-ia-apple-icon-$stamp\" (Join-Path $dir 'assets\\apple-touch-icon.png')\n$icon192Cfg=New-DockerConfig \"reader-ia-icon192-$stamp\" (Join-Path $dir 'assets\\icon-192.png')\n$icon512Cfg=New-DockerConfig \"reader-ia-icon512-$stamp\" (Join-Path $dir 'assets\\icon-512.png')\n"
if '$manifestCfg=' not in s:s=s.replace(anchor,anchor+extra,1)
needle='@{ConfigID=$zikmundCfg.ID;ConfigName="reader-ia-zikmund-profile-$stamp";File=@{Name=\'/app/zikmund4_profile.json\';UID=\'0\';GID=\'0\';Mode=292}}'
repl=needle+',\n        @{ConfigID=$manifestCfg.ID;ConfigName="reader-ia-manifest-$stamp";File=@{Name=\'/app/manifest.webmanifest\';UID=\'0\';GID=\'0\';Mode=292}},\n        @{ConfigID=$swCfg.ID;ConfigName="reader-ia-sw-$stamp";File=@{Name=\'/app/sw.js\';UID=\'0\';GID=\'0\';Mode=292}},\n        @{ConfigID=$coverKotlerCfg.ID;ConfigName="reader-ia-cover-kotler-$stamp";File=@{Name=\'/app/assets/cover-kotler.jpg\';UID=\'0\';GID=\'0\';Mode=292}},\n        @{ConfigID=$coverZikmundCfg.ID;ConfigName="reader-ia-cover-zikmund-$stamp";File=@{Name=\'/app/assets/cover-zikmund.jpg\';UID=\'0\';GID=\'0\';Mode=292}},\n        @{ConfigID=$appleIconCfg.ID;ConfigName="reader-ia-apple-icon-$stamp";File=@{Name=\'/app/assets/apple-touch-icon.png\';UID=\'0\';GID=\'0\';Mode=292}},\n        @{ConfigID=$icon192Cfg.ID;ConfigName="reader-ia-icon192-$stamp";File=@{Name=\'/app/assets/icon-192.png\';UID=\'0\';GID=\'0\';Mode=292}},\n        @{ConfigID=$icon512Cfg.ID;ConfigName="reader-ia-icon512-$stamp";File=@{Name=\'/app/assets/icon-512.png\';UID=\'0\';GID=\'0\';Mode=292}}'
if '$manifestCfg=' in s and '/app/manifest.webmanifest' not in s:s=s.replace(needle,repl,1)
p.write_text(s,encoding='utf-8-sig')
print('DEPLOY_PWA_PATCHED')