from pathlib import Path
base=Path(r'C:\Users\Adler\agency-ops-hetzner-worktree\vps\reader-ia')
p=base/'app-v2.mjs'; s=p.read_text(encoding='utf-8-sig')
s=s.replace("function voiceNeedsPriority(){if(!speaking||$('voice').value==='system:browser')return false;const tail=audioTimeline[audioTimeline.length-1],ahead=tail?tail.idx-sentenceIndex:0;return audioFillRunning||ahead<3;}","function requiredAudioAhead(){return Math.min(3,Math.max(0,currentSegments.length-1-sentenceIndex));}\nfunction voiceNeedsPriority(){if(!speaking||$('voice').value==='system:browser')return false;return audioFillRunning||audioAheadCount()<requiredAudioAhead();}")
s=s.replace("function audioAheadCount(){const tail=audioTimeline[audioTimeline.length-1];return tail?Math.max(0,tail.idx-sentenceIndex):0;}","function audioAheadCount(){const tail=audioTimeline[audioTimeline.length-1];return tail?Math.max(0,tail.idx-sentenceIndex):0;}\nfunction primeUpcomingCurrent(start,count=2){if(!speaking||paused||$('voice').value==='system:browser')return;for(let i=start;i<Math.min(currentSegments.length,start+count);i++){const text=String(currentSegments[i]?.target||'');if(text)void getDecodedAudio(text).catch(()=>{});}}")
s=s.replace("async function waitForAudioIdle(){while((speaking&&!paused&&(audioFillRunning||audioAheadCount()<3))||(!speaking&&(audioPending.size>0||decodedAudioPending.size>0)))await new Promise(r=>setTimeout(r,120));}","async function waitForAudioIdle(){while((speaking&&!paused&&(audioFillRunning||audioAheadCount()<requiredAudioAhead()))||(!speaking&&(audioPending.size>0||decodedAudioPending.size>0)))await new Promise(r=>setTimeout(r,100));}")
s=s.replace("async function warmAheadAudio(fromPage){if(!pdf||$('voice').value==='system:browser')return;await warmPageAudio(fromPage+1,12);if(fromPage+2<=pdf.numPages)await warmPageAudio(fromPage+2,6);}","async function warmAheadAudio(fromPage){if(!pdf||$('voice').value==='system:browser')return;await warmPageAudio(fromPage+1,6);if(fromPage+2<=pdf.numPages)await warmPageAudio(fromPage+2,3);}")
s=s.replace("if(nextIdx===sentenceIndex){currentSource=source;currentBuffer=buffer;}setBuffer(`voz local • fluxo contínuo ${Math.min(5,audioTimeline.length)} trechos`,true);","if(nextIdx===sentenceIndex){currentSource=source;currentBuffer=buffer;}primeUpcomingCurrent(nextIdx+1,2);setBuffer(`voz local • fluxo contínuo ${Math.min(5,audioAheadCount()+1)} trechos`,true);")
s=s.replace("maxW=Math.max(420,(pane?.clientWidth||900)-44),scale=", "mobile=matchMedia('(max-width:900px)').matches,maxW=mobile?Math.max(280,(pane?.clientWidth||390)-12):Math.max(420,(pane?.clientWidth||900)-44),scale=")
marker="function setMobileView(view){document.body.dataset.mobileView=view;for(const id of ['mobilePdf','mobileText'])$(id)?.classList.toggle('active',(view==='pdf'&&id==='mobilePdf')||(view==='text'&&id==='mobileText'));}"
helpers="function syncMobileSettingsControls(){const mv=$('mobileVoice'),mr=$('mobileRate'),v=$('voice'),r=$('rate');if(mv&&v){mv.innerHTML=v.innerHTML;mv.value=v.value;}if(mr&&r){mr.innerHTML=r.innerHTML;mr.value=r.value;}}\nfunction showMobileSettings(){syncMobileSettingsControls();const el=$('settingsBackdrop');if(el){el.classList.add('show');el.setAttribute('aria-hidden','false');}}\nfunction hideMobileSettings(){const el=$('settingsBackdrop');if(el){el.classList.remove('show');el.setAttribute('aria-hidden','true');}}\n"
if helpers.splitlines()[0] not in s:s=s.replace(marker,helpers+marker,1)
old="$('mobileLibrary')?.addEventListener('click',showLibrary);$('mobilePdf')?.addEventListener('click',()=>setMobileView('pdf'));$('mobileText')?.addEventListener('click',()=>setMobileView('text'));$('mobilePlay')?.addEventListener('click',()=>{toggleSpeech();setTimeout(syncMobilePlay,40);});"
new="$('mobileImport')?.addEventListener('click',()=>$('file')?.click());$('mobileLibrary')?.addEventListener('click',showLibrary);$('mobilePdf')?.addEventListener('click',()=>setMobileView('pdf'));$('mobileText')?.addEventListener('click',()=>setMobileView('text'));$('mobileSettings')?.addEventListener('click',showMobileSettings);$('settingsClose')?.addEventListener('click',hideMobileSettings);$('settingsBackdrop')?.addEventListener('click',e=>{if(e.target===$('settingsBackdrop'))hideMobileSettings();});$('mobileVoice')?.addEventListener('change',e=>{const v=$('voice');if(v){v.value=e.target.value;v.dispatchEvent(new Event('change',{bubbles:true}));}});$('mobileRate')?.addEventListener('change',e=>{const r=$('rate');if(r){r.value=e.target.value;r.dispatchEvent(new Event('change',{bubbles:true}));}});$('mobilePlay')?.addEventListener('click',()=>{toggleSpeech();setTimeout(syncMobilePlay,40);});"
if old not in s: raise SystemExit('mobile events marker missing')
s=s.replace(old,new,1).replace("populateVoices();loadLibrary()","populateVoices().then(syncMobileSettingsControls);loadLibrary()",1)
p.write_text(s,encoding='utf-8')
print('frontend_patch_ok')