from pathlib import Path
import re
base=Path(r'C:\Users\Adler\agency-ops-hetzner-worktree\vps\reader-ia')
index=base/'index.html'; app=base/'app-v2.mjs'
h=index.read_text(encoding='utf-8-sig')
css='.libraryOverlay{position:fixed;inset:0;z-index:50;background:#05070bdd;backdrop-filter:blur(18px);display:none;padding:42px;overflow:auto}.libraryOverlay.show{display:block}.libraryShell{max-width:1080px;margin:0 auto}.libraryHead{display:flex;align-items:flex-start;gap:16px;margin-bottom:26px}.libraryHead h1{margin:0;font-size:32px}.libraryHead p{margin:7px 0 0;color:var(--muted)}.libraryGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:18px}.bookCard{border:1px solid var(--line);background:linear-gradient(145deg,#121724,#0d111a);border-radius:22px;padding:18px;display:grid;grid-template-columns:110px 1fr;gap:18px;box-shadow:0 22px 70px #0005}.bookCover{height:158px;border-radius:14px;padding:14px;background:linear-gradient(155deg,#7c3aed,#172554 55%,#083344);display:flex;flex-direction:column;justify-content:space-between;font-size:11px;letter-spacing:.08em;text-transform:uppercase;font-weight:800}.bookCover b{font-size:20px;letter-spacing:-.03em;text-transform:none}.bookTitle{font-size:18px;font-weight:850}.bookAuthors{font-size:12px;color:var(--muted);margin-top:5px;line-height:1.45}.bookDesc{font-size:13px;color:#c5ccda;line-height:1.45;margin:12px 0}.bookProgress{height:5px;background:#222936;border-radius:99px;overflow:hidden;margin:9px 0}.bookProgress i{display:block;height:100%;background:linear-gradient(90deg,var(--accent),var(--accent2))}.bookMeta{font-size:11px;color:var(--muted);display:flex;justify-content:space-between}.bookActions{display:flex;gap:8px;margin-top:13px}.libraryClose{margin-left:auto}.libraryEmpty{color:var(--muted);padding:30px;border:1px dashed var(--line);border-radius:18px}@media(max-width:650px){.libraryOverlay{padding:20px}.bookCard{grid-template-columns:82px 1fr}.bookCover{height:128px;padding:10px}}'
if '.libraryOverlay{' not in h:h=h.replace('</style>',css+'\n</style>',1)
if 'id="libraryBtn"' not in h:h=h.replace('<label class="fileBtn">Abrir PDF','<button class="btn" id="libraryBtn">ðŸ“š Biblioteca</button>\n    <label class="fileBtn">Abrir PDF',1)
over='''<div class="libraryOverlay" id="libraryOverlay"><div class="libraryShell"><div class="libraryHead"><div><div class="eyebrow">Acervo ReaderPro</div><h1>Sua Biblioteca</h1><p>Livros prÃ©-analisados, com traduÃ§Ã£o, voz e progresso individual.</p></div><button class="btn libraryClose" id="libraryClose">Fechar âœ•</button></div><div class="libraryGrid" id="libraryGrid"><div class="libraryEmpty">Carregando biblioteca...</div></div></div></div>'''
if 'id="libraryOverlay"' not in h:h=h.replace('<script type="module" src="/reader/app-v2.mjs"></script>',over+'\n<script type="module" src="/reader/app-v2.mjs"></script>',1)
index.write_text(h,encoding='utf-8')
print('INDEX_LIBRARY_PATCHED')
a=app.read_text(encoding='utf-8-sig')
if 'let libraryBooks=[];' not in a:a=a.replace("let knownBookProfile=null,knownBookId='',knownBookSha256='';", "let knownBookProfile=null,knownBookId='',knownBookSha256='';\nlet libraryBooks=[];",1)
lib='''function libraryProgress(book){try{const raw=localStorage.getItem(`readerpro:${book.sha256}:${book.size}`),p=JSON.parse(raw||'{}'),pg=Math.max(1,Math.min(Number(book.pageCount)||1,Number(p.page)||1));return{page:pg,pct:Math.max(0,Math.min(100,pg/Math.max(1,Number(book.pageCount)||1)*100)),has:!!raw};}catch{return{page:1,pct:0,has:false};}}
function renderLibrary(){const grid=$('libraryGrid');if(!grid)return;if(!libraryBooks.length){grid.innerHTML='<div class="libraryEmpty">Nenhum livro disponÃ­vel no acervo.</div>';return;}grid.innerHTML=libraryBooks.map((b,i)=>{const p=libraryProgress(b),author=(b.authors||[]).join(' â€¢ '),short=b.id?.startsWith('kotler')?'KOTLER':'ZIKMUND';return `<article class="bookCard"><div class="bookCover"><span>${b.edition||'ReaderPro'}</span><b>${short}</b><span>${b.pageCount||0} pÃ¡ginas</span></div><div><div class="bookTitle">${b.title||'Livro'}</div><div class="bookAuthors">${author}</div><div class="bookDesc">${b.description||'Livro prÃ©-analisado no ReaderPro.'}</div><div class="bookProgress"><i style="width:${p.pct}%"></i></div><div class="bookMeta"><span>${p.has?`PÃ¡gina ${p.page} de ${b.pageCount}`:'Ainda nÃ£o iniciado'}</span><span>${b.available?'DisponÃ­vel':'IndisponÃ­vel'}</span></div><div class="bookActions"><button class="btn primary" data-book-id="${b.id}" ${b.available?'':'disabled'}>${p.has?'Continuar leitura':'Ler agora'}</button></div></div></article>`;}).join('');grid.querySelectorAll('[data-book-id]').forEach(btn=>btn.addEventListener('click',()=>openLibraryBook(btn.dataset.bookId)));}
function showLibrary(){renderLibrary();$('libraryOverlay')?.classList.add('show');}
function hideLibrary(){$('libraryOverlay')?.classList.remove('show');}
async function loadLibrary(){try{const r=await fetch(BASE+'/api/library'),d=await r.json();libraryBooks=Array.isArray(d.books)?d.books:[];renderLibrary();}catch(e){console.warn('library_load_failed',e);}}
function activateProfile(profile){knownBookProfile=profile||null;knownBookId=String(profile?.id||'');knownBookSha256=String(profile?.sha256||'');activeDocHash=knownBookSha256;activeDocProfile=profile||null;if(Array.isArray(profile?.chapters))bookAnalysis.chapters=profile.chapters;}
'''
if 'function libraryProgress(book)' not in a:a=a.replace('function saveProgress(){',lib+'\nfunction saveProgress(){',1)
app.write_text(a,encoding='utf-8')
print('APP_LIBRARY_STATE_PATCHED')
a=app.read_text(encoding='utf-8')
pat=r"\$\('file'\)\.addEventListener\('change',async e=>\{.*?\}\);\nwindow\.addEventListener\('keydown'"
m=re.search(pat,a,flags=re.S)
if not m:raise SystemExit('file handler region not found')
block='''async function openPdfBytes(bytes,meta,profileHint=null){stopSpeech();preloadGeneration++;pageTextCache.clear();pdfContentCache.clear();translationCache.clear();audioTimeline=[];bookAnalysis={ready:false,repeated:new Set(),chapters:[]};knownBookProfile=null;knownBookId='';knownBookSha256='';fileMeta=meta;$('docTitle').textContent=String(meta.name||'Livro').replace(/\\.pdf$/i,'');setStatus('Identificando livro e carregando prÃ©-anÃ¡lise...');if(profileHint)activateProfile(profileHint);else{const profile=await detectKnownBook(bytes);if(profile)activateProfile(profile);}if(knownBookProfile){$('docTitle').textContent=knownBookProfile.title||$('docTitle').textContent;setStatus(`Acervo reconhecido: ${knownBookProfile.title||'livro prÃ©-analisado'}`);}pdf=await pdfjsLib.getDocument({data:bytes}).promise;page=1;pendingSentenceIndex=null;pendingSentenceOffset=0;restoreProgress();updateAudiobookUi();await loadSavedAnalysis();if(pendingVoice&&[...$('voice').options].some(o=>o.value===pendingVoice)){$('voice').value=pendingVoice;pendingVoice=null;}$('pageTotal').textContent=`/ ${pdf.numPages}`;await loadPage(page,{preservePending:true});}
async function openLibraryBook(bookId){const book=libraryBooks.find(b=>b.id===bookId);if(!book||!book.available)return;hideLibrary();setStatus(`Abrindo ${book.title} da biblioteca...`);setBuffer('carregando livro do acervo');try{const r=await fetch(`${BASE}/api/library/book/${encodeURIComponent(bookId)}`);if(!r.ok)throw new Error(`Biblioteca ${r.status}`);const bytes=new Uint8Array(await r.arrayBuffer());await openPdfBytes(bytes,{name:`${book.title}.pdf`,size:book.size,lastModified:0},book);}catch(e){setStatus(`Falha ao abrir livro: ${e.message||e}`);showLibrary();}}
$('file').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;const bytes=new Uint8Array(await f.arrayBuffer());await openPdfBytes(bytes,{name:f.name,size:f.size,lastModified:f.lastModified});});
window.addEventListener('keydown' '''
a=a[:m.start()]+block+a[m.end():]
if "$('libraryBtn')?.addEventListener" not in a:
    a=a.replace('updateAudiobookUi();populateVoices();',"$('libraryBtn')?.addEventListener('click',showLibrary);$('libraryClose')?.addEventListener('click',hideLibrary);$('libraryOverlay')?.addEventListener('click',e=>{if(e.target===$('libraryOverlay'))hideLibrary();});updateAudiobookUi();populateVoices();loadLibrary().then(()=>{if(!pdf)showLibrary();});",1)
app.write_text(a,encoding='utf-8')
print('APP_LIBRARY_OPEN_PATCHED')
