from playwright.sync_api import sync_playwright
url='https://readerpro.lakassessoriadigital.workers.dev/'
with sync_playwright() as p:
    b=p.chromium.launch(headless=True,executable_path=r'C:\Program Files\Google\Chrome\Application\chrome.exe',args=['--disable-gpu'])
    page=b.new_page(viewport={'width':1600,'height':1000})
    translations=[]; tts=[]
    page.on('request',lambda r: translations.append(r.url) if '/api/translate' in r.url else (tts.append(r.url) if '/api/tts' in r.url else None))
    page.goto(url,wait_until='domcontentloaded',timeout=60000)
    page.wait_for_selector('[data-book-id="greene-48-leis-do-poder-ptbr"]',timeout=30000)
    cards=page.locator('.bookCard').count()
    btn=page.locator('[data-book-id="greene-48-leis-do-poder-ptbr"]')
    print('cards',cards,'button',btn.inner_text())
    btn.click()
    page.wait_for_function("document.getElementById('pageTotal').textContent.includes('158')",timeout=30000)
    page.locator('#pageNum').fill('12'); page.locator('#pageNum').press('Enter')
    page.wait_for_function("document.getElementById('status').textContent.includes('texto original PT-BR')",timeout=30000)
    page.wait_for_selector('.sentence',timeout=15000)
    print('title',page.locator('#docTitle').inner_text())
    print('eyebrow',page.locator('.readerHeader .eyebrow').inner_text())
    print('status',page.locator('#status').inner_text())
    print('sentences',page.locator('.sentence').count())
    print('first',page.locator('.sentence').first.inner_text()[:180])
    print('translate_requests',len(translations))
    page.wait_for_timeout(2500)
    print('tts_warm_requests',len(tts))
    page.locator('#play').click(); page.wait_for_timeout(2200)
    print('play_button',page.locator('#play').inner_text())
    print('purple_marks',page.locator('.pdfSourceMark').count())
    print('active_text',page.locator('.sentence.active').inner_text()[:140] if page.locator('.sentence.active').count() else 'NONE')
    page.locator('#play').click(); page.wait_for_timeout(250)
    print('after_pause',page.locator('#play').inner_text())
    page.screenshot(path=r'C:\Users\Adler\agency-ops-hetzner-worktree\vps\reader-ia\greene-browser-test.png',full_page=True)
    b.close()