"use client";

import { useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { BrandMark, SUPABASE_URL, authenticatedFetch, supabase } from "../shared";
import "./commercial-direction.css";

type Row = Record<string, any>;
type Tab = "overview" | "crm" | "forecast" | "meetings" | "quality" | "campaigns" | "won" | "handoff" | "retention";
const API = `${SUPABASE_URL}/functions/v1/agency-ops-commercial-direction-api`;
const tabs: [Tab,string][] = [
  ["overview","Visão Comercial"],["crm","CRM"],["forecast","Forecast"],["meetings","Reuniões"],
  ["quality","Lead Quality"],["campaigns","Campanhas"],["won","Clientes Ganhos"],["handoff","Comercial → Operação"],["retention","Retenção"],
];
const stageLabel: Record<string,string> = { novo:"Novo",qualificacao:"Qualificação",reuniao:"Reunião",proposta:"Proposta",negociacao:"Negociação",fechado:"Fechado",perdido:"Perdido" };
const handoffLabel: Record<string,string> = { CAMPAIGN_LIVE:"Campanha no ar",ONBOARDING_DONE:"Onboarding concluído",ONBOARDING:"Em onboarding",WAITING_ONBOARDING:"Aguardando onboarding" };

function money(v: unknown) { return Number(v || 0).toLocaleString("pt-BR", { style:"currency", currency:"BRL", maximumFractionDigits:0 }); }
function num(v: unknown) { return Number(v || 0).toLocaleString("pt-BR"); }
function pct(v: unknown) { const x=Number(v); return Number.isFinite(x) ? `${x.toLocaleString("pt-BR",{maximumFractionDigits:1})}%` : "—"; }
function date(v: unknown, withTime=false) { if(!v) return "—"; const d=new Date(String(v)); if(Number.isNaN(d.getTime())) return "—"; return new Intl.DateTimeFormat("pt-BR",{timeZone:"America/Sao_Paulo",day:"2-digit",month:"2-digit",year:"2-digit",...(withTime?{hour:"2-digit",minute:"2-digit"}:{})}).format(d); }
function text(v: unknown, fallback="—") { const s=String(v ?? "").trim(); return s || fallback; }
function tone(stage: string) { const s=String(stage||"").toLowerCase(); return s==="negociacao"||s==="fechado"?"good":s==="proposta"||s==="reuniao"?"warm":s==="perdido"?"bad":"muted"; }

function Kpi({label,value,hint,tone="neutral"}:{label:string;value:string|number;hint?:string;tone?:string}) {
  return <article className={`cd-kpi ${tone}`}><span>{label}</span><b>{value}</b>{hint&&<small>{hint}</small>}</article>;
}
function Empty({children}:{children?:any}) { return <div className="cd-empty">{children}</div>; }
function StagePill({value}:{value:string}) { return <span className={`cd-pill ${tone(value)}`}>{stageLabel[String(value||"").toLowerCase()]||text(value)}</span>; }

export default function CommercialDirectionPage() {
  const [session,setSession]=useState<Session|null>(null);
  const [authReady,setAuthReady]=useState(false);
  const [payload,setPayload]=useState<Row>({});
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  const [tab,setTab]=useState<Tab>("overview");
  const [query,setQuery]=useState("");
  const [owner,setOwner]=useState("ALL");

  useEffect(()=>{ supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthReady(true)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,next)=>{setSession(next);setAuthReady(true)}); return()=>subscription.unsubscribe(); },[]);
  async function load(){ setLoading(true);setError(""); try{ const r=await authenticatedFetch(API,{cache:"no-store"}); const b=await r.json().catch(()=>({})); if(!r.ok) throw new Error(b.detail||b.error||`API ${r.status}`); setPayload(b||{}); }catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar a direção comercial.");}finally{setLoading(false)} }
  useEffect(()=>{ if(!authReady)return; if(!session){window.location.assign("/");return;} load(); },[authReady,session?.access_token]);

  const leads:Row[]=payload.leads||[];
  const owners=useMemo(()=>[...new Set(leads.map(r=>String(r.owner_name||"")).filter(Boolean))], [leads]);
  const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase("pt-BR");return leads.filter(r=>(owner==="ALL"||r.owner_name===owner)&&(!q||`${r.name||""} ${r.company||""} ${r.email||""} ${r.phone||""}`.toLocaleLowerCase("pt-BR").includes(q)));},[leads,query,owner]);
  const summary=payload.summary||{};

  if(!authReady||!session) return <main className="cd-loading">Carregando…</main>;
  return <main className="cd-shell">
    <header className="cd-top"><button onClick={()=>window.location.assign("/")}>← Dashboard</button><div className="cd-brand"><BrandMark/><span><small>Leonardo Imobi</small><b>Direção Comercial</b></span></div><div className="cd-profile"><b>{text(payload.profile?.person,"Direção")}</b><small>{text(payload.profile?.display_role,"Direção Comercial")} · leitura executiva</small></div></header>
    <section className="cd-hero"><div><span>DIREÇÃO COMERCIAL · CRM + MARKETING + OPERAÇÃO</span><h1>Venda com contexto. <em>Sem microgestão.</em></h1><p>Pipeline, reuniões, forecast, campanhas e entrega pós-venda em uma leitura executiva. Não há controles de execução operacional nesta área.</p></div><div className="cd-refresh"><small>Atualizado {date(payload.generated_at,true)}</small><button onClick={load} disabled={loading}>{loading?"Atualizando…":"Atualizar"}</button></div></section>
    <nav className="cd-tabs">{tabs.map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}</nav>
    {error&&<div className="cd-error">{error}</div>}

    {tab==="overview"&&<>
      <section className="cd-kpis"><Kpi label="Leads abertos" value={num(summary.open_leads)} hint={`${num(summary.new_7d)} novos em 7 dias`}/><Kpi label="Oportunidades avançadas" value={num(summary.advanced_opportunities)} hint="reunião, proposta ou negociação" tone="good"/><Kpi label="Reuniões · 7 dias" value={num(summary.meetings_7d)} hint="Donnah comercial"/><Kpi label="Follow-ups vencidos" value={num(summary.overdue_followups)} hint={`${num(summary.stale_leads)} oportunidades paradas`} tone={summary.overdue_followups?"bad":"good"}/><Kpi label="Forecast ponderado" value={money(summary.weighted_forecast_value)} hint="usa estágio + valor informado"/><Kpi label="Clientes em onboarding" value={num(summary.clients_onboarding)} hint="handoff comercial → operação"/></section>
      <section className="cd-grid two"><article className="cd-card"><div className="cd-card-head"><div><span>DECISÕES</span><h2>O que merece atenção</h2></div><b>{num((payload.executive_alerts||[]).length)}</b></div>{(payload.executive_alerts||[]).length?(payload.executive_alerts||[]).slice(0,12).map((a:Row,i:number)=><div className="cd-alert" key={`${a.type}-${a.lead_id||a.client_id||i}`}><i className={a.severity==="HIGH"?"bad":"warm"}/><div><b>{text(a.title)}</b><small>{text(a.detail)}{a.owner?` · ${a.owner}`:""}</small></div></div>):<Empty>Sem exceções executivas relevantes agora.</Empty>}</article>
      <article className="cd-card"><div className="cd-card-head"><div><span>TIME COMERCIAL</span><h2>Performance do funil</h2></div></div>{(payload.performance||[]).map((p:Row)=><div className="cd-owner" key={p.owner_id}><div><b>{p.owner_name}</b><small>{num(p.leads)} leads · {num(p.negotiations)} negociações · {num(p.proposals)} propostas</small></div><div><b>{money(p.weighted_value)}</b><small>forecast · {num(p.overdue_followups)} follow-ups vencidos</small></div></div>)}</article></section>
      <section className="cd-card"><div className="cd-card-head"><div><span>ENTREGA DO VENDIDO</span><h2>Comercial → Operação</h2></div><button onClick={()=>setTab("handoff")}>ver tudo</button></div><div className="cd-handoff-grid">{(payload.handoffs||[]).slice(0,8).map((h:Row)=><article key={h.client_id}><b>{h.display_name}</b><small>{h.commercial_owner||"Origem comercial não vinculada"}</small><span className={`cd-pill ${h.handoff_status==="CAMPAIGN_LIVE"?"good":h.onboarding?.blocked_by?"bad":"warm"}`}>{handoffLabel[h.handoff_status]||h.handoff_status}</span><p>{h.onboarding?.next_action||h.onboarding?.blocked_by||"Acompanhamento executivo"}</p></article>)}</div></section>
    </>}

    {tab==="crm"&&<section className="cd-card"><div className="cd-card-head"><div><span>CRM COMERCIAL</span><h2>Pipeline completo</h2></div><b>{filtered.length}</b></div><div className="cd-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar lead, empresa, e-mail ou telefone…"/><select value={owner} onChange={e=>setOwner(e.target.value)}><option value="ALL">Todos os responsáveis</option>{owners.map(o=><option key={o}>{o}</option>)}</select></div><div className="cd-table"><table><thead><tr><th>Lead</th><th>Responsável</th><th>Etapa</th><th>Tempo</th><th>Última atividade</th><th>Próxima ação</th><th>Valor</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><b>{text(r.company||r.name)}</b><small>{r.company?text(r.name):text(r.source)}</small></td><td>{text(r.owner_name)}</td><td><StagePill value={r.stage}/></td><td>{num(r.stage_age_days)}d</td><td>{r.no_activity?<span className="cd-danger">Sem atividade</span>:<><b>{text(r.last_activity_type)}</b><small>{date(r.last_activity_at,true)}</small></>}</td><td>{r.followup_overdue?<span className="cd-danger">Vencido · {date(r.next_action_at,true)}</span>:<>{text(r.next_action,"Sem próxima ação")}{r.next_action_at&&<small>{date(r.next_action_at,true)}</small>}</>}</td><td>{r.estimated_value?money(r.estimated_value):"não informado"}</td></tr>)}</tbody></table></div></section>}

    {tab==="forecast"&&<><section className="cd-kpis"><Kpi label="Pipeline informado" value={money(summary.informed_pipeline_value)} hint="somente valores preenchidos"/><Kpi label="Forecast ponderado" value={money(summary.weighted_forecast_value)} hint="probabilidade por estágio" tone="good"/><Kpi label="Negócios avançados" value={num(summary.advanced_opportunities)} hint="foco de fechamento"/><Kpi label="Parados" value={num(summary.stale_leads)} hint="sem avanço recente" tone={summary.stale_leads?"bad":"good"}/></section><section className="cd-grid two"><article className="cd-card"><div className="cd-card-head"><div><span>PIPELINE</span><h2>Distribuição por estágio</h2></div></div>{(payload.stage_summary||[]).map((s:Row)=><div className="cd-stage-row" key={s.stage}><StagePill value={s.stage}/><div><b>{num(s.count)} oportunidades</b><small>{money(s.informed_value)} informado · {money(s.weighted_value)} ponderado</small></div></div>)}</article><article className="cd-card"><div className="cd-card-head"><div><span>METAS DO MÊS</span><h2>Closer goals</h2></div></div>{(payload.goals||[]).length?(payload.goals||[]).map((g:Row)=><div className="cd-goal" key={`${g.owner_id}-${g.ano}-${g.mes}`}><b>{g.owner_name}</b><div><span>Clientes <b>{num(g.meta_clientes)}</b></span><span>Mensalidade <b>{money(g.meta_mensalidade)}</b></span><span>Implementação <b>{money(g.meta_implementacao)}</b></span></div></div>):<Empty>Nenhuma meta cadastrada para o mês atual.</Empty>}</article></section></>}

    {tab==="meetings"&&<section className="cd-card"><div className="cd-card-head"><div><span>DONNAH</span><h2>Reuniões comerciais</h2></div><b>{num((payload.meetings||[]).length)}</b></div><div className="cd-meetings">{(payload.meetings||[]).slice(0,80).map((m:Row)=><article key={m.id}><div className="cd-meeting-top"><span><b>{m.owner}</b><small>{date(m.meeting_started_at,true)}</small></span>{m.crm_stage&&<StagePill value={m.crm_stage}/>}</div><h3>{text(m.title)}</h3><p>{text(m.summary,"Resumo ainda não disponível.")}</p><footer><span>{m.crm_lead_name?`Lead: ${m.crm_lead_name}`:m.client_name?`Cliente: ${m.client_name}`:"Lead/cliente ainda não identificado"}</span><span>{Array.isArray(m.participants)?m.participants.join(" · "):""}</span></footer></article>)}</div></section>}

    {tab==="quality"&&<><section className="cd-kpis"><Kpi label="Sem atividade" value={num(summary.no_activity)} hint="CRM sem histórico útil" tone={summary.no_activity?"bad":"good"}/><Kpi label="Follow-up vencido" value={num(summary.overdue_followups)} hint="ação comercial pendente" tone={summary.overdue_followups?"bad":"good"}/><Kpi label="Oportunidades paradas" value={num(summary.stale_leads)} hint="tempo excessivo na etapa"/><Kpi label="Campanhas sem entrega" value={num(summary.campaigns_inactive)} hint="clientes ativos/onboarding"/></section><section className="cd-grid two"><article className="cd-card"><div className="cd-card-head"><div><span>HIGIENE DO CRM</span><h2>O que está escapando</h2></div></div>{[...(payload.lead_quality?.overdue_followups||[]),...(payload.lead_quality?.stale_leads||[])].filter((r:Row,i:number,a:Row[])=>a.findIndex(x=>x.id===r.id)===i).slice(0,30).map((r:Row)=><div className="cd-quality" key={r.id}><div><b>{text(r.company||r.name)}</b><small>{r.owner_name} · {stageLabel[String(r.stage).toLowerCase()]||r.stage}</small></div><span>{r.followup_overdue?"Follow-up vencido":`${num(r.stage_age_days)}d parado`}</span></div>)}</article><article className="cd-card"><div className="cd-card-head"><div><span>CLIENTES</span><h2>Meta × comercial</h2></div></div>{(payload.lead_quality?.client_crosscheck||[]).slice(0,25).map((r:Row)=><div className="cd-quality" key={r.id}><div><b>{text(r.client_name)}</b><small>Semana {date(r.week_start)}–{date(r.week_end)}</small></div><span className={String(r.meta_cross_status).includes("DIVERGENCE")?"cd-danger":""}>{num(r.meta_leads)} Meta · {num(r.commercial_leads)} comercial</span></div>)}</article></section></>}

    {tab==="campaigns"&&<><div className="cd-readonly-note"><b>Visão executiva de campanhas</b><span>Sem segmentação, orçamento, criativo ou qualquer comando de alteração. Aqui a pergunta é: estamos gerando oportunidade comercial suficiente?</span><button onClick={()=>window.location.assign("/campaigns")}>Abrir análise completa</button></div><section className="cd-card"><div className="cd-card-head"><div><span>MARKETING</span><h2>Campanhas por cliente</h2></div><b>{num((payload.campaigns||[]).length)}</b></div><div className="cd-table"><table><thead><tr><th>Cliente</th><th>GT</th><th>Status</th><th>Campanhas</th><th>Investimento</th><th>Leads</th><th>CPL</th><th>CTR</th><th>Atualização</th></tr></thead><tbody>{(payload.campaigns||[]).map((r:Row)=><tr key={r.client_id}><td><b>{r.display_name}</b></td><td>{text(r.gt_owner)}</td><td><span className={`cd-pill ${Number(r.active_campaigns)>0?"good":"bad"}`}>{Number(r.active_campaigns)>0?"Ativa":"Sem ativa"}</span></td><td>{num(r.active_campaigns)} ativas · {num(r.paused_campaigns)} pausadas</td><td>{money(r.spend)}</td><td>{num(r.leads)}</td><td>{r.cost_per_result!=null?money(r.cost_per_result):"—"}</td><td>{r.ctr!=null?pct(r.ctr):"—"}</td><td>{date(r.latest_date)}</td></tr>)}</tbody></table></div></section></>}

    {tab==="won"&&<section className="cd-card"><div className="cd-card-head"><div><span>CLIENTES GANHOS</span><h2>Fechamento → entrega</h2></div><b>{num((payload.won_clients||[]).length)}</b></div>{(payload.won_clients||[]).length?<div className="cd-table"><table><thead><tr><th>Cliente</th><th>Vendedor</th><th>Fechado em</th><th>Mensalidade</th><th>Implementação</th><th>Operação</th></tr></thead><tbody>{(payload.won_clients||[]).map((r:Row)=><tr key={r.id}><td><b>{text(r.company||r.name)}</b></td><td>{r.owner_name}</td><td>{date(r.closed_at,true)}</td><td>{money(r.closed_monthly_value)}</td><td>{money(r.closed_setup_value)}</td><td>{r.client?<span className="cd-pill good">Cliente criado</span>:<span className="cd-pill warm">Aguardando vínculo</span>}</td></tr>)}</tbody></table></div>:<Empty>O CRM real ainda não tem fechamentos marcados como “fechado” nos responsáveis comerciais válidos.</Empty>}</section>}

    {tab==="handoff"&&<section className="cd-card"><div className="cd-card-head"><div><span>COMERCIAL → OPERAÇÃO</span><h2>O que foi vendido está andando?</h2></div><b>{num((payload.handoffs||[]).length)}</b></div><div className="cd-table"><table><thead><tr><th>Cliente</th><th>Comercial</th><th>Entrada</th><th>CS / GT</th><th>Onboarding</th><th>Campanha</th><th>Briefing do closer</th></tr></thead><tbody>{(payload.handoffs||[]).map((h:Row)=><tr key={h.client_id}><td><b>{h.display_name}</b><small>{text(h.service,"Serviço não informado")}</small></td><td>{text(h.commercial_owner,"Não vinculado")}</td><td>{date(h.entrada)}</td><td>{text(h.cs_owner)} / {text(h.gt_owner)}</td><td><span className={`cd-pill ${h.onboarding?.blocked_by?"bad":h.onboarding?.status==="CLOSED"?"good":"warm"}`}>{h.onboarding?.blocked_by?"Bloqueado":text(h.onboarding?.current_stage,h.onboarding?.status||"Aguardando")}</span><small>{text(h.onboarding?.next_action,"")}</small></td><td><span className={`cd-pill ${Number(h.campaign?.active_campaigns)>0?"good":"muted"}`}>{Number(h.campaign?.active_campaigns)>0?"No ar":"Sem ativa"}</span></td><td>{h.briefing?<span className={`cd-pill ${h.briefing.status==="DONE"||h.briefing.processed_at?"good":"warm"}`}>{h.briefing.processed_at?"Processado":text(h.briefing.status)}</span>:"—"}</td></tr>)}</tbody></table></div></section>}

    {tab==="retention"&&<><section className="cd-kpis"><Kpi label="Clientes em alto risco" value={num(summary.clients_high_risk)} hint="saúde consolidada" tone={summary.clients_high_risk?"bad":"good"}/><Kpi label="Churn · 90 dias" value={num(summary.churns_90d)} hint="confirmados"/><Kpi label="Motivos catalogados" value={num((payload.retention?.churn_reasons||[]).length)} hint="padrões de saída"/></section><section className="cd-grid two"><article className="cd-card"><div className="cd-card-head"><div><span>RISCO</span><h2>Clientes que merecem contato executivo</h2></div></div>{(payload.retention?.high_risk_clients||[]).slice(0,30).map((r:Row)=><div className="cd-risk" key={r.client_id}><div><b>{r.display_name}</b><small>{r.gt_owner} · {r.cs_owner}</small></div><p>{text(r.external_recommended_action||r.external_summary||r.sinais_alerta,"Sinal de risco consolidado")}</p></div>)}</article><article className="cd-card"><div className="cd-card-head"><div><span>RETENÇÃO</span><h2>Motivos de churn</h2></div></div>{(payload.retention?.churn_reasons||[]).length?(payload.retention.churn_reasons||[]).map((r:Row)=><div className="cd-reason" key={r.reason}><span>{r.reason}</span><b>{num(r.count)}</b></div>):<Empty>Sem motivos de churn confirmados na base.</Empty>}</article></section></>}

    <footer className="cd-footer"><span>{text(payload.data_quality?.note)}</span><small>{num(payload.data_quality?.real_crm_owners)} responsáveis reais · {num(payload.data_quality?.crm_leads)} leads CRM · {num(payload.data_quality?.commercial_meetings)} reuniões comerciais</small></footer>
  </main>;
}
