"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { SUPABASE_URL, authenticatedFetch, supabase } from "../shared";

type Row=Record<string,any>;
const API=`${SUPABASE_URL}/functions/v1/agency-ops-commercial-direction-api`;
const label:Record<string,string>={OPEN:"Aberta",IN_PROGRESS:"Em andamento",SNOOZED:"Adiada",COMPLETED:"Concluída"};
function fmt(value:unknown){if(!value)return"—";const d=new Date(String(value));return Number.isNaN(d.getTime())?String(value):new Intl.DateTimeFormat("pt-BR",{timeZone:"America/Sao_Paulo",dateStyle:"short",timeStyle:"short"}).format(d)}
export default function LeonardoWorkPage(){
 const[session,setSession]=useState<Session|null>(null),[data,setData]=useState<Row>({}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("OPEN");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,n)=>setSession(n));return()=>subscription.unsubscribe()},[]);
 const load=useCallback(async()=>{if(!session?.access_token)return;setLoading(true);setError("");try{const r=await authenticatedFetch(API,{cache:"no-store"}),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||b.error||`API ${r.status}`);if(String(b?.profile?.person||"")!=="Leonardo Augusto")throw new Error("Área restrita à Direção Comercial.");setData(b)}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar a Central de Trabalho.")}finally{setLoading(false)}},[session?.access_token]);
 useEffect(()=>{if(!session?.access_token)return;load();const t=window.setInterval(load,30000);return()=>clearInterval(t)},[session?.access_token,load]);
 const rows:Row[]=data.my_work||[];
 const visible=useMemo(()=>rows.filter(row=>{const ok=status==="ALL"||(status==="OPEN"?!["COMPLETED"].includes(String(row.status)):String(row.status)===status);const q=query.trim().toLowerCase();return ok&&(!q||`${row.title||""} ${row.client_name||""} ${row.description||""}`.toLowerCase().includes(q))}),[rows,status,query]);
 async function update(item:Row,next:string){try{const r=await authenticatedFetch(API,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"update_work_item",item_id:item.id,status:next,resolution:next==="COMPLETED"?"Concluído por Leonardo Augusto":undefined}),cache:"no-store"});const b=await r.json().catch(()=>({}));if(!r.ok||!b.ok)throw new Error(b.detail||b.error||`API ${r.status}`);await load()}catch(e){setError(e instanceof Error?e.message:"Falha ao atualizar demanda.")}}
 if(!session)return <main className="lw-loading">Carregando…</main>;
 return <main className="lw-root"><style>{styles}</style><header><div><button onClick={()=>window.location.assign("/")}>← Central Comercial</button><span>DIREÇÃO COMERCIAL</span><h1>Central de Trabalho</h1><p>Somente demandas atribuídas diretamente ao Leonardo. A fila operacional dos demais colaboradores não aparece aqui.</p></div><small>{loading?"Sincronizando…":`${rows.length} demandas vinculadas`}</small></header>{error&&<div className="lw-error">{error}</div>}<section className="lw-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente ou demanda"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="OPEN">Pendentes</option><option value="ALL">Todas</option><option value="IN_PROGRESS">Em andamento</option><option value="SNOOZED">Adiadas</option><option value="COMPLETED">Concluídas</option></select><button onClick={load}>Atualizar</button></section><section className="lw-list">{visible.map(item=><article key={item.id}><div className="lw-head"><div><span>{item.client_name||"Demanda interna"}</span><h2>{item.title||"Demanda"}</h2></div><b className={String(item.status).toLowerCase()}>{label[String(item.status)]||item.status}</b></div><p>{item.description||"Sem descrição adicional."}</p><footer><div><small>Prioridade: {item.priority||"normal"}</small><small>{item.due_at?`Prazo: ${fmt(item.due_at)}`:`Atualizado: ${fmt(item.updated_at)}`}</small></div><div>{item.status!=="IN_PROGRESS"&&item.status!=="COMPLETED"&&<button onClick={()=>update(item,"IN_PROGRESS")}>Iniciar</button>}{item.status!=="COMPLETED"&&<button className="ok" onClick={()=>update(item,"COMPLETED")}>Concluir</button>}{item.status==="COMPLETED"&&<button onClick={()=>update(item,"OPEN")}>Reabrir</button>}</div></footer></article>)}{!visible.length&&<div className="lw-empty">Nenhuma demanda atribuída ao Leonardo nesse filtro.</div>}</section></main>
}
const styles=`.lw-root{min-height:100vh;background:#071015;color:#e8f2ef;font-family:Inter,system-ui;padding-bottom:50px}.lw-loading{min-height:100vh;display:grid;place-items:center;background:#071015;color:#c9d8d4}.lw-root>header{padding:24px 28px;border-bottom:1px solid #203237;background:#081317;display:flex;justify-content:space-between;gap:20px;align-items:flex-end}.lw-root header button,.lw-tools button,.lw-list footer button{border:1px solid #2a4940;background:#10231f;color:#cce8df;border-radius:9px;padding:8px 10px;cursor:pointer}.lw-root header span{display:block;color:#62cca0;font-size:9px;font-weight:900;letter-spacing:.12em;margin-top:12px}.lw-root h1{margin:4px 0;font-size:28px}.lw-root header p{margin:0;color:#76918a;font-size:11px}.lw-root header>small{color:#708984}.lw-error{margin:14px 28px;border:1px solid #713f3b;background:#2a1514;color:#f0a097;border-radius:10px;padding:10px}.lw-tools{display:flex;gap:8px;padding:20px 28px 10px}.lw-tools input,.lw-tools select{border:1px solid #2a4145;background:#091519;color:#dce9e5;border-radius:9px;padding:9px 10px}.lw-tools input{min-width:320px}.lw-list{display:grid;gap:10px;padding:0 28px}.lw-list article{border:1px solid #203338;background:#0b171b;border-radius:13px;padding:15px}.lw-head{display:flex;justify-content:space-between;gap:14px}.lw-head span{font-size:8px;color:#62cca0;font-weight:900;text-transform:uppercase}.lw-head h2{font-size:14px;margin:4px 0}.lw-head>b{font-size:8px;height:max-content;border:1px solid #38514b;border-radius:999px;padding:5px 8px;color:#a9c8bf}.lw-head>b.completed{color:#82ddb1;border-color:#31624d}.lw-head>b.in_progress{color:#e4c273;border-color:#66532f}.lw-list article>p{color:#8aa19b;font-size:10px;line-height:1.55;white-space:pre-wrap;max-width:1100px}.lw-list footer{border-top:1px solid #192b2e;padding-top:10px;display:flex;justify-content:space-between;gap:12px}.lw-list footer>div{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.lw-list footer small{font-size:8px;color:#6d8580}.lw-list footer button.ok{background:#164b37;border-color:#2a7a57;color:#bdf0d6}.lw-empty{padding:40px;text-align:center;color:#667f79;border:1px dashed #29403f;border-radius:12px}@media(max-width:720px){.lw-root>header,.lw-list footer{flex-direction:column;align-items:flex-start}.lw-tools{flex-direction:column}.lw-tools input{min-width:0;width:100%}.lw-tools select{width:100%}}`;
