import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import postgres from "npm:postgres@3.4.5";

const GRAPH_API_VERSION="v21.0",JOB_NAME="meta_performance_weekly",TZ="America/Sao_Paulo";
const WINDOWS=[3,7,14,30] as const,BATCH_SIZE=3;
const sql=postgres(Deno.env.get("SUPABASE_DB_URL")!,{prepare:false,max:3});
let cachedSecret:string|null=null;
type Action={action_type:string;value:string};
type Integration={client_id:string;meta_ad_account_id:string};
type QueueRow={id:number;run_id:string;client_id:string;client_name:string;gt_owner:string|null;entrada:string|null;attempts:number};
type CampaignMeta={id:string;name:string|null;status:string|null;objective:string|null};
type Insight={campaign_id?:string;campaign_name?:string;spend?:string;impressions?:string;clicks?:string;reach?:string;frequency?:string;actions?:Action[]};
const out=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
async function secret(){if(cachedSecret)return cachedSecret;const r=await sql`select agency_ops.get_internal_secret('META_CAMPAIGN_SYNC_SECRET') secret`;cachedSecret=r.length?String(r[0].secret||""):null;return cachedSecret;}
const n=(v:unknown)=>{const x=Number(v??0);return Number.isFinite(x)?x:0;};
const div=(a:number,b:number)=>b>0?a/b:null;
function exact(actions:Action[]|undefined,type:string){const r=(actions??[]).find(x=>x.action_type.toLowerCase()===type.toLowerCase());if(!r)return null;const v=Number(r.value);return Number.isFinite(v)?{value:v,source:r.action_type}:null;}
function contains(actions:Action[]|undefined,needle:string){let best:{value:number;source:string}|null=null;for(const r of (actions??[]).filter(x=>x.action_type.toLowerCase().includes(needle.toLowerCase()))){const v=Number(r.value);if(Number.isFinite(v)&&(!best||v>best.value))best={value:v,source:r.action_type};}return best;}
function canonical(name:string|null,actions:Action[]|undefined){const lead=exact(actions,"lead")??exact(actions,"onsite_conversion.lead_grouped")??exact(actions,"offsite_complete_registration_add_meta_leads");const msg=contains(actions,"messaging_conversation_started")??contains(actions,"total_messaging_connection");const byName=/(^|[^a-z])(wpp|whats|whatsapp|mensagem)([^a-z]|$)/i.test((name??"").toLowerCase());const useMsg=byName||(!lead&&!!msg),result=useMsg?msg:lead;return{leads:lead?.value??0,result:result?.value??0,result_type:result?(useMsg?"MENSAGEM":"LEAD"):null,result_source:result?.source??null};}
function localDate(){return new Intl.DateTimeFormat("en-CA",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
function shift(day:string,delta:number){const d=new Date(`${day}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+delta);return d.toISOString().slice(0,10);}
const maxDate=(a:string,b:string)=>a>b?a:b;
function inclusiveDays(from:string,to:string){const a=new Date(`${from}T12:00:00Z`).getTime(),b=new Date(`${to}T12:00:00Z`).getTime();return b<a?0:Math.floor((b-a)/86400000)+1;}
async function graph(url:string,retries=3):Promise<any>{let last="Meta API error";for(let i=0;i<retries;i++){const response=await fetch(url),body=await response.json().catch(()=>null);if(response.ok&&body&&!body.error)return body;last=String(body?.error?.message||`HTTP ${response.status}`).slice(0,500);if(![429,500,502,503,504].includes(response.status)||i===retries-1)break;await new Promise(r=>setTimeout(r,500*Math.pow(2,i)));}throw new Error(last);}
async function paged(url:string){const rows:any[]=[];let next:string|null=url;while(next){const body=await graph(next);rows.push(...(body.data||[]));next=body.paging?.next||null;}return rows;}
async function campaigns(account:string,token:string){const rows=await paged(`https://graph.facebook.com/${GRAPH_API_VERSION}/act_${account}/campaigns?fields=id,name,status,objective&limit=500&access_token=${encodeURIComponent(token)}`);return rows.map((r:any)=>({id:String(r.id),name:r.name??null,status:r.status??null,objective:r.objective??null})) as CampaignMeta[];}
async function accountInsight(account:string,token:string,since:string,until:string){const fields=["spend","impressions","clicks","reach","frequency","actions"].join(","),range=encodeURIComponent(JSON.stringify({since,until}));const rows=await paged(`https://graph.facebook.com/${GRAPH_API_VERSION}/act_${account}/insights?level=account&time_range=${range}&limit=50&fields=${fields}&access_token=${encodeURIComponent(token)}`);return(rows[0]||null) as Insight|null;}
async function campaignInsights(account:string,token:string,since:string,until:string){const fields=["campaign_id","campaign_name","spend","impressions","clicks","reach","frequency","actions"].join(","),range=encodeURIComponent(JSON.stringify({since,until}));return await paged(`https://graph.facebook.com/${GRAPH_API_VERSION}/act_${account}/insights?level=campaign&time_range=${range}&limit=500&fields=${fields}&access_token=${encodeURIComponent(token)}`) as Insight[];}
async function emptySnapshot(q:QueueRow,snapshot:string,end:string,period:number,status:string,accountIds:string[]=[],metadata:Record<string,unknown>={}){const from=shift(end,-(period-1)),effective=q.entrada?maxDate(from,q.entrada):from,available=q.entrada?Math.min(period,inclusiveDays(effective,end)):period,partial=available<period;await sql`insert into agency_ops.meta_performance_snapshots(run_id,client_id,client_name,gt_owner,snapshot_date,period_days,date_from,date_to,requested_period_days,available_period_days,is_partial_period,meta_ad_account_ids,account_count,data_status,metadata) values(${q.run_id}::uuid,${q.client_id}::uuid,${q.client_name},${q.gt_owner},${snapshot}::date,${period},${from}::date,${end}::date,${period},${available},${partial},${sql.json(accountIds)},${accountIds.length},${status},${sql.json({...metadata,effective_date_from:effective,graph_api_version:GRAPH_API_VERSION})}) on conflict(run_id,client_id,period_days) do nothing`;}
async function processClient(q:QueueRow,snapshot:string,end:string,token:string){const integrations=await sql<Integration[]>`select distinct client_id::text,meta_ad_account_id::text from agency_ops.client_integrations where client_id=${q.client_id}::uuid and system='META_BM' and meta_ad_account_id is not null order by meta_ad_account_id`,accountIds=integrations.map(x=>String(x.meta_ad_account_id));if(!accountIds.length){for(const p of WINDOWS)await emptySnapshot(q,snapshot,end,p,"NO_META_ACCOUNT");return{outcome:"NO_META_ACCOUNT"};}
 const maps=new Map<string,Map<string,CampaignMeta>>(),inventoryErrors:string[]=[];for(const account of accountIds){try{const rows=await campaigns(account,token);maps.set(account,new Map(rows.map(r=>[r.id,r])));}catch(e){inventoryErrors.push(`${account}: ${String(e instanceof Error?e.message:e)}`);maps.set(account,new Map());}}
 let fullFailures=0;for(const period of WINDOWS){const requestedFrom=shift(end,-(period-1)),effective=q.entrada?maxDate(requestedFrom,q.entrada):requestedFrom,available=q.entrada?Math.min(period,inclusiveDays(effective,end)):period,partial=available<period;if(available<=0){await emptySnapshot(q,snapshot,end,period,"PARTIAL_PERIOD",accountIds,{reason:"client_entered_after_window_end"});continue;}
  let spend=0,impressions=0,clicks=0,reach=0,leads=0,results=0,successfulAccounts=0;const errors:string[]=[],resultTypes=new Set<string>(),campaignRows:any[]=[];
  for(const account of accountIds){try{const [acc,insights]=await Promise.all([accountInsight(account,token,effective,end),campaignInsights(account,token,effective,end)]);successfulAccounts++;spend+=n(acc?.spend);impressions+=n(acc?.impressions);clicks+=n(acc?.clicks);reach+=n(acc?.reach);const metaMap=maps.get(account)||new Map<string,CampaignMeta>();for(const insight of insights){const id=String(insight.campaign_id||"");if(!id)continue;const meta=metaMap.get(id),metric=canonical(insight.campaign_name??meta?.name??null,insight.actions);leads+=metric.leads;results+=metric.result;if(metric.result_type)resultTypes.add(metric.result_type);const s=n(insight.spend),im=n(insight.impressions),cl=n(insight.clicks),re=n(insight.reach),row={account,id,name:insight.campaign_name??meta?.name??id,status:meta?.status??null,objective:meta?.objective??null,spend:s,impressions:im,clicks:cl,reach:re,ctr:im>0?cl/im*100:null,cpc:div(s,cl),cpm:im>0?s/im*1000:null,frequency:div(im,re),leads:metric.leads,results:metric.result,cpl:div(s,metric.leads),cpr:div(s,metric.result),resultType:metric.result_type,resultSource:metric.result_source};if(s>0||im>0||metric.result>0)campaignRows.push(row);}}catch(e){errors.push(`${account}: ${String(e instanceof Error?e.message:e).slice(0,300)}`);}}
  if(successfulAccounts===0)fullFailures++;const inventory=accountIds.flatMap(id=>[...(maps.get(id)?.values()||[])]),active=inventory.filter(x=>String(x.status||"").toUpperCase()==="ACTIVE").length,paused=inventory.filter(x=>String(x.status||"").toUpperCase()==="PAUSED").length;let dataStatus="OK";if(successfulAccounts===0)dataStatus="API_ERROR";else if(errors.length)dataStatus="API_PARTIAL";else if(spend===0&&impressions===0&&results===0)dataStatus="NO_DELIVERY";else if(partial)dataStatus="PARTIAL_PERIOD";
  const ctr=impressions>0?clicks/impressions*100:null,cpc=div(spend,clicks),cpm=impressions>0?spend/impressions*1000:null,frequency=div(impressions,reach),cpl=div(spend,leads),cpr=div(spend,results),reachMode=accountIds.length===1?"EXACT_ACCOUNT_RANGE":"SUM_EXACT_ACCOUNT_RANGES";
  await sql`insert into agency_ops.meta_performance_snapshots(run_id,client_id,client_name,gt_owner,snapshot_date,period_days,date_from,date_to,requested_period_days,available_period_days,is_partial_period,meta_ad_account_ids,account_count,spend,impressions,reach,clicks,ctr,cpc,cpm,frequency,leads,results,cpl,cost_per_result,campaign_count,active_campaigns,paused_campaigns,data_status,metadata) values(${q.run_id}::uuid,${q.client_id}::uuid,${q.client_name},${q.gt_owner},${snapshot}::date,${period},${requestedFrom}::date,${end}::date,${period},${available},${partial},${sql.json(accountIds)},${accountIds.length},${spend},${Math.round(impressions)},${Math.round(reach)},${Math.round(clicks)},${ctr},${cpc},${cpm},${frequency},${leads},${results},${cpl},${cpr},${inventory.length},${active},${paused},${dataStatus},${sql.json({effective_date_from:effective,graph_api_version:GRAPH_API_VERSION,result_types:[...resultTypes],account_errors:errors,inventory_errors:inventoryErrors,reach_aggregation:reachMode,source:"META_MARKETING_API_DIRECT_RANGE"})}) on conflict(run_id,client_id,period_days) do nothing`;
  for(const r of campaignRows)await sql`insert into agency_ops.meta_campaign_performance_snapshots(run_id,client_id,client_name,gt_owner,snapshot_date,period_days,date_from,date_to,meta_ad_account_id,campaign_id,campaign_name,campaign_status,objective,spend,impressions,reach,clicks,ctr,cpc,cpm,frequency,leads,results,cpl,cost_per_result,result_type,result_source,data_status,metadata) values(${q.run_id}::uuid,${q.client_id}::uuid,${q.client_name},${q.gt_owner},${snapshot}::date,${period},${requestedFrom}::date,${end}::date,${r.account},${r.id},${r.name},${r.status},${r.objective},${r.spend},${Math.round(r.impressions)},${Math.round(r.reach)},${Math.round(r.clicks)},${r.ctr},${r.cpc},${r.cpm},${r.frequency},${r.leads},${r.results},${r.cpl},${r.cpr},${r.resultType},${r.resultSource},'OK',${sql.json({effective_date_from:effective,source:"META_MARKETING_API_DIRECT_RANGE"})}) on conflict(run_id,client_id,period_days,meta_ad_account_id,campaign_id) do nothing`;
 }
 return{outcome:fullFailures===WINDOWS.length?"API_ERROR":"DONE"};}
async function recalc(runId:string){const rows=await sql`select count(*)::int total,count(*) filter(where status='DONE')::int done,count(*) filter(where status='ERROR' and attempts>=3)::int exhausted,count(*) filter(where status in ('PENDING','RUNNING') or(status='ERROR' and attempts<3))::int pending from agency_ops.meta_performance_queue where run_id=${runId}::uuid`,q=rows[0],sr=await sql`select count(distinct client_id) filter(where period_days=7 and data_status='NO_META_ACCOUNT')::int no_meta,count(distinct client_id) filter(where period_days=7 and data_status='NO_DELIVERY')::int no_data,count(distinct client_id) filter(where period_days=7 and data_status='API_ERROR')::int api_error from agency_ops.meta_performance_snapshots where run_id=${runId}::uuid`,s=sr[0]||{no_meta:0,no_data:0,api_error:0},processed=Number(q.done||0)+Number(q.exhausted||0),errors=Number(q.exhausted||0)+Number(s.api_error||0),final=Number(q.pending||0)===0,status=final?(errors>0?"COMPLETED_WITH_ERRORS":"COMPLETED"):"RUNNING";await sql`update agency_ops.meta_performance_runs set status=${status},total_clients=${q.total},processed_clients=${processed},successful_clients=${Number(q.done||0)},error_clients=${errors},no_meta_clients=${Number(s.no_meta||0)},no_data_clients=${Number(s.no_data||0)},finished_at=${final?new Date().toISOString():null},updated_at=now() where id=${runId}::uuid`;return{final,pending:Number(q.pending||0),total:Number(q.total||0),processed,errors,no_meta:Number(s.no_meta||0),no_data:Number(s.no_data||0),status};}
async function notify(runId:string,snapshot:string,stats:any){const desc=`${stats.total} clientes ativos · ${Math.max(0,stats.total-stats.no_meta-stats.errors)} com coleta · ${stats.no_data} sem entrega · ${stats.no_meta} sem integração Meta · ${stats.errors} erro(s).`;await sql`insert into agency_ops.platform_notifications(event_key,type,level,title,description,source,actor,occurred_at,metadata) values(${`meta_performance_weekly:${snapshot}`},'META_PERFORMANCE_WEEKLY',${stats.errors>0?"WARNING":"INFO"},'Relatório Meta semanal concluído',${desc},'meta_performance','Sistema',now(),${sql.json({private_to_person:true,target_person:"Adler Furtado",target_role:"MGMT",meta_performance_run_id:runId,button_label:"Ver relatório",route:`/meta-performance?run=${runId}`})}) on conflict(event_key) do nothing`;}
async function invoke(mode:string){const s=await secret();if(!s)return;const promise=fetch(`${Deno.env.get("SUPABASE_URL")}/functions/v1/agency-ops-meta-performance-weekly`,{method:"POST",headers:{"content-type":"application/json","x-meta-campaign-secret":s},body:JSON.stringify({mode})}).catch(()=>null);const runtime=(globalThis as any).EdgeRuntime;if(runtime?.waitUntil)runtime.waitUntil(promise);else await promise;}
async function logFinal(runId:string,stats:any){const run=await sql`select started_at,finished_at from agency_ops.meta_performance_runs where id=${runId}::uuid`,started=run[0]?.started_at?new Date(run[0].started_at):new Date(),finished=run[0]?.finished_at?new Date(run[0].finished_at):new Date();await sql`insert into agency_ops.job_runs(job_name,started_at,finished_at,status,events_processed,error,duration_ms) values(${JOB_NAME},${started.toISOString()},${finished.toISOString()},${stats.errors>0?"ERROR":"SUCCESS"},${stats.processed},${stats.errors>0?`${stats.errors} cliente(s) com erro`:null},${Math.max(0,finished.getTime()-started.getTime())})`;}
Deno.serve(async req=>{if(req.method==="GET"&&new URL(req.url).searchParams.get("health")==="1")return out({ok:true,service:JOB_NAME,version:2,windows:WINDOWS});const s=await secret().catch(()=>null);if(!s||req.headers.get("x-meta-campaign-secret")!==s)return out({ok:false,error:"unauthorized"},401);const token=Deno.env.get("META_SYSTEM_USER_TOKEN");if(!token)return out({ok:false,error:"META_SYSTEM_USER_TOKEN ausente"},500);const body=await req.json().catch(()=>({})),mode=String(body?.mode||"start").toLowerCase();try{if(mode==="start"){const snapshot=localDate(),end=shift(snapshot,-1),inserted=await sql`insert into agency_ops.meta_performance_runs(snapshot_date,window_end,status,started_at,metadata) values(${snapshot}::date,${end}::date,'RUNNING',now(),${sql.json({windows:WINDOWS,timezone:TZ,source:"META_MARKETING_API_DIRECT_RANGE",immutable:true})}) on conflict(snapshot_date) do nothing returning id::text`;let runId=inserted[0]?.id?String(inserted[0].id):"";if(!runId){const existing=await sql`select id::text,status from agency_ops.meta_performance_runs where snapshot_date=${snapshot}::date limit 1`;runId=String(existing[0]?.id||"");if(["COMPLETED","COMPLETED_WITH_ERRORS"].includes(String(existing[0]?.status)))return out({ok:true,already_completed:true,run_id:runId,snapshot_date:snapshot});await sql`update agency_ops.meta_performance_runs set status='RUNNING',started_at=coalesce(started_at,now()),updated_at=now() where id=${runId}::uuid`;}
 const clients=await sql`select id::text,display_name,gt_owner,entrada from agency_ops.clients where lifecycle='ACTIVE' order by display_name`;for(const c of clients)await sql`insert into agency_ops.meta_performance_queue(run_id,client_id,client_name,gt_owner,entrada,status) values(${runId}::uuid,${String(c.id)}::uuid,${String(c.display_name)},${c.gt_owner??null},${c.entrada??null}::date,'PENDING') on conflict(run_id,client_id) do nothing`;await sql`update agency_ops.meta_performance_queue set status='PENDING',locked_at=null,updated_at=now() where run_id=${runId}::uuid and status='RUNNING' and locked_at<now()-interval '20 minutes'`;await sql`update agency_ops.meta_performance_runs set total_clients=(select count(*) from agency_ops.meta_performance_queue where run_id=${runId}::uuid),updated_at=now() where id=${runId}::uuid`;await invoke(`work:${runId}`);return out({ok:true,run_id:runId,snapshot_date:snapshot,window_end:end,queued:clients.length});}
 if(mode.startsWith("work:")){const runId=mode.slice(5),runs=await sql`select id::text,snapshot_date::text,window_end::text,status from agency_ops.meta_performance_runs where id=${runId}::uuid limit 1`;if(!runs.length)return out({ok:false,error:"run_not_found"},404);if(["COMPLETED","COMPLETED_WITH_ERRORS"].includes(String(runs[0].status)))return out({ok:true,done:true,run_id:runId});await sql`update agency_ops.meta_performance_queue set status='PENDING',locked_at=null,updated_at=now() where run_id=${runId}::uuid and status='RUNNING' and locked_at<now()-interval '20 minutes'`;const claimed=await sql<QueueRow[]>`update agency_ops.meta_performance_queue q set status='RUNNING',attempts=q.attempts+1,locked_at=now(),updated_at=now() where q.id in(select id from agency_ops.meta_performance_queue where run_id=${runId}::uuid and(status='PENDING' or(status='ERROR' and attempts<3)) order by id limit ${BATCH_SIZE} for update skip locked) returning q.id,q.run_id::text,q.client_id::text,q.client_name,q.gt_owner,q.entrada::text,q.attempts`;for(const q of claimed){try{const result=await processClient(q,String(runs[0].snapshot_date),String(runs[0].window_end),token);await sql`update agency_ops.meta_performance_queue set status='DONE',error=${result.outcome==="API_ERROR"?"Meta API indisponível para todas as janelas":null},locked_at=null,updated_at=now() where id=${q.id}`;}catch(e){await sql`update agency_ops.meta_performance_queue set status='ERROR',error=${String(e instanceof Error?e.message:e).slice(0,800)},locked_at=null,updated_at=now() where id=${q.id}`;}}
 const stats=await recalc(runId);if(stats.final){await notify(runId,String(runs[0].snapshot_date),stats);await logFinal(runId,stats).catch(()=>{});}else await invoke(`work:${runId}`);return out({ok:true,run_id:runId,claimed:claimed.length,...stats});}return out({ok:false,error:"invalid_mode"},400);}catch(e){return out({ok:false,error:String(e instanceof Error?e.message:e).slice(0,1000)},500);}});
