import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const CORS={"access-control-allow-origin":"*","access-control-allow-headers":"authorization,apikey,content-type","access-control-allow-methods":"GET,OPTIONS"};
const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});if(req.method!=="GET")return reply({error:"method_not_allowed"},405);
 const supabaseUrl=Deno.env.get("SUPABASE_URL"),serviceRole=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),anonKey=Deno.env.get("SUPABASE_ANON_KEY");if(!supabaseUrl||!serviceRole||!anonKey)return reply({error:"server_configuration"},500);
 const authHeader=req.headers.get("Authorization")??"";if(!authHeader.startsWith("Bearer "))return reply({error:"unauthorized"},401);const authClient=createClient(supabaseUrl,anonKey,{global:{headers:{Authorization:authHeader}},auth:{persistSession:false}}),{data:userData}=await authClient.auth.getUser();if(!userData?.user)return reply({error:"unauthorized"},401);
 const db=createClient(supabaseUrl,serviceRole,{auth:{persistSession:false,autoRefreshToken:false}}),ops=db.schema("agency_ops"),userKey=userData.user.id;
 const {data:pref}=await ops.from("user_preferences").select("collaborator_person").eq("user_key",userKey).maybeSingle();const person=pref?.collaborator_person??null;let role:string|null=null,accessLevel="RESTRICTED";if(person){const {data:roster}=await ops.from("team_roster").select("role,access_level").eq("person",person).eq("is_former",false).maybeSingle();role=roster?.role??null;accessLevel=roster?.access_level??"RESTRICTED";}
 const {data:approvals}=await ops.from("access_requests").select("kind,status").eq("user_key",userKey).eq("status","APPROVED");const accountApproved=(approvals??[]).some((r:any)=>r.kind==="SIGNUP"),elevated=accessLevel==="RESTRICTED"&&(approvals??[]).some((r:any)=>r.kind==="ELEVATION"),isFull=accessLevel==="FULL"||elevated,isWalletOnly=accessLevel==="WALLET_ONLY"&&!elevated;if(!accountApproved||(!person&&!elevated))return reply({error:"forbidden"},403);
 const url=new URL(req.url),lifecycle=(url.searchParams.get("lifecycle")??"ACTIVE").toUpperCase(),includeDetails=url.searchParams.get("details")!=="0";let q=ops.from("campaign_client_latest").select("*");if(lifecycle==="ACTIVE")q=q.in("lifecycle",["ACTIVE","ONBOARDING"]);else if(lifecycle!=="ALL")q=q.eq("lifecycle",lifecycle);if(isWalletOnly&&person)q=q.eq("gt_owner",person);const {data:clients,error}=await q.order("display_name");if(error)return reply({error:"query_failed",detail:error.message},500);const scoped=clients??[],ids=scoped.map((r:any)=>r.client_id);let campaigns:any[]=[];
 if(includeDetails&&ids.length){const [inventoryResult,insightResult]=await Promise.all([ops.from("meta_campaign_inventory").select("client_id,account_key,meta_ad_account_id,campaign_id,campaign_name,campaign_status,objective,checked_at").in("client_id",ids),ops.from("campaign_latest_details").select("client_id,display_name,lifecycle,gt_owner,account_key,meta_ad_account_id,campaign_id,campaign_name,campaign_status,objective,date_start,date_stop,spend,impressions,clicks,ctr,cpc,cpm,reach,frequency,leads_estimate,cost_per_lead_estimate,result_type,result_count,cost_per_result,result_source,checked_at").in("client_id",ids)]);if(inventoryResult.error)return reply({error:"query_failed",detail:inventoryResult.error.message},500);if(insightResult.error)return reply({error:"query_failed",detail:insightResult.error.message},500);const insightMap=new Map((insightResult.data??[]).map((r:any)=>[`${r.client_id}:${r.campaign_id}`,r]));campaigns=(inventoryResult.data??[]).map((inv:any)=>{const ins:any=insightMap.get(`${inv.client_id}:${inv.campaign_id}`);return ins?{...inv,...ins,has_delivery:Number(ins.impressions??0)>0||Number(ins.spend??0)>0}:{...inv,date_start:null,date_stop:null,spend:0,impressions:0,clicks:0,ctr:null,cpc:null,cpm:null,reach:0,frequency:null,leads_estimate:0,cost_per_lead_estimate:null,result_type:null,result_count:0,cost_per_result:null,result_source:null,has_delivery:false};}).sort((a:any,b:any)=>Number(b.has_delivery)-Number(a.has_delivery)||Number(b.spend)-Number(a.spend)||String(a.campaign_name??"").localeCompare(String(b.campaign_name??""),"pt-BR"));}
 const sum=(k:string)=>scoped.reduce((a:number,r:any)=>a+Number(r[k]??0),0),byStatus=scoped.reduce((a:Record<string,number>,r:any)=>{const k=String(r.delivery_status??"UNKNOWN");a[k]=(a[k]??0)+1;return a;},{}),spend=sum("spend"),results=sum("results"),impressions=sum("impressions"),clicks=sum("clicks");return reply({clients:scoped,campaigns,summary:{lifecycle_filter:lifecycle,clients_total:scoped.length,active_delivery:byStatus.ACTIVE_DELIVERY??0,no_meta_account:byStatus.NO_META_ACCOUNT??0,no_delivery:byStatus.NO_DELIVERY??0,no_active_campaign:byStatus.NO_ACTIVE_CAMPAIGN??0,no_campaigns:byStatus.NO_CAMPAIGNS??0,stale:byStatus.STALE??0,churned_with_delivery:byStatus.CHURNED_WITH_DELIVERY??0,spend:Number(spend.toFixed(2)),results,leads:sum("leads"),impressions,clicks,ctr:impressions?Number((clicks/impressions*100).toFixed(2)):null,cost_per_result:results?Number((spend/results).toFixed(2)):null,reference_date:scoped.map((r:any)=>r.latest_date).filter(Boolean).sort().at(-1)??null,checked_at:scoped.map((r:any)=>r.checked_at).filter(Boolean).sort().at(-1)??null},profile:{person,role,access_level:accessLevel,elevated,scope:isFull?"FULL":isWalletOnly?"WALLET":"RESTRICTED"},generated_at:new Date().toISOString()});
});