import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const CORS={"access-control-allow-origin":"*","access-control-allow-headers":"authorization,apikey,content-type,x-dashboard-key","access-control-allow-methods":"GET,POST,OPTIONS"};
const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const day=(date=new Date())=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).format(date);
const norm=(value:unknown)=>String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
function isAiDemand(item:any){
  const metadata=item?.metadata??{};
  if(metadata.ai_workspace===true||metadata.n8n_verified===true||metadata.created_inside_ai_work_center===true||metadata.imported_from_clickup===true||metadata.ai_classified===true)return true;
  const title=norm(`${item?.title??item?.name??""} ${item?.description??""}`);
  const list=norm(item?.list_name??item?.metadata?.clickup_list_name??"");
  const combined=`${title} ${list}`;
  if(/\bagente\b|\bn8n\b|chatbot|bot de atendimento|automacao|webhook|prompt|llm|openai|assistente virtual|fluxo de atendimento|integracao.*whatsapp|whatsapp.*integracao/.test(combined))return true;
  return /\bia\b.{0,80}(lead|atendimento|agente|fluxo|whatsapp|automacao|integracao|prompt|resposta|conversa)|(?:lead|atendimento|agente|fluxo|whatsapp|automacao|integracao|prompt|resposta|conversa).{0,80}\bia\b/.test(combined);
}

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});
  if(!["GET","POST"].includes(req.method))return reply({error:"method_not_allowed"},405);
  const supabaseUrl=Deno.env.get("SUPABASE_URL")!,anonKey=Deno.env.get("SUPABASE_ANON_KEY")!,serviceRole=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  if(!supabaseUrl||!anonKey||!serviceRole)return reply({error:"server_configuration"},500);
  const auth=req.headers.get("Authorization")??"";if(!auth.startsWith("Bearer "))return reply({error:"unauthorized"},401);
  const token=auth.replace(/^Bearer\s+/i,"").trim();const db=createClient(supabaseUrl,serviceRole,{auth:{persistSession:false,autoRefreshToken:false}});const ops=db.schema("agency_ops");
  const{data:userData,error:userError}=await db.auth.getUser(token);if(userError||!userData.user)return reply({error:"unauthorized"},401);
  const[{data:pref},{data:signup}]=await Promise.all([ops.from("user_preferences").select("collaborator_person").eq("user_key",userData.user.id).maybeSingle(),ops.from("access_requests").select("id").eq("user_key",userData.user.id).eq("kind","SIGNUP").eq("status","APPROVED").limit(1)]);
  const person=String(pref?.collaborator_person??"");const bodyText=req.method==="POST"?await req.text():"";const incoming=new URL(req.url);const view=incoming.searchParams.get("view")??"home";const coreUrl=new URL(`${supabaseUrl}/functions/v1/agency-ops-dashboard-api`);coreUrl.search=incoming.search;
  const core=()=>fetch(coreUrl,{method:req.method,headers:{Authorization:auth,apikey:anonKey,...(bodyText?{"content-type":req.headers.get("content-type")||"application/json"}:{})},body:req.method==="POST"?bodyText:undefined});
  if(person!=="Gabriel Castro"){const response=await core();return new Response(response.body,{status:response.status,headers:{...CORS,"content-type":response.headers.get("content-type")||"application/json","cache-control":"no-store"}});}
  if(!(signup??[]).length)return reply({error:"forbidden"},403);
  const{data:roster}=await ops.from("team_roster").select("person,role,access_level,clickup_user,is_former").eq("person","Gabriel Castro").maybeSingle();if(!roster||roster.is_former||roster.role!=="AI")return reply({error:"forbidden"},403);
  const{data:aiRows,error:aiError}=await ops.rpc("ai_ours_active_client_ids");if(aiError)return reply({error:"ai_scope_failed",detail:aiError.message},500);const aiIds=new Set((aiRows??[]).map((r:any)=>String(r.client_id)).filter(Boolean));const allowedClient=(id:unknown)=>Boolean(id)&&aiIds.has(String(id));

  if(view==="clickup-range"&&req.method==="GET"){const since=/^\d{4}-\d{2}-\d{2}$/.test(incoming.searchParams.get("since")||"")?incoming.searchParams.get("since")!:day(new Date(Date.now()-29*86400000));const until=/^\d{4}-\d{2}-\d{2}$/.test(incoming.searchParams.get("until")||"")?incoming.searchParams.get("until")!:day();const{data,error}=await ops.rpc("clickup_range_report_ai_clients",{p_since:since,p_until:until,p_person:roster.clickup_user||"Gabriel Castro"});if(error)return reply({error:"clickup_scope_failed",detail:error.message},500);return reply({...data,scoped:true,scope_model:"AI_N8N_CLIENTS",generated_at:new Date().toISOString()});}
  const allowedGet=new Set(["home","work","client"]),allowedPost=new Set(["notifications-read","preferences","work-item-update","note-create","note-confirm"]);if(req.method==="GET"&&!allowedGet.has(view))return reply({error:"forbidden"},403);if(req.method==="POST"&&!allowedPost.has(view))return reply({error:"forbidden"},403);if(view==="client"&&!allowedClient(incoming.searchParams.get("id")))return reply({error:"not_found_or_forbidden"},404);
  let posted:any={};if(req.method==="POST"&&bodyText){try{posted=JSON.parse(bodyText);}catch{return reply({error:"invalid_json"},400);}if(posted?.client_id&&!allowedClient(posted.client_id))return reply({error:"forbidden_client_scope"},403);if(view==="work-item-update"&&posted?.id){const{data:item}=await ops.from("work_items").select("id,client_id,title,description,source,target_person,target_role,metadata").eq("id",posted.id).maybeSingle();if(!item||!allowedClient(item.client_id)||!isAiDemand(item))return reply({error:"not_found_or_forbidden"},404);}if(view==="notifications-read"&&posted?.id){const{data:n}=await ops.from("platform_notifications").select("id,client_id").eq("id",posted.id).maybeSingle();if(!n||!allowedClient(n.client_id))return reply({error:"not_found_or_forbidden"},404);}}
  const response=await core();const contentType=response.headers.get("content-type")||"";if(!response.ok||!contentType.includes("application/json"))return new Response(response.body,{status:response.status,headers:{...CORS,"content-type":contentType||"application/json","cache-control":"no-store"}});const raw=await response.json();
  const DROP=Symbol("drop");const sanitize=(v:any):any=>{if(Array.isArray(v))return v.map(sanitize).filter((x)=>x!==DROP);if(!v||typeof v!=="object")return v;if(Object.prototype.hasOwnProperty.call(v,"client_id")&&v.client_id&&!allowedClient(v.client_id))return DROP;const out:Record<string,any>={};for(const[k,c]of Object.entries(v)){const n=sanitize(c);if(n!==DROP)out[k]=n;}return out;};let result:any=sanitize(raw);if(result===DROP)return reply({error:"not_found_or_forbidden"},404);
  if(view==="work"){result.items=(result.items||[]).filter((item:any)=>allowedClient(item.client_id)&&isAiDemand(item));const open=result.items.filter((i:any)=>!["COMPLETED","DISMISSED"].includes(String(i.status)));result.summary={open:open.length,critical:open.filter((i:any)=>i.priority==="CRITICAL").length,overdue:open.filter((i:any)=>i.due_at&&new Date(i.due_at).getTime()<Date.now()).length,waiting:open.filter((i:any)=>["WAITING","SNOOZED"].includes(String(i.status))).length,completed_30d:result.items.filter((i:any)=>i.status==="COMPLETED"&&i.completed_at&&new Date(i.completed_at).getTime()>=Date.now()-30*86400000).length};result.roster=[{person:"Gabriel Castro",role:"AI"}];result.scope_model="AI_N8N_CLIENTS_AI_DEMANDS_ONLY";return reply(result);}
  if(view==="home"){const clients=(result.clients||[]).filter((c:any)=>allowedClient(c.client_id));const active=clients.filter((c:any)=>["ACTIVE","ONBOARDING"].includes(String(c.lifecycle)));const activeIds=new Set(active.map((c:any)=>String(c.client_id)));const campaigns=(result.campaigns||[]).filter((r:any)=>r.client_id&&activeIds.has(String(r.client_id)));const notifications=(result.notifications||[]).filter((r:any)=>allowedClient(r.client_id));const commitments=(result.commitments||[]).filter((r:any)=>allowedClient(r.client_id));const conversations=(result.conversations||[]).filter((r:any)=>allowedClient(r.client_id));const alerts=(result.alerts||[]).filter((r:any)=>allowedClient(r.client_id));result.clients=clients;result.campaigns=campaigns;result.notifications=notifications;result.commitments=commitments;result.conversations=conversations;result.alerts=alerts;result.preclients=[];result.team=[];result.unassigned_clients=[];result.wallets=[];result.portfolio=null;result.audit_runs=[];result.audit_issues=[];result.access_requests_pending=[];result.integration_health=[];if(result.operations?.sla){for(const key of["waiting_agency","waiting_client","overdue_commitments"])result.operations.sla[key]=(result.operations.sla[key]||[]).filter((r:any)=>allowedClient(r.client_id));}if(result.operations){result.operations.evidence_review=[];if(result.operations.personal_focus){result.operations.personal_focus.open_tasks=(result.operations.personal_focus.open_tasks||[]).filter((t:any)=>allowedClient(t.client_id)&&isAiDemand(t));result.operations.personal_focus.closed_today=(result.operations.personal_focus.closed_today||[]).filter((t:any)=>allowedClient(t.client_id)&&isAiDemand(t));}}
    const{data:productivity}=await ops.rpc("clickup_range_report_ai_clients",{p_since:day(new Date(Date.now()-29*86400000)),p_until:day(),p_person:roster.clickup_user||"Gabriel Castro"});if(result.clickup){result.clickup.productivity_30d=productivity?.summary||[];result.clickup.productivity_daily=(productivity?.daily_totals||[]).map((r:any)=>({...r,person:roster.clickup_user||"Gabriel Castro"}));result.clickup.recent_completed=(result.clickup.recent_completed||[]).filter((t:any)=>allowedClient(t.client_id));result.clickup.total_completed=result.clickup.recent_completed.length;result.clickup.indexing=null;result.clickup.configured=null;result.clickup.webhook_configured=null;result.clickup.last_sync=null;}
    const spend=campaigns.reduce((s:number,r:any)=>s+Number(r.spend||0),0),leads=campaigns.reduce((s:number,r:any)=>s+Number(r.leads||0),0),clicks=campaigns.reduce((s:number,r:any)=>s+Number(r.clicks||0),0),impressions=campaigns.reduce((s:number,r:any)=>s+Number(r.impressions||0),0),latestDates=campaigns.map((r:any)=>r.latest_date).filter(Boolean).sort();result.media={latest_date:latestDates.at(-1)||null,age_days:campaigns.length?Math.max(...campaigns.map((r:any)=>Number(r.age_days??0))):null,is_stale:!campaigns.length||campaigns.some((r:any)=>r.is_stale),accounts:campaigns.length,clients_with_media:new Set(campaigns.map((r:any)=>r.client_id)).size,spend:Number(spend.toFixed(2)),leads,clicks,impressions,ctr:impressions?Number((clicks/impressions*100).toFixed(2)):null,cpc:clicks?Number((spend/clicks).toFixed(2)):null,cpl:leads?Number((spend/leads).toFixed(2)):null};const coverage={complete:0,partial:0,incomplete:0};for(const c of active){if(c.data_coverage==="COMPLETE")coverage.complete++;else if(c.data_coverage==="PARTIAL")coverage.partial++;else if(c.data_coverage==="INCOMPLETE")coverage.incomplete++;}result.coverage=coverage;const overdue=commitments.filter((r:any)=>r.due_at&&new Date(r.due_at).getTime()<Date.now());result.kpis={...(result.kpis||{}),active_clients:active.length,churned_clients:clients.filter((r:any)=>r.lifecycle==="CHURNED").length,onboarding_clients:active.filter((r:any)=>r.lifecycle==="ONBOARDING").length,operation_clients:active.filter((r:any)=>r.lifecycle==="ACTIVE").length,attention_now:active.filter((r:any)=>r.priority==="ATTENTION").length,follow_up:active.filter((r:any)=>r.priority==="FOLLOW_UP").length,ok:active.filter((r:any)=>r.priority==="OK").length,undetermined:active.filter((r:any)=>r.priority==="UNDETERMINED").length,data_incomplete:active.filter((r:any)=>r.priority==="DATA_INCOMPLETE").length,client_waiting_agency:active.filter((r:any)=>r.waiting_direction==="CLIENT_WAITING_AGENCY").length,agency_waiting_client:active.filter((r:any)=>r.waiting_direction==="AGENCY_WAITING_CLIENT").length,overdue_commitments:overdue.length,open_alerts:alerts.length,critical_alerts:alerts.filter((r:any)=>["CRITICAL","HIGH"].includes(String(r.severity))).length,semantic_review:conversations.filter((r:any)=>r.needs_semantic_review).length,queue_pending:0,queue_errors:0,team_members:1,team_unassigned:0,clients_unassigned:0};result.profile={...(result.profile||{}),person:"Gabriel Castro",role:"AI",access_level:"RESTRICTED",portfolio_scoped:true,scope_model:"AI_N8N_CLIENTS",ai_client_count:active.length};result.generated_at=new Date().toISOString();}
  return reply(result);
});
