-- Renata Fiel: historico de WhatsApp no CRM + pipeline editavel pelos membros.
-- A ingestao continua passando pelo repositorio canonico agency_ops.whatsapp_messages.

create table if not exists imobi_board.renata_fiel_whatsapp_config (
  id uuid primary key default gen_random_uuid(),
  agency_client_id uuid not null references agency_ops.clients(id) on delete cascade,
  tenant_id uuid null references imobi_board.tenants(id) on delete set null,
  instance_id text not null,
  webhook_secret text not null default encode(gen_random_bytes(24), 'hex'),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (agency_client_id),
  unique (instance_id)
);

create table if not exists imobi_board.renata_fiel_whatsapp_messages (
  id bigint generated by default as identity primary key,
  config_id uuid not null references imobi_board.renata_fiel_whatsapp_config(id) on delete cascade,
  tenant_id uuid null references imobi_board.tenants(id) on delete set null,
  contact_id uuid null references imobi_board.contacts(id) on delete set null,
  opportunity_id uuid null references imobi_board.opportunities(id) on delete set null,
  source_message_row_id bigint null,
  message_id text not null,
  instance_id text not null,
  connected_phone text null,
  lead_phone_normalized text null,
  chat_id text null,
  chat_name text null,
  sender_phone text null,
  sender_name text null,
  from_me boolean not null default false,
  message_type text null,
  body text null,
  status text null,
  event_at timestamptz null,
  received_at timestamptz not null default now(),
  match_status text not null default 'PENDING'
    check (match_status in ('PENDING','MATCHED','NO_TENANT','NO_CONTACT','NO_OPPORTUNITY')),
  raw_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (instance_id, message_id)
);

create index if not exists renata_fiel_whatsapp_messages_tenant_idx
  on imobi_board.renata_fiel_whatsapp_messages(tenant_id, event_at desc);
create index if not exists renata_fiel_whatsapp_messages_contact_idx
  on imobi_board.renata_fiel_whatsapp_messages(contact_id, event_at desc);
create index if not exists renata_fiel_whatsapp_messages_opportunity_idx
  on imobi_board.renata_fiel_whatsapp_messages(opportunity_id, event_at desc);
create index if not exists renata_fiel_whatsapp_messages_phone_idx
  on imobi_board.renata_fiel_whatsapp_messages(lead_phone_normalized);

alter table imobi_board.renata_fiel_whatsapp_config enable row level security;
alter table imobi_board.renata_fiel_whatsapp_messages enable row level security;
drop policy if exists renata_fiel_whatsapp_config_select on imobi_board.renata_fiel_whatsapp_config;
create policy renata_fiel_whatsapp_config_select
on imobi_board.renata_fiel_whatsapp_config
for select to authenticated
using (
  tenant_id is not null
  and tenant_id = any ((select imobi_board_priv.current_tenant_ids())::uuid[])
);

drop policy if exists renata_fiel_whatsapp_messages_select on imobi_board.renata_fiel_whatsapp_messages;
create policy renata_fiel_whatsapp_messages_select
on imobi_board.renata_fiel_whatsapp_messages
for select to authenticated
using (
  tenant_id is not null
  and (
    tenant_id = any ((select imobi_board_priv.admin_tenant_ids())::uuid[])
    or (opportunity_id is not null and imobi_board_priv.owns_opportunity(opportunity_id))
  )
);

grant select on imobi_board.renata_fiel_whatsapp_config to authenticated;
grant select on imobi_board.renata_fiel_whatsapp_messages to authenticated;
grant all on imobi_board.renata_fiel_whatsapp_config to service_role;
grant all on imobi_board.renata_fiel_whatsapp_messages to service_role;

create or replace function imobi_board_priv.normalize_whatsapp_phone(p_value text)
returns text language plpgsql immutable as $$
declare v text;
begin
  v := regexp_replace(coalesce(p_value,''), '[^0-9]', '', 'g');
  if v = '' then return null; end if;
  while length(v) > 11 and left(v,1) = '0' loop v := substr(v,2); end loop;
  if length(v) in (10,11) then return '55' || v; end if;
  return v;
end;
$$;

create or replace function imobi_board_priv.sync_renata_fiel_whatsapp_message(p_source_id bigint)
returns void language plpgsql security definer
set search_path = pg_catalog, agency_ops, imobi_board, imobi_board_priv
as $$
declare
  m agency_ops.whatsapp_messages%rowtype;
  cfg imobi_board.renata_fiel_whatsapp_config%rowtype;
  v_tenant uuid; v_contact uuid; v_opportunity uuid;
  v_phone text; v_match text;
begin
  select * into m from agency_ops.whatsapp_messages where id=p_source_id;
  if not found or coalesce(m.is_group,false) or coalesce(m.is_newsletter,false) then return; end if;

  select * into cfg from imobi_board.renata_fiel_whatsapp_config
  where active=true and instance_id=m.instance_id limit 1;
  if not found then return; end if;

  v_tenant := cfg.tenant_id;
  if v_tenant is null then
    select t.id into v_tenant from imobi_board.tenants t
    where t.agency_client_id=cfg.agency_client_id order by t.created_at desc limit 1;
    if v_tenant is not null then
      update imobi_board.renata_fiel_whatsapp_config
      set tenant_id=v_tenant,updated_at=now() where id=cfg.id;
    end if;
  end if;

  v_phone := imobi_board_priv.normalize_whatsapp_phone(
    case when coalesce(m.from_me,false)
      then coalesce(m.chat_id,m.participant_phone,m.sender_phone)
      else coalesce(m.sender_phone,m.participant_phone,m.chat_id) end
  );

  if v_tenant is null then
    v_match := 'NO_TENANT';
  else
    select c.id into v_contact from imobi_board.contacts c
    where c.tenant_id=v_tenant
      and (c.phone_normalized=v_phone or imobi_board_priv.normalize_whatsapp_phone(c.phone)=v_phone)
    order by c.updated_at desc limit 1;

    if v_contact is null then
      v_match := 'NO_CONTACT';
    else
      select o.id into v_opportunity from imobi_board.opportunities o
      where o.tenant_id=v_tenant and o.contact_id=v_contact
      order by (o.status='OPEN') desc,o.updated_at desc limit 1;
      v_match := case when v_opportunity is null then 'NO_OPPORTUNITY' else 'MATCHED' end;
    end if;
  end if;

  insert into imobi_board.renata_fiel_whatsapp_messages (
    config_id,tenant_id,contact_id,opportunity_id,source_message_row_id,
    message_id,instance_id,connected_phone,lead_phone_normalized,chat_id,chat_name,
    sender_phone,sender_name,from_me,message_type,body,status,event_at,received_at,
    match_status,raw_json,updated_at
  ) values (
    cfg.id,v_tenant,v_contact,v_opportunity,m.id,m.message_id,m.instance_id,m.connected_phone,v_phone,
    m.chat_id,m.chat_name,m.sender_phone,m.sender_name,coalesce(m.from_me,false),m.message_type,
    coalesce(m.text_body,m.caption),m.status,m.event_at,coalesce(m.received_at,now()),
    v_match,coalesce(m.raw_json,'{}'::jsonb),now()
  )
  on conflict (instance_id,message_id) do update set
    tenant_id=excluded.tenant_id,contact_id=excluded.contact_id,opportunity_id=excluded.opportunity_id,
    source_message_row_id=excluded.source_message_row_id,connected_phone=excluded.connected_phone,
    lead_phone_normalized=excluded.lead_phone_normalized,chat_id=excluded.chat_id,chat_name=excluded.chat_name,
    sender_phone=excluded.sender_phone,sender_name=excluded.sender_name,from_me=excluded.from_me,
    message_type=excluded.message_type,body=excluded.body,status=excluded.status,event_at=excluded.event_at,
    received_at=excluded.received_at,match_status=excluded.match_status,raw_json=excluded.raw_json,updated_at=now();

  if v_opportunity is not null then
    update imobi_board.opportunities set
      last_interaction_at=greatest(coalesce(last_interaction_at,'epoch'::timestamptz),coalesce(m.event_at,m.received_at,now())),
      first_contact_at=case when first_contact_at is null and not coalesce(m.from_me,false)
        then coalesce(m.event_at,m.received_at,now()) else first_contact_at end,
      updated_at=now()
    where id=v_opportunity;
  end if;
end;
$$;
create or replace function imobi_board_priv.trg_sync_renata_fiel_whatsapp()
returns trigger language plpgsql security definer
set search_path = pg_catalog, agency_ops, imobi_board, imobi_board_priv
as $$
begin
  perform imobi_board_priv.sync_renata_fiel_whatsapp_message(new.id);
  return new;
end;
$$;

drop trigger if exists trg_sync_renata_fiel_whatsapp on agency_ops.whatsapp_messages;
create trigger trg_sync_renata_fiel_whatsapp
after insert or update of text_body,caption,status,event_at,instance_id,sender_phone,participant_phone,chat_id
on agency_ops.whatsapp_messages for each row
execute function imobi_board_priv.trg_sync_renata_fiel_whatsapp();

create or replace function imobi_board_priv.trg_link_renata_fiel_tenant()
returns trigger language plpgsql security definer
set search_path = pg_catalog, agency_ops, imobi_board, imobi_board_priv
as $$
declare
  v_cfg imobi_board.renata_fiel_whatsapp_config%rowtype;
  r record;
begin
  if new.agency_client_id is not null then
    update imobi_board.renata_fiel_whatsapp_config
    set tenant_id=new.id,updated_at=now()
    where agency_client_id=new.agency_client_id and tenant_id is distinct from new.id
    returning * into v_cfg;
    if v_cfg.id is not null then
      for r in select id from agency_ops.whatsapp_messages
        where instance_id=v_cfg.instance_id
          and coalesce(is_group,false)=false and coalesce(is_newsletter,false)=false
      loop
        perform imobi_board_priv.sync_renata_fiel_whatsapp_message(r.id);
      end loop;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_link_renata_fiel_tenant on imobi_board.tenants;
create trigger trg_link_renata_fiel_tenant
after insert or update of agency_client_id on imobi_board.tenants
for each row execute function imobi_board_priv.trg_link_renata_fiel_tenant();

insert into imobi_board.renata_fiel_whatsapp_config(agency_client_id,tenant_id,instance_id,active)
select
  '41d70cb8-2160-4abe-9b96-a2cae27e91b6'::uuid,
  (select id from imobi_board.tenants
    where agency_client_id='41d70cb8-2160-4abe-9b96-a2cae27e91b6'::uuid
    order by created_at desc limit 1),
  '3F95B37A38AAB17B4C56B2194C7A232A',
  true
on conflict (agency_client_id) do update set
  instance_id=excluded.instance_id,
  tenant_id=coalesce(excluded.tenant_id,imobi_board.renata_fiel_whatsapp_config.tenant_id),
  active=true,updated_at=now();
drop policy if exists pipelines_member_write on imobi_board.pipelines;
drop policy if exists pipelines_admin_write on imobi_board.pipelines;
create policy pipelines_admin_write on imobi_board.pipelines
for all to authenticated
using (tenant_id = any ((select imobi_board_priv.admin_tenant_ids())::uuid[]))
with check (tenant_id = any ((select imobi_board_priv.admin_tenant_ids())::uuid[]));

drop policy if exists pipeline_stages_member_write on imobi_board.pipeline_stages;
drop policy if exists pipeline_stages_admin_write on imobi_board.pipeline_stages;
create policy pipeline_stages_admin_write on imobi_board.pipeline_stages
for all to authenticated
using (tenant_id = any ((select imobi_board_priv.admin_tenant_ids())::uuid[]))
with check (tenant_id = any ((select imobi_board_priv.admin_tenant_ids())::uuid[]));

create or replace function imobi_board.criar_etapa_pipeline(
  p_tenant_id uuid,p_name text,p_kind imobi_board.stage_kind default 'CONTACTED'
) returns uuid language plpgsql security invoker
set search_path=pg_catalog,imobi_board as $$
declare v_pipeline uuid; v_id uuid; v_sort smallint;
begin
  if length(btrim(coalesce(p_name,'')))<1 then
    raise exception 'Digite um nome para a etapa.' using errcode='P0001';
  end if;
  select id into v_pipeline from imobi_board.pipelines
  where tenant_id=p_tenant_id and is_default=true order by created_at limit 1;
  if v_pipeline is null then raise exception 'Pipeline principal nao encontrado.' using errcode='P0001'; end if;
  select coalesce(max(sort_order),-1)+1 into v_sort from imobi_board.pipeline_stages where pipeline_id=v_pipeline;
  insert into imobi_board.pipeline_stages(tenant_id,pipeline_id,name,kind,sort_order)
  values(p_tenant_id,v_pipeline,btrim(p_name),p_kind,v_sort) returning id into v_id;
  return v_id;
end;
$$;

create or replace function imobi_board.atualizar_etapa_pipeline(
  p_stage_id uuid,p_name text,p_kind imobi_board.stage_kind
) returns void language plpgsql security invoker
set search_path=pg_catalog,imobi_board as $$
begin
  if length(btrim(coalesce(p_name,'')))<1 then
    raise exception 'Digite um nome para a etapa.' using errcode='P0001';
  end if;
  update imobi_board.pipeline_stages set name=btrim(p_name),kind=p_kind where id=p_stage_id;
  if not found then raise exception 'Etapa nao encontrada ou sem permissao.' using errcode='P0001'; end if;
end;
$$;

create or replace function imobi_board.mover_etapa_pipeline(p_stage_id uuid,p_direction integer)
returns void language plpgsql security invoker
set search_path=pg_catalog,imobi_board as $$
declare v_pipeline uuid; v_sort smallint; v_other_id uuid; v_other_sort smallint;
begin
  if p_direction not in (-1,1) then raise exception 'Direcao invalida.' using errcode='P0001'; end if;
  select pipeline_id,sort_order into v_pipeline,v_sort from imobi_board.pipeline_stages where id=p_stage_id;
  if v_pipeline is null then raise exception 'Etapa nao encontrada ou sem permissao.' using errcode='P0001'; end if;
  if p_direction=-1 then
    select id,sort_order into v_other_id,v_other_sort from imobi_board.pipeline_stages
    where pipeline_id=v_pipeline and sort_order<v_sort order by sort_order desc limit 1;
  else
    select id,sort_order into v_other_id,v_other_sort from imobi_board.pipeline_stages
    where pipeline_id=v_pipeline and sort_order>v_sort order by sort_order asc limit 1;
  end if;
  if v_other_id is null then return; end if;
  set constraints pipeline_stages_position_uq deferred;
  update imobi_board.pipeline_stages set sort_order=case
    when id=p_stage_id then v_other_sort when id=v_other_id then v_sort else sort_order end
  where id in (p_stage_id,v_other_id);
end;
$$;

create or replace function imobi_board.excluir_etapa_pipeline(p_stage_id uuid)
returns void language plpgsql security invoker
set search_path=pg_catalog,imobi_board as $$
declare v_pipeline uuid; v_total integer; v_used integer;
begin
  select pipeline_id into v_pipeline from imobi_board.pipeline_stages where id=p_stage_id;
  if v_pipeline is null then raise exception 'Etapa nao encontrada ou sem permissao.' using errcode='P0001'; end if;
  select count(*) into v_used from imobi_board.opportunities where stage_id=p_stage_id;
  if v_used>0 then
    raise exception 'Essa etapa ainda tem % lead(s). Mova os leads antes de excluir.',v_used using errcode='P0001';
  end if;
  select count(*) into v_total from imobi_board.pipeline_stages where pipeline_id=v_pipeline;
  if v_total<=1 then raise exception 'O pipeline precisa ter pelo menos uma etapa.' using errcode='P0001'; end if;
  delete from imobi_board.pipeline_stages where id=p_stage_id;
end;
$$;

grant execute on function imobi_board.criar_etapa_pipeline(uuid,text,imobi_board.stage_kind) to authenticated;
grant execute on function imobi_board.atualizar_etapa_pipeline(uuid,text,imobi_board.stage_kind) to authenticated;
grant execute on function imobi_board.mover_etapa_pipeline(uuid,integer) to authenticated;
grant execute on function imobi_board.excluir_etapa_pipeline(uuid) to authenticated;

do $$
declare r record;
begin
  for r in select id from agency_ops.whatsapp_messages
    where instance_id='3F95B37A38AAB17B4C56B2194C7A232A'
      and coalesce(is_group,false)=false and coalesce(is_newsletter,false)=false
  loop
    perform imobi_board_priv.sync_renata_fiel_whatsapp_message(r.id);
  end loop;
end $$;
