-- Leonardo's profile is exclusively commercial.
-- The dedicated commercial page exposes Overview, Campaigns, Sales Funnel and Portfolio.

insert into agency_ops.dashboard_view_permissions
  (view_key, scope_type, scope_value, allowed, note, updated_at)
values
  ('overview', 'PERSON', 'Leonardo Augusto', true, 'Visão geral exclusivamente comercial', now()),
  ('campaigns', 'PERSON', 'Leonardo Augusto', true, 'Campanhas em modo comercial e somente leitura', now()),
  ('preclients', 'PERSON', 'Leonardo Augusto', true, 'Funil comercial', now()),
  ('clients', 'PERSON', 'Leonardo Augusto', true, 'Carteira comercial sem sinais operacionais', now()),
  ('commercial_direction', 'PERSON', 'Leonardo Augusto', true, 'Painel comercial dedicado', now()),
  ('executive', 'PERSON', 'Leonardo Augusto', true, 'Perfil executivo comercial', now()),
  ('agenda', 'PERSON', 'Leonardo Augusto', false, 'Fora do perfil comercial', now()),
  ('alerts', 'PERSON', 'Leonardo Augusto', false, 'Sem alertas operacionais', now()),
  ('audit', 'PERSON', 'Leonardo Augusto', false, 'Sem auditoria operacional', now()),
  ('clickup', 'PERSON', 'Leonardo Augusto', false, 'Sem gestão operacional no ClickUp', now()),
  ('contracts', 'PERSON', 'Leonardo Augusto', false, 'Fora do perfil comercial', now()),
  ('conversations', 'PERSON', 'Leonardo Augusto', false, 'Sem conversas', now()),
  ('creative', 'PERSON', 'Leonardo Augusto', false, 'Sem execução criativa', now()),
  ('diary', 'PERSON', 'Leonardo Augusto', false, 'Sem diário operacional', now()),
  ('evidence', 'PERSON', 'Leonardo Augusto', false, 'Sem evidências operacionais', now()),
  ('finance', 'PERSON', 'Leonardo Augusto', false, 'Fora do perfil comercial', now()),
  ('focus', 'PERSON', 'Leonardo Augusto', false, 'Sem foco operacional', now()),
  ('health', 'PERSON', 'Leonardo Augusto', false, 'Sem clientes com problema ou risco operacional', now()),
  ('onboarding', 'PERSON', 'Leonardo Augusto', false, 'Sem acompanhamento operacional de onboarding', now()),
  ('opsperf', 'PERSON', 'Leonardo Augusto', false, 'Sem desempenho operacional', now()),
  ('team', 'PERSON', 'Leonardo Augusto', false, 'Sem gestão da operação', now()),
  ('work', 'PERSON', 'Leonardo Augusto', false, 'Sem Central de Trabalho operacional', now()),
  ('overview', 'ROLE', 'COMMERCIAL', true, 'Visão geral exclusivamente comercial', now()),
  ('campaigns', 'ROLE', 'COMMERCIAL', true, 'Campanhas em modo comercial e somente leitura', now()),
  ('preclients', 'ROLE', 'COMMERCIAL', true, 'Funil comercial', now()),
  ('clients', 'ROLE', 'COMMERCIAL', true, 'Carteira comercial sem sinais operacionais', now()),
  ('commercial_direction', 'ROLE', 'COMMERCIAL', true, 'Painel comercial dedicado', now()),
  ('executive', 'ROLE', 'COMMERCIAL', true, 'Perfil executivo comercial', now()),
  ('agenda', 'ROLE', 'COMMERCIAL', false, 'Fora do perfil comercial', now()),
  ('alerts', 'ROLE', 'COMMERCIAL', false, 'Sem alertas operacionais', now()),
  ('audit', 'ROLE', 'COMMERCIAL', false, 'Sem auditoria operacional', now()),
  ('clickup', 'ROLE', 'COMMERCIAL', false, 'Sem gestão operacional no ClickUp', now()),
  ('contracts', 'ROLE', 'COMMERCIAL', false, 'Fora do perfil comercial', now()),
  ('conversations', 'ROLE', 'COMMERCIAL', false, 'Sem conversas', now()),
  ('creative', 'ROLE', 'COMMERCIAL', false, 'Sem execução criativa', now()),
  ('diary', 'ROLE', 'COMMERCIAL', false, 'Sem diário operacional', now()),
  ('evidence', 'ROLE', 'COMMERCIAL', false, 'Sem evidências operacionais', now()),
  ('finance', 'ROLE', 'COMMERCIAL', false, 'Fora do perfil comercial', now()),
  ('focus', 'ROLE', 'COMMERCIAL', false, 'Sem foco operacional', now()),
  ('health', 'ROLE', 'COMMERCIAL', false, 'Sem clientes com problema ou risco operacional', now()),
  ('onboarding', 'ROLE', 'COMMERCIAL', false, 'Sem acompanhamento operacional de onboarding', now()),
  ('opsperf', 'ROLE', 'COMMERCIAL', false, 'Sem desempenho operacional', now()),
  ('team', 'ROLE', 'COMMERCIAL', false, 'Sem gestão da operação', now()),
  ('work', 'ROLE', 'COMMERCIAL', false, 'Sem Central de Trabalho operacional', now())
on conflict (view_key, scope_type, scope_value) do update
set allowed = excluded.allowed,
    note = excluded.note,
    updated_at = excluded.updated_at;
