create or replace function agency_ops.add_business_days(p_started timestamptz, p_days integer)
returns timestamptz
language plpgsql
immutable
set search_path to 'pg_catalog'
as $$
declare
  v_result timestamptz := p_started;
  v_added integer := 0;
  v_isodow integer;
begin
  if p_started is null or coalesce(p_days,0) <= 0 then return p_started; end if;
  while v_added < p_days loop
    v_result := v_result + interval '1 day';
    v_isodow := extract(isodow from (v_result at time zone 'America/Sao_Paulo'))::integer;
    if v_isodow between 1 and 5 then v_added := v_added + 1; end if;
  end loop;
  return v_result;
end;
$$;

create table if not exists agency_ops.onboarding_sla_events (
  id bigint generated by default as identity primary key,
  case_id bigint not null references agency_ops.onboarding_cases(id) on delete cascade,
  client_id uuid not null references agency_ops.clients(id) on delete cascade,
  event_type text not null check (event_type in ('CREATIVE_PRODUCTION','CREATIVE_REVISION','CAMPAIGN_LAUNCH')),
  status text not null default 'OPEN' check (status in ('OPEN','COMPLETED','CANCELLED')),
  responsible_role text,
  responsible_person text,
  started_at timestamptz not null,
  due_at timestamptz not null,
  completed_at timestamptz,
  source_type text not null,
  source_id text not null,
  evidence text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(case_id,event_type,source_type,source_id)
);
create index if not exists onboarding_sla_events_case_idx on agency_ops.onboarding_sla_events(case_id,status,due_at);
create index if not exists onboarding_sla_events_client_idx on agency_ops.onboarding_sla_events(client_id,started_at desc);

create table if not exists agency_ops.weekly_commercial_reports (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references agency_ops.clients(id) on delete cascade,
  week_start date not null,
  week_end date not null,
  cs_owner text,
  gt_owner text,
  commercial_leads integer,
  meta_leads integer,
  meta_source text,
  meta_cross_status text not null default 'META_UNAVAILABLE',
  meta_difference integer,
  meta_difference_pct numeric,
  confidence_level text not null default 'BAIXA',
  metrics jsonb not null default '{}'::jsonb,
  previous_metrics jsonb not null default '{}'::jsonb,
  reporters jsonb not null default '[]'::jsonb,
  context jsonb not null default '{}'::jsonb,
  client_message text,
  internal_warning text,
  source_summary text,
  generated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(client_id,week_end)
);
create index if not exists weekly_commercial_reports_week_idx on agency_ops.weekly_commercial_reports(week_end desc,client_id);

create or replace function agency_ops.sync_onboarding_playbook_sla(p_case_id bigint)
returns void
language plpgsql
security definer
set search_path to 'agency_ops','pg_catalog'
as $$
declare
  v_case agency_ops.onboarding_cases%rowtype;
  v_client agency_ops.clients%rowtype;
  v_ready boolean := false;
  v_ready_at timestamptz;
  v_creative_done_at timestamptz;
  v_approval_at timestamptz;
  v_launch_done_at timestamptz;
  v_designer text;
  v_previous_internal text := coalesce(current_setting('agency_ops.onboarding_internal_update',true),'off');
begin
  select * into v_case from agency_ops.onboarding_cases where id=p_case_id;
  if not found then return; end if;
  select * into v_client from agency_ops.clients where id=v_case.client_id;
  select designer_owner into v_designer from agency_ops.client_health_board where client_id=v_case.client_id limit 1;

  select
    exists(select 1 from agency_ops.onboarding_stages where case_id=p_case_id and stage_code='PRODUCT_FORM' and status in ('DONE','SKIPPED'))
    and exists(select 1 from agency_ops.onboarding_stages where case_id=p_case_id and stage_code='PERSONA_FORM' and status in ('DONE','SKIPPED'))
    and exists(select 1 from agency_ops.onboarding_stages where case_id=p_case_id and stage_code='RAW_ASSETS' and status in ('DONE','SKIPPED'))
  into v_ready;

  perform set_config('agency_ops.onboarding_internal_update','on',true);

  if v_ready then
    select max(x.completed_at) into v_ready_at
    from (select completed_at from agency_ops.onboarding_stages where case_id=p_case_id and stage_code in ('PRODUCT_FORM','PERSONA_FORM','RAW_ASSETS') and completed_at is not null) x;
    v_ready_at := coalesce(v_case.creative_input_ready_at,v_ready_at,now());
    update agency_ops.onboarding_cases
    set creative_input_ready_at=coalesce(creative_input_ready_at,v_ready_at),
        creative_sla_started_at=coalesce(creative_sla_started_at,v_ready_at),
        creative_due_at=agency_ops.add_business_days(coalesce(creative_sla_started_at,v_ready_at),2),updated_at=now()
    where id=p_case_id;
    update agency_ops.onboarding_stages
    set status=case when status='PENDING' then 'IN_PROGRESS' else status end,
        started_at=coalesce(started_at,v_ready_at),due_at=agency_ops.add_business_days(coalesce(started_at,v_ready_at),2)
    where case_id=p_case_id and stage_code='CREATIVE_PRODUCTION' and status not in ('DONE','SKIPPED');
    select completed_at into v_creative_done_at from agency_ops.onboarding_stages where case_id=p_case_id and stage_code='CREATIVE_PRODUCTION';
    insert into agency_ops.onboarding_sla_events(case_id,client_id,event_type,status,responsible_role,responsible_person,started_at,due_at,completed_at,source_type,source_id,evidence,metadata)
    values(p_case_id,v_case.client_id,'CREATIVE_PRODUCTION',case when v_creative_done_at is null then 'OPEN' else 'COMPLETED' end,'DESIGN',v_designer,v_ready_at,agency_ops.add_business_days(v_ready_at,2),v_creative_done_at,'ONBOARDING_CASE','creative-input-ready','Formulário + persona + materiais liberaram o SLA de produção.',jsonb_build_object('business_days',2))
    on conflict(case_id,event_type,source_type,source_id) do update set status=excluded.status,responsible_person=coalesce(excluded.responsible_person,agency_ops.onboarding_sla_events.responsible_person),started_at=least(agency_ops.onboarding_sla_events.started_at,excluded.started_at),due_at=excluded.due_at,completed_at=coalesce(excluded.completed_at,agency_ops.onboarding_sla_events.completed_at),updated_at=now();
  end if;

  select completed_at into v_approval_at from agency_ops.onboarding_stages where case_id=p_case_id and stage_code='CREATIVE_APPROVAL' and status='DONE';
  select completed_at into v_launch_done_at from agency_ops.onboarding_stages where case_id=p_case_id and stage_code='CAMPAIGN_LAUNCH' and status='DONE';
  if v_approval_at is not null then
    update agency_ops.onboarding_stages set status=case when status in ('PENDING','MENTIONED') then 'IN_PROGRESS' else status end,started_at=coalesce(started_at,v_approval_at),due_at=case when status='DONE' then due_at else agency_ops.add_business_days(coalesce(started_at,v_approval_at),1) end where case_id=p_case_id and stage_code='CAMPAIGN_LAUNCH';
    insert into agency_ops.onboarding_sla_events(case_id,client_id,event_type,status,responsible_role,responsible_person,started_at,due_at,completed_at,source_type,source_id,evidence,metadata)
    values(p_case_id,v_case.client_id,'CAMPAIGN_LAUNCH',case when v_launch_done_at is null then 'OPEN' else 'COMPLETED' end,'GT',v_client.gt_owner,v_approval_at,agency_ops.add_business_days(v_approval_at,1),v_launch_done_at,'ONBOARDING_STAGE','creative-approved','Criativos aprovados; iniciou SLA para colocar a campanha no ar.',jsonb_build_object('business_days',1))
    on conflict(case_id,event_type,source_type,source_id) do update set status=excluded.status,responsible_person=excluded.responsible_person,started_at=excluded.started_at,due_at=excluded.due_at,completed_at=coalesce(excluded.completed_at,agency_ops.onboarding_sla_events.completed_at),updated_at=now();
  end if;
  update agency_ops.onboarding_cases oc set next_action_due=(select min(e.due_at) from agency_ops.onboarding_sla_events e where e.case_id=oc.id and e.status='OPEN'),updated_at=now() where oc.id=p_case_id;
  perform set_config('agency_ops.onboarding_internal_update',v_previous_internal,true);
exception when others then
  perform set_config('agency_ops.onboarding_internal_update',v_previous_internal,true);
  raise;
end;
$$;

create or replace function agency_ops.maybe_start_creative_sla(p_case bigint) returns void language plpgsql security definer set search_path to 'agency_ops','pg_catalog' as $$ begin perform agency_ops.sync_onboarding_playbook_sla(p_case); end; $$;
create or replace function agency_ops.tg_sync_onboarding_playbook_sla() returns trigger language plpgsql security definer set search_path to 'agency_ops','pg_catalog' as $$ begin if pg_trigger_depth()>1 then return new; end if; if tg_op='INSERT' or new.status is distinct from old.status or new.completed_at is distinct from old.completed_at then perform agency_ops.sync_onboarding_playbook_sla(new.case_id); end if; return new; end; $$;
drop trigger if exists zz_sync_onboarding_playbook_sla on agency_ops.onboarding_stages;
create trigger zz_sync_onboarding_playbook_sla after insert or update of status,completed_at on agency_ops.onboarding_stages for each row execute function agency_ops.tg_sync_onboarding_playbook_sla();

create or replace function agency_ops.tg_client_adjustment_onboarding_sla()
returns trigger language plpgsql security definer set search_path to 'agency_ops','pg_catalog'
as $$
declare v_case_id bigint;v_started timestamptz;v_due timestamptz;v_designer text;v_completed timestamptz;
begin
  if new.client_id is null or coalesce(new.category_code,'')<>'CREATIVE' or coalesce(new.request_origin,'')<>'CLIENT' then return new; end if;
  select oc.id into v_case_id from agency_ops.onboarding_cases oc where oc.client_id=new.client_id and oc.status='OPEN' and exists(select 1 from agency_ops.onboarding_stages s where s.case_id=oc.id and s.stage_code='CREATIVE_PRODUCTION' and s.status='DONE') and not exists(select 1 from agency_ops.onboarding_stages s where s.case_id=oc.id and s.stage_code='CAMPAIGN_LAUNCH' and s.status='DONE') order by oc.updated_at desc,oc.id desc limit 1;
  if v_case_id is null then return new; end if;
  v_started:=coalesce(new.occurred_at,new.created_at,now());v_due:=agency_ops.add_business_days(v_started,1);v_completed:=case when new.resolved_at is not null or upper(coalesce(new.status,'')) in ('RESOLVED','DONE','CLOSED') then coalesce(new.resolved_at,new.updated_at,now()) end;
  select coalesce(new.responsible_person,h.designer_owner) into v_designer from agency_ops.client_health_board h where h.client_id=new.client_id limit 1;
  insert into agency_ops.onboarding_sla_events(case_id,client_id,event_type,status,responsible_role,responsible_person,started_at,due_at,completed_at,source_type,source_id,evidence,metadata)
  values(v_case_id,new.client_id,'CREATIVE_REVISION',case when v_completed is null then 'OPEN' else 'COMPLETED' end,'DESIGN',v_designer,v_started,v_due,v_completed,'CLIENT_ADJUSTMENT',new.id::text,left(new.descricao,1800),jsonb_build_object('business_days',1,'adjustment_status',new.status))
  on conflict(case_id,event_type,source_type,source_id) do update set status=excluded.status,responsible_person=coalesce(excluded.responsible_person,agency_ops.onboarding_sla_events.responsible_person),due_at=excluded.due_at,completed_at=excluded.completed_at,evidence=excluded.evidence,metadata=excluded.metadata,updated_at=now();
  update agency_ops.onboarding_cases oc set next_action_due=(select min(e.due_at) from agency_ops.onboarding_sla_events e where e.case_id=oc.id and e.status='OPEN'),updated_at=now() where oc.id=v_case_id;
  return new;
end;
$$;
drop trigger if exists client_adjustment_onboarding_sla on agency_ops.client_adjustments;
create trigger client_adjustment_onboarding_sla after insert or update of status,resolved_at,responsible_person on agency_ops.client_adjustments for each row execute function agency_ops.tg_client_adjustment_onboarding_sla();

create or replace view agency_ops.onboarding_sla_board as
select e.id,e.case_id,e.client_id,c.display_name,c.lifecycle,c.cs_owner,c.gt_owner,e.event_type,e.status,e.responsible_role,e.responsible_person,e.started_at,e.due_at,e.completed_at,e.source_type,e.source_id,e.evidence,e.metadata,
case when e.status='COMPLETED' and e.completed_at>e.due_at then 'DONE_LATE' when e.status='COMPLETED' then 'ON_TIME' when e.status='OPEN' and e.due_at<now() then 'OVERDUE' when e.status='OPEN' and e.due_at-now()<=interval '4 hours' then 'DUE_SOON' else 'ON_TRACK' end as sla_status,
case when e.status='OPEN' and e.due_at<now() then extract(epoch from (now()-e.due_at))/60 else 0 end as overdue_minutes
from agency_ops.onboarding_sla_events e join agency_ops.clients c on c.id=e.client_id;

comment on view agency_ops.onboarding_sla_board is 'SLAs do playbook: produção 2 dias úteis, ajuste criativo 1 dia útil e campanha 1 dia útil após aprovação.';

do $$ declare r record; begin for r in select id from agency_ops.onboarding_cases where status='OPEN' loop perform agency_ops.sync_onboarding_playbook_sla(r.id); end loop; end $$;
