-- Mantem banco, Edge Function e interface na mesma fonte versionada.
-- O schema agency_ops e privado; toda leitura/escrita passa pela Edge Function autenticada.

create table if not exists agency_ops.work_items (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references agency_ops.clients(id) on delete set null,
  type text not null default 'GENERAL' check (type in ('ESCALATION','CREATIVE_REQUEST','TECHNICAL','CLIENT_FOLLOWUP','CLICKUP','FINANCE','GENERAL')),
  status text not null default 'OPEN' check (status in ('OPEN','IN_PROGRESS','WAITING','SNOOZED','COMPLETED','DISMISSED')),
  priority text not null default 'MEDIUM' check (priority in ('CRITICAL','HIGH','MEDIUM','LOW')),
  title text not null,
  description text,
  source text not null default 'dashboard',
  source_id text,
  created_by_user_key text,
  created_by_person text,
  target_role text,
  target_person text,
  due_at timestamptz,
  snoozed_until timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  completed_by text,
  resolution text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists agency_ops.work_item_events (
  id bigint generated by default as identity primary key,
  work_item_id uuid not null references agency_ops.work_items(id) on delete cascade,
  event_type text not null,
  actor_user_key text,
  actor_person text,
  previous_status text,
  new_status text,
  detail text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

-- Leitura e' individual. Uma pessoa nao apaga a notificacao do restante do perfil.
create table if not exists agency_ops.platform_notification_reads (
  notification_id uuid not null references agency_ops.platform_notifications(id) on delete cascade,
  user_key text not null,
  read_at timestamptz not null default now(),
  primary key (notification_id, user_key)
);

create index if not exists work_items_client_idx on agency_ops.work_items (client_id, created_at desc);
create index if not exists work_items_creator_idx on agency_ops.work_items (created_by_person, created_at desc);
create index if not exists work_items_target_person_status_idx on agency_ops.work_items (target_person, status, due_at);
create index if not exists work_items_target_role_status_idx on agency_ops.work_items (target_role, status, due_at);
create index if not exists work_item_events_item_idx on agency_ops.work_item_events (work_item_id, occurred_at desc);
create index if not exists platform_notification_reads_user_idx on agency_ops.platform_notification_reads (user_key, read_at desc);

alter table agency_ops.work_items enable row level security;
alter table agency_ops.work_item_events enable row level security;
alter table agency_ops.platform_notification_reads enable row level security;

create or replace function agency_ops.touch_work_item()
returns trigger
language plpgsql
set search_path to 'agency_ops', 'public'
as $$
begin
  new.updated_at := now();
  if new.status = 'IN_PROGRESS' and old.status is distinct from new.status and new.started_at is null then
    new.started_at := now();
  end if;
  if new.status = 'COMPLETED' and old.status is distinct from new.status and new.completed_at is null then
    new.completed_at := now();
  end if;
  return new;
end;
$$;

create or replace function agency_ops.audit_work_item()
returns trigger
language plpgsql
set search_path to 'agency_ops', 'public'
as $$
declare
  event_label text;
begin
  event_label := case when tg_op = 'INSERT' then 'CREATED' else 'STATUS_CHANGED' end;
  insert into agency_ops.work_item_events(work_item_id,event_type,actor_user_key,actor_person,previous_status,new_status,detail,metadata)
  values (
    new.id,event_label,new.created_by_user_key,coalesce(new.completed_by,new.created_by_person),
    case when tg_op = 'UPDATE' then old.status else null end,new.status,
    case when tg_op = 'INSERT' then new.description else new.resolution end,
    jsonb_build_object('target_role',new.target_role,'target_person',new.target_person,'type',new.type)
  );

  if tg_op = 'INSERT' then
    insert into agency_ops.platform_notifications(event_key,type,level,title,description,client_id,source,actor,occurred_at,metadata)
    values (
      'work-item-created:' || new.id::text,'WORK_ITEM_ASSIGNED',
      case new.priority when 'CRITICAL' then 'CRITICAL' when 'HIGH' then 'HIGH' else 'INFO' end,
      'Nova demanda: ' || new.title,coalesce(new.description,'Abra a Central de Trabalho para ver e assumir.'),
      new.client_id,'work_center',new.created_by_person,now(),
      jsonb_build_object('work_item_id',new.id,'target_role',new.target_role,'target_person',new.target_person,'status',new.status)
    );
  elsif old.status is distinct from new.status and new.status = 'COMPLETED' then
    insert into agency_ops.platform_notifications(event_key,type,level,title,description,client_id,source,actor,occurred_at,metadata)
    values (
      'work-item-completed:' || new.id::text,'WORK_ITEM_COMPLETED','SUCCESS',
      'Demanda concluída: ' || new.title,coalesce(new.resolution,'A demanda foi marcada como concluída.'),
      new.client_id,'work_center',new.completed_by,now(),
      jsonb_build_object('work_item_id',new.id,'target_person',new.created_by_person,'status',new.status)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_touch_work_item on agency_ops.work_items;
create trigger trg_touch_work_item before update on agency_ops.work_items for each row execute function agency_ops.touch_work_item();
drop trigger if exists trg_audit_work_item_insert on agency_ops.work_items;
create trigger trg_audit_work_item_insert after insert on agency_ops.work_items for each row execute function agency_ops.audit_work_item();
drop trigger if exists trg_audit_work_item_update on agency_ops.work_items;
create trigger trg_audit_work_item_update after update on agency_ops.work_items for each row execute function agency_ops.audit_work_item();

insert into agency_ops.dashboard_view_permissions(view_key,scope_type,scope_value,allowed,note)
values
  ('work','ROLE','GT',true,'Central de Trabalho por perfil'),
  ('work','ROLE','CS',true,'Central de Trabalho por perfil'),
  ('work','ROLE','DESIGN',true,'Central de Trabalho por perfil'),
  ('work','ROLE','AI',true,'Central de Trabalho por perfil'),
  ('work','ROLE','MGMT',true,'Central de Trabalho por perfil')
on conflict (view_key,scope_type,scope_value)
do update set allowed=excluded.allowed,note=excluded.note,updated_at=now();

revoke all on agency_ops.work_items from anon, authenticated;
revoke all on agency_ops.work_item_events from anon, authenticated;
revoke all on agency_ops.platform_notification_reads from anon, authenticated;
