alter table agency_ops.generated_tasks
  add column if not exists grounding_score numeric(5,4),
  add column if not exists grounding_reason text,
  add column if not exists source_excerpt_hash text,
  add column if not exists validation_version text;

comment on column agency_ops.generated_tasks.grounding_score is
  'Deterministic grounding confidence computed after AI suggestion and before any LIVE delivery.';
comment on column agency_ops.generated_tasks.grounding_reason is
  'Deterministic validation outcome explaining why a generated task was accepted or discarded.';
comment on column agency_ops.generated_tasks.source_excerpt_hash is
  'SHA-256 of the event excerpt used to validate this generated task without duplicating source text.';
comment on column agency_ops.generated_tasks.validation_version is
  'Version of the deterministic Task Engine validation rules applied to the row.';

create table if not exists agency_ops.system_review_events (
  id bigint generated by default as identity primary key,
  source_event_id bigint not null references agency_ops.task_generation_events(id) on delete cascade,
  client_id uuid,
  chat_id text,
  proposed_title text not null,
  proposed_title_norm text not null,
  proposed_description text,
  reason text not null,
  validation_version text not null,
  source_excerpt_hash text,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'PENDING'
    check (status in ('PENDING', 'RESOLVED', 'IGNORED')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

comment on table agency_ops.system_review_events is
  'Technical review queue for AI suggestions that are system/data-maintenance work rather than human operational tasks.';

create unique index if not exists system_review_events_event_reason_title_uidx
  on agency_ops.system_review_events (source_event_id, reason, proposed_title_norm);
create index if not exists system_review_events_status_created_idx
  on agency_ops.system_review_events (status, created_at desc);

alter table agency_ops.system_review_events enable row level security;
revoke all on agency_ops.system_review_events from anon, authenticated;
grant select, insert, update on agency_ops.system_review_events to service_role;

-- Existing rows predate the deterministic audit columns. Keep lineage explicit.
update agency_ops.generated_tasks
set validation_version = 'legacy-pre-grounding-v2'
where validation_version is null;

-- Remove the known class of context leakage from the current SHADOW sample without relying on row ids.
update agency_ops.generated_tasks
set
  status = 'DESCARTADA',
  grounding_score = 0.2500,
  grounding_reason = case
    when lower(titulo) like '%triagem%' or lower(titulo) like '%titularidade%'
      then 'retroactive:internal_system_task'
    when lower(titulo) like '%pagamento%'
      then 'retroactive:unsupported_context:pagamento'
    when lower(titulo) like '%notifica%'
      then 'retroactive:unsupported_context:notificacao'
    else 'retroactive:grounding_rejected'
  end,
  validation_version = 'grounding-v2-retroactive',
  evidencia = coalesce(evidencia, '{}'::jsonb) || jsonb_build_object(
    'discard_reason', 'grounding_v2_retroactive_cleanup',
    'validation_version', 'grounding-v2-retroactive'
  )
where status = 'PROPOSTA'
  and (
    lower(titulo) like '%triagem%'
    or lower(titulo) like '%titularidade%'
    or (
      lower(titulo) like '%pagamento%'
      and lower(coalesce(evidencia->>'trecho', '')) not like '%pagamento%'
      and lower(coalesce(evidencia->>'trecho', '')) not like '%pagar%'
      and lower(coalesce(evidencia->>'trecho', '')) not like '%boleto%'
      and lower(coalesce(evidencia->>'trecho', '')) not like '%cobran%'
    )
    or (
      lower(titulo) like '%notifica%'
      and lower(coalesce(evidencia->>'trecho', '')) not like '%notifica%'
    )
  );