create table if not exists agency_ops.meeting_integration_providers (
  provider_key text primary key check (provider_key ~ '^[A-Z0-9_:-]{2,80}$'),
  label text not null,
  category text not null check (category in ('GOOGLE','CRM','MESSAGING','DOCUMENTS','MEETING','MCP','IMPORT')),
  auth_mode text not null check (auth_mode in ('OAUTH2','API_KEY','INTERNAL','MCP','IMPORT')),
  capabilities jsonb not null default '[]'::jsonb,
  enabled boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into agency_ops.meeting_integration_providers(provider_key,label,category,auth_mode,capabilities,metadata) values
 ('GOOGLE_WORKSPACE','Google','GOOGLE','OAUTH2','["GMAIL_READ","GMAIL_SEND","CALENDAR_READ","CALENDAR_WRITE","DRIVE_READ","MEET_CONTEXT","PEOPLE_IDENTITY"]'::jsonb,'{"products":["Gmail","Google Calendar","Google Drive","Google Meet"],"rollout":"oauth_required"}'::jsonb),
 ('WHATSAPP','WhatsApp','MESSAGING','INTERNAL','["READ_CONTEXT","SEND_FOLLOWUP","LINK_CONTACT"]'::jsonb,'{"transport":"existing_zapi","rollout":"reuse_existing"}'::jsonb),
 ('PIPEDRIVE','Pipedrive','CRM','OAUTH2','["READ_DEALS","READ_CONTACTS","WRITE_NOTES","WRITE_FIELDS","WRITE_ACTIVITIES"]'::jsonb,'{"rollout":"oauth_required"}'::jsonb),
 ('SALESFORCE','Salesforce','CRM','OAUTH2','["READ_OPPORTUNITIES","READ_CONTACTS","WRITE_NOTES","WRITE_FIELDS","WRITE_TASKS"]'::jsonb,'{"rollout":"oauth_required"}'::jsonb),
 ('HUBSPOT','HubSpot','CRM','OAUTH2','["READ_DEALS","READ_CONTACTS","WRITE_NOTES","WRITE_PROPERTIES","WRITE_TASKS"]'::jsonb,'{"rollout":"oauth_required"}'::jsonb),
 ('NOTION','Notion','DOCUMENTS','OAUTH2','["READ_PAGES","READ_DATABASES","WRITE_PAGES"]'::jsonb,'{"rollout":"oauth_required"}'::jsonb),
 ('ZOOM','Zoom','MEETING','OAUTH2','["MEETING_CONTEXT","RECORDING_IMPORT","TRANSCRIPT_IMPORT"]'::jsonb,'{"rollout":"later"}'::jsonb),
 ('MICROSOFT_TEAMS','Microsoft Teams','MEETING','OAUTH2','["MEETING_CONTEXT","CALENDAR_CONTEXT","RECORDING_IMPORT","TRANSCRIPT_IMPORT"]'::jsonb,'{"rollout":"later"}'::jsonb),
 ('PLAUD','Plaud','IMPORT','IMPORT','["TRANSCRIPT_IMPORT","AUDIO_IMPORT"]'::jsonb,'{"rollout":"drive_or_upload"}'::jsonb),
 ('MCP_API','MCP API','MCP','MCP','["TOOLS","RESOURCES","ACTIONS"]'::jsonb,'{"rollout":"generic"}'::jsonb)
on conflict (provider_key) do update set
 label=excluded.label, category=excluded.category, auth_mode=excluded.auth_mode,
 capabilities=excluded.capabilities, metadata=agency_ops.meeting_integration_providers.metadata || excluded.metadata,
 enabled=true, updated_at=now();

create table if not exists agency_ops.meeting_integration_accounts (
  id uuid primary key default gen_random_uuid(),
  owner_person text not null,
  provider_key text not null references agency_ops.meeting_integration_providers(provider_key),
  account_slot text not null default 'primary',
  external_account_id text,
  account_email text,
  display_name text,
  status text not null default 'DISCONNECTED' check (status in ('DISCONNECTED','CONNECTING','ACTIVE','ERROR','REVOKED')),
  granted_scopes text[] not null default '{}',
  enabled_capabilities jsonb not null default '[]'::jsonb,
  access_secret_id uuid,
  refresh_secret_id uuid,
  webhook_secret_id uuid,
  token_expires_at timestamptz,
  last_sync_at timestamptz,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(owner_person,provider_key,account_slot)
);
create index if not exists meeting_integration_accounts_owner_idx on agency_ops.meeting_integration_accounts(owner_person,status,provider_key);

create table if not exists agency_ops.meeting_oauth_states (
  id uuid primary key default gen_random_uuid(),
  owner_person text not null,
  provider_key text not null references agency_ops.meeting_integration_providers(provider_key),
  state_hash text not null unique,
  code_verifier_secret_id uuid,
  redirect_uri text not null,
  requested_scopes text[] not null default '{}',
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists meeting_oauth_states_expiry_idx on agency_ops.meeting_oauth_states(expires_at) where used_at is null;

create table if not exists agency_ops.meeting_integration_events (
  id bigint generated by default as identity primary key,
  owner_person text not null,
  provider_key text not null,
  account_id uuid,
  event_type text not null,
  status text not null default 'OK',
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists meeting_integration_events_owner_idx on agency_ops.meeting_integration_events(owner_person,created_at desc);

alter table agency_ops.meeting_integration_providers enable row level security;
alter table agency_ops.meeting_integration_accounts enable row level security;
alter table agency_ops.meeting_oauth_states enable row level security;
alter table agency_ops.meeting_integration_events enable row level security;
revoke all on agency_ops.meeting_integration_providers, agency_ops.meeting_integration_accounts, agency_ops.meeting_oauth_states, agency_ops.meeting_integration_events from public, anon, authenticated;
grant select,insert,update,delete on agency_ops.meeting_integration_providers, agency_ops.meeting_integration_accounts, agency_ops.meeting_oauth_states, agency_ops.meeting_integration_events to service_role;
grant usage, select on all sequences in schema agency_ops to service_role;

insert into agency_ops.worker_runtime_config(key,value,updated_at)
values ('meeting_integrations','{"mode":"off","google_sync":false,"crm_sync":false,"mail_context":false}'::jsonb,now())
on conflict (key) do update set value=agency_ops.worker_runtime_config.value || excluded.value, updated_at=now();