-- Keep factual report data immutable while allowing GT/MGMT to edit client-facing narrative.

alter table agency_ops.weekly_client_reports
  add column if not exists editorial_narrative jsonb,
  add column if not exists editorial_status text not null default 'SYSTEM_DRAFT',
  add column if not exists edited_by text,
  add column if not exists edited_at timestamptz,
  add column if not exists shared_at timestamptz;

alter table agency_ops.weekly_client_reports drop constraint if exists weekly_client_reports_editorial_status_check;
alter table agency_ops.weekly_client_reports
  add constraint weekly_client_reports_editorial_status_check
  check (editorial_status in ('SYSTEM_DRAFT','EDITED'));

create table if not exists agency_ops.weekly_report_editorial_history (
  id bigint generated always as identity primary key,
  report_id uuid not null references agency_ops.weekly_client_reports(id) on delete cascade,
  editor text not null,
  before_narrative jsonb,
  after_narrative jsonb not null,
  created_at timestamptz not null default now()
);
create index if not exists weekly_report_editorial_history_report_idx
  on agency_ops.weekly_report_editorial_history(report_id, created_at desc);

create or replace function agency_ops.audit_weekly_snapshot_report()
returns trigger
language plpgsql
security definer
set search_path to 'agency_ops','public'
as $$
declare
  v_account record;
  v_campaign record;
  v_spend_ok boolean;
  v_results_ok boolean;
  v_impressions_ok boolean;
  v_clicks_ok boolean;
  v_audit jsonb;
begin
  if new.status <> 'READY' or new.generation_source <> 'META_SNAPSHOT' or new.meta_run_id is null then
    return new;
  end if;

  select
    coalesce(spend,0)::numeric as spend,
    coalesce(results,0)::numeric as results,
    coalesce(impressions,0)::bigint as impressions,
    coalesce(clicks,0)::bigint as clicks,
    data_status,
    date_from,
    date_to,
    account_count,
    meta_ad_account_ids
  into v_account
  from agency_ops.meta_performance_snapshots
  where run_id=new.meta_run_id and client_id=new.client_id and period_days=7
  limit 1;

  if not found then
    new.audit_status := 'FAIL';
    new.status := 'REVIEW_REQUIRED';
    new.snapshot := coalesce(new.snapshot,'{}'::jsonb) || jsonb_build_object(
      'audit', jsonb_build_object('status','FAIL','reason','missing_account_snapshot')
    );
    return new;
  end if;

  select
    coalesce(sum(spend),0)::numeric as spend,
    coalesce(sum(results),0)::numeric as results,
    coalesce(sum(impressions),0)::bigint as impressions,
    coalesce(sum(clicks),0)::bigint as clicks,
    count(*)::int as campaign_rows
  into v_campaign
  from agency_ops.meta_campaign_performance_snapshots
  where run_id=new.meta_run_id and client_id=new.client_id and period_days=7;

  v_spend_ok := abs(v_account.spend - v_campaign.spend) <= 0.10;
  v_results_ok := abs(v_account.results - v_campaign.results) <= 0.01;
  v_impressions_ok := abs(v_account.impressions - v_campaign.impressions) <= 1;
  v_clicks_ok := abs(v_account.clicks - v_campaign.clicks) <= 1;

  v_audit := jsonb_build_object(
    'status', case when v_spend_ok and v_results_ok and v_impressions_ok and v_clicks_ok then 'PASS' else 'FAIL' end,
    'source','META_MARKETING_API_DIRECT_RANGE',
    'period',jsonb_build_object('from',v_account.date_from,'to',v_account.date_to),
    'accounts',v_account.meta_ad_account_ids,
    'account_count',v_account.account_count,
    'campaign_rows',v_campaign.campaign_rows,
    'checks',jsonb_build_object(
      'spend',jsonb_build_object('pass',v_spend_ok,'account',v_account.spend,'campaign_sum',v_campaign.spend),
      'results',jsonb_build_object('pass',v_results_ok,'account',v_account.results,'campaign_sum',v_campaign.results),
      'impressions',jsonb_build_object('pass',v_impressions_ok,'account',v_account.impressions,'campaign_sum',v_campaign.impressions),
      'clicks',jsonb_build_object('pass',v_clicks_ok,'account',v_account.clicks,'campaign_sum',v_campaign.clicks)
    ),
    'audited_at',now()
  );

  if v_spend_ok and v_results_ok and v_impressions_ok and v_clicks_ok then
    new.audit_status := 'PASS';
  else
    new.audit_status := 'FAIL';
    new.status := 'REVIEW_REQUIRED';
  end if;
  new.snapshot := coalesce(new.snapshot,'{}'::jsonb) || jsonb_build_object('audit',v_audit);
  return new;
end;
$$;

DROP TRIGGER IF EXISTS trg_audit_weekly_snapshot_report ON agency_ops.weekly_client_reports;
create trigger trg_audit_weekly_snapshot_report
before insert or update of status,snapshot on agency_ops.weekly_client_reports
for each row execute function agency_ops.audit_weekly_snapshot_report();

-- Audit reports generated by the first release as well.
update agency_ops.weekly_client_reports
set status=status, updated_at=updated_at
where status='READY' and generation_source='META_SNAPSHOT' and meta_run_id is not null;
