-- Agenda operacional automatica.
-- Equivalente final aplicado em producao no Supabase em 2026-08-24.
-- O backfill historico foi executado operacionalmente na implantacao; esta migration
-- preserva o schema, detector, permissoes e RPC autenticada para novos ambientes.

create table if not exists agency_ops.meeting_agenda_events (
  id bigint generated by default as identity primary key,
  person text,
  client_id uuid references agency_ops.clients(id),
  chat_id text not null,
  chat_name text,
  status text not null default 'PROPOSED'
    check (status in ('PROPOSED','SCHEDULED','SUPERSEDED','CANCELLED')),
  scheduled_for timestamptz not null,
  duration_minutes integer not null default 60 check (duration_minutes between 5 and 480),
  topic text,
  meet_url text,
  source text not null default 'WHATSAPP',
  source_record_id text,
  proposal_message_id bigint,
  confirmation_message_id bigint,
  confidence numeric,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists meeting_agenda_events_person_time_idx
  on agency_ops.meeting_agenda_events(person, scheduled_for desc)
  where status in ('SCHEDULED','PROPOSED');
create index if not exists meeting_agenda_events_chat_time_idx
  on agency_ops.meeting_agenda_events(chat_id, scheduled_for desc);
create unique index if not exists meeting_agenda_events_source_record_uidx
  on agency_ops.meeting_agenda_events(source, source_record_id)
  where source_record_id is not null;

comment on table agency_ops.meeting_agenda_events is
  'Reunioes combinadas identificadas automaticamente. PROPOSED nunca aparece como reuniao confirmada na agenda.';

create or replace function agency_ops.extract_agenda_meeting_datetime(
  p_text text,
  p_reference timestamptz default now()
) returns timestamptz
language plpgsql
stable
security definer
set search_path to 'agency_ops','pg_catalog','extensions'
as $$
declare
  v_dt timestamptz;
  v text := lower(unaccent(coalesce(p_text,'')));
  m text[];
  v_ref timestamp := p_reference at time zone 'America/Sao_Paulo';
  v_hour int;
  v_min int := 0;
begin
  v_dt := agency_ops.extract_ptbr_meeting_datetime(p_text,p_reference);
  if v_dt is not null then return v_dt; end if;

  m := regexp_match(v, '(hoje|agora)[^0-9]{0,28}([0-2]?[0-9])(?::([0-5][0-9])|[[:space:]]*h(?:oras?|rs?)?)');
  if m is not null then
    v_hour := m[2]::int;
    v_min := coalesce(nullif(m[3],''),'0')::int;
    return make_timestamptz(
      extract(year from v_ref)::int,
      extract(month from v_ref)::int,
      extract(day from v_ref)::int,
      v_hour,v_min,0,'America/Sao_Paulo'
    );
  end if;
  return null;
end
$$;

create or replace function agency_ops.infer_agenda_meeting_topic(
  p_text text,
  p_client_id uuid,
  p_chat_id text,
  p_at timestamptz
) returns text
language plpgsql
stable
security definer
set search_path to 'agency_ops','pg_catalog','extensions'
as $$
declare
  v text := lower(unaccent(coalesce(p_text,'')));
  v_fallback text;
begin
  if v ~ '(call[[:space:]]+de[[:space:]]+ap|primeira reuniao|1a reuniao|reuniao de apresentacao|apresentacao)' then return 'Call de AP'; end if;
  if v ~ '(call[[:space:]]+de[[:space:]]+pp|produto.{0,18}persona|persona.{0,18}produto|reuniao de formular|reuniao de forms|formularios?|forms)' then return 'Call de PP'; end if;
  if v ~ '(call[[:space:]]+de[[:space:]]+int|reuniao de integracao|integracao com (o )?gt|finalizacao da integracao)' then return 'Call de INT'; end if;
  if v ~ '(briefing.{0,12}ia|ia.{0,12}briefing)' then return 'Briefing de IA'; end if;
  if v ~ '(performance|resultado|campanha|lead|otimiz)' then return 'Performance / campanhas'; end if;
  if v ~ '(criativ|design|video|roteiro)' then return 'Criativos / conteúdo'; end if;
  if v ~ '(crm|atendimento|follow.?up|roleta)' then return 'CRM / atendimento'; end if;
  v_fallback := agency_ops.infer_meeting_topic(p_client_id,p_chat_id,p_at);
  return coalesce(v_fallback,'Reunião / alinhamento');
end
$$;

create or replace function agency_ops.capture_meeting_agenda_message(
  p_db_id bigint,
  p_message_id text,
  p_chat_id text,
  p_chat_name text,
  p_sender_phone text,
  p_sender_name text,
  p_from_me boolean,
  p_text text,
  p_event_at timestamptz,
  p_received_at timestamptz
) returns void
language plpgsql
security definer
set search_path to 'agency_ops','pg_catalog','extensions'
as $$
declare
  v_text text := trim(coalesce(p_text,''));
  v_norm text;
  v_at timestamptz := coalesce(p_event_at,p_received_at,now());
  v_person text;
  v_client uuid;
  v_dt timestamptz;
  v_topic text;
  v_meet_url text;
  v_context boolean := false;
  v_recent_context boolean := false;
  v_is_proposal boolean := false;
  v_is_ack boolean := false;
  v_is_reschedule boolean := false;
  v_is_cancel boolean := false;
  v_existing bigint;
  v_prop record;
  m text[];
  v_hour int;
  v_min int;
  v_target_date date;
begin
  if p_chat_id is null or length(v_text) < 2 then return; end if;
  if coalesce(p_chat_name,'') ~* '^\[OPS\]' then return; end if;

  v_norm := lower(unaccent(v_text));
  v_person := agency_ops.resolve_team_person_from_whatsapp(p_sender_phone,p_sender_name);
  select reg.client_id into v_client from agency_ops.whatsapp_chat_registry reg where reg.chat_id=p_chat_id limit 1;
  v_meet_url := agency_ops.extract_google_meet_url(v_text);
  v_dt := agency_ops.extract_agenda_meeting_datetime(v_text,v_at);

  v_context := v_norm ~ '(reuniao|videochamada|google meet|meet\.google\.com|call([[:space:]]+de)?[[:space:]]+(ap|pp|int)|alinhamento|briefing|formularios?|forms|produto.{0,18}persona|integracao|apresentacao)';
  if not v_context then
    select exists(
      select 1 from agency_ops.whatsapp_messages m0
      where m0.chat_id=p_chat_id and m0.id<>p_db_id
        and coalesce(m0.event_at,m0.received_at) between v_at-interval '3 hours' and v_at
        and lower(unaccent(coalesce(m0.text_body,'')||' '||coalesce(m0.caption,'')))
          ~ '(reuniao|videochamada|google meet|meet\.google\.com|call([[:space:]]+de)?[[:space:]]+(ap|pp|int)|alinhamento|briefing|formularios?|forms|produto.{0,18}persona|integracao|apresentacao)'
    ) into v_recent_context;
  end if;
  if not v_context and not v_recent_context then return; end if;

  v_is_reschedule := v_norm ~ '(remarcar|remarc|reagendar|reagend|mudar (essa |a )?reuniao|outro horario|outro dia|preciso mudar)';
  v_is_cancel := v_norm ~ '(cancelar (a |essa )?reuniao|reuniao (foi |esta )?cancelad|nao teremos (a |essa )?reuniao|nao vai rolar (a |essa )?reuniao)';
  v_is_ack := v_norm ~ '(^|[^a-z])(sim|combinado|fechado|pode ser|confirmado|confirmada|perfeito|beleza|show|ok|marcado|marcada)([^a-z]|$)';
  v_is_proposal := v_dt is not null and (
    v_person is null or v_norm ~ '(podemos|pode ser|consegue|conseguimos|disponibilidade|que tal|qual (desses )?horarios?|teria disponibilidade|poderia|vamos fazer|seria as|remarcar|reagendar)'
  );

  if v_is_reschedule then
    select e.id into v_existing from agency_ops.meeting_agenda_events e
    where e.chat_id=p_chat_id and e.status='SCHEDULED'
      and e.scheduled_for >= v_at-interval '6 hours' and (v_person is null or e.person=v_person)
    order by e.scheduled_for asc limit 1;
    if v_existing is not null then
      update agency_ops.meeting_agenda_events set status='SUPERSEDED',
        evidence=coalesce(evidence,'{}'::jsonb)||jsonb_build_object('superseded_by_message_id',p_message_id,'superseded_by_db_id',p_db_id,'superseded_at',v_at),updated_at=now()
      where id=v_existing;
    end if;
  end if;

  if v_is_cancel and v_dt is null then
    select e.id into v_existing from agency_ops.meeting_agenda_events e
    where e.chat_id=p_chat_id and e.status='SCHEDULED'
      and e.scheduled_for >= v_at-interval '6 hours' and (v_person is null or e.person=v_person)
    order by e.scheduled_for asc limit 1;
    if v_existing is not null then
      update agency_ops.meeting_agenda_events set status='CANCELLED',
        evidence=coalesce(evidence,'{}'::jsonb)||jsonb_build_object('cancel_message_id',p_message_id,'cancel_db_id',p_db_id,'cancelled_at',v_at),updated_at=now()
      where id=v_existing;
    end if;
    return;
  end if;

  if v_is_proposal then
    if v_dt < v_at-interval '8 hours' or v_dt > v_at+interval '180 days' then return; end if;
    update agency_ops.meeting_agenda_events set status='SUPERSEDED',updated_at=now()
    where chat_id=p_chat_id and status='PROPOSED' and scheduled_for >= v_at-interval '1 day'
      and (v_person is null or person=v_person);
    insert into agency_ops.meeting_agenda_events(
      person,client_id,chat_id,chat_name,status,scheduled_for,topic,meet_url,source,source_record_id,
      proposal_message_id,confidence,evidence,created_at,updated_at
    ) values (
      v_person,v_client,p_chat_id,p_chat_name,'PROPOSED',v_dt,
      agency_ops.infer_agenda_meeting_topic(v_text,v_client,p_chat_id,v_at),v_meet_url,'WHATSAPP',p_db_id::text,p_db_id,
      case when v_person is not null and v_client is not null then 0.88 else 0.76 end,
      jsonb_build_object('proposal_message_id',p_message_id,'proposal_sender',p_sender_name,'proposal_at',v_at,'auto_detected',true),v_at,now()
    )
    on conflict (source,source_record_id) where source_record_id is not null
    do update set person=coalesce(excluded.person,agency_ops.meeting_agenda_events.person),
      client_id=coalesce(excluded.client_id,agency_ops.meeting_agenda_events.client_id),
      scheduled_for=excluded.scheduled_for,topic=coalesce(excluded.topic,agency_ops.meeting_agenda_events.topic),
      meet_url=coalesce(excluded.meet_url,agency_ops.meeting_agenda_events.meet_url),
      evidence=agency_ops.meeting_agenda_events.evidence||excluded.evidence,updated_at=now();
    return;
  end if;

  if v_person is not null and v_dt is not null and (v_context or v_meet_url is not null) then
    if v_dt < v_at-interval '8 hours' or v_dt > v_at+interval '180 days' then return; end if;
    v_topic := agency_ops.infer_agenda_meeting_topic(v_text,v_client,p_chat_id,v_at);
    select e.id into v_existing from agency_ops.meeting_agenda_events e
    where e.chat_id=p_chat_id and e.person=v_person and e.status='SCHEDULED'
      and e.scheduled_for between v_dt-interval '15 minutes' and v_dt+interval '15 minutes'
    order by e.updated_at desc limit 1;
    if v_existing is not null then
      update agency_ops.meeting_agenda_events set client_id=coalesce(client_id,v_client),chat_name=coalesce(chat_name,p_chat_name),
        topic=coalesce(topic,v_topic),meet_url=coalesce(meet_url,v_meet_url),
        confidence=greatest(coalesce(confidence,0),case when v_client is not null then 0.96 else 0.90 end),
        evidence=coalesce(evidence,'{}'::jsonb)||jsonb_build_object('last_confirmation_message_id',p_message_id,'last_confirmation_db_id',p_db_id,'last_confirmation_at',v_at),updated_at=now()
      where id=v_existing;
    else
      insert into agency_ops.meeting_agenda_events(
        person,client_id,chat_id,chat_name,status,scheduled_for,topic,meet_url,source,source_record_id,
        confirmation_message_id,confidence,evidence,created_at,updated_at
      ) values (
        v_person,v_client,p_chat_id,p_chat_name,'SCHEDULED',v_dt,v_topic,v_meet_url,'WHATSAPP',p_db_id::text,p_db_id,
        case when v_client is not null then 0.96 else 0.90 end,
        jsonb_build_object('confirmation_message_id',p_message_id,'confirmation_sender',p_sender_name,'confirmation_at',v_at,'auto_detected',true),v_at,now()
      ) on conflict (source,source_record_id) where source_record_id is not null do nothing;
    end if;
    return;
  end if;

  if v_is_ack then
    select e.* into v_prop from agency_ops.meeting_agenda_events e
    where e.chat_id=p_chat_id and e.status='PROPOSED'
      and e.created_at between v_at-interval '36 hours' and v_at+interval '5 minutes'
      and ((v_person is null and e.person is not null) or (v_person is not null and (e.person is null or e.person=v_person)))
    order by e.created_at desc,e.id desc limit 1;
    if v_prop.id is null then return; end if;

    if v_dt is null then
      m := regexp_match(v_norm, '(^|[^0-9])([0-2]?[0-9])(?::([0-5][0-9])|[[:space:]]*h(?:oras?|rs?)?)([^0-9]|$)');
      if m is not null then
        v_hour := m[2]::int; v_min := coalesce(nullif(m[3],''),'0')::int;
        v_target_date := (v_prop.scheduled_for at time zone 'America/Sao_Paulo')::date;
        v_dt := make_timestamptz(extract(year from v_target_date)::int,extract(month from v_target_date)::int,extract(day from v_target_date)::int,v_hour,v_min,0,'America/Sao_Paulo');
      end if;
    end if;
    if coalesce(v_prop.person,v_person) is null then return; end if;
    update agency_ops.meeting_agenda_events set status='SCHEDULED',person=coalesce(v_prop.person,v_person),
      client_id=coalesce(v_prop.client_id,v_client),scheduled_for=coalesce(v_dt,v_prop.scheduled_for),
      topic=coalesce(v_prop.topic,agency_ops.infer_agenda_meeting_topic(v_text,v_client,p_chat_id,v_at)),
      meet_url=coalesce(v_prop.meet_url,v_meet_url),confirmation_message_id=p_db_id,
      confidence=greatest(coalesce(v_prop.confidence,0),case when v_client is not null then 0.94 else 0.88 end),
      evidence=coalesce(v_prop.evidence,'{}'::jsonb)||jsonb_build_object('confirmation_message_id',p_message_id,'confirmation_sender',p_sender_name,'confirmation_at',v_at),updated_at=now()
    where id=v_prop.id;
  end if;
end
$$;

create or replace function agency_ops.capture_meeting_agenda_from_whatsapp()
returns trigger
language plpgsql
security definer
set search_path to 'agency_ops','pg_catalog','extensions'
as $$
declare
  v_text text := trim(coalesce(new.text_body,'')||' '||coalesce(new.caption,''));
  v_norm text := lower(unaccent(trim(coalesce(new.text_body,'')||' '||coalesce(new.caption,''))));
  v_has_client boolean := false;
begin
  if coalesce(new.is_group,false) is not true then return new; end if;
  select exists(select 1 from agency_ops.whatsapp_chat_registry reg where reg.chat_id=new.chat_id) into v_has_client;
  if not v_has_client and (
    v_norm ~ '(a partir de agora.{0,80}(padronizar|padrao)|exemplos?:|call de ap[[:space:]]*=|call de pp[[:space:]]*=|call de int[[:space:]]*=)'
    or (length(v_text) > 500 and v_norm ~ '(padroniz|manual|exemplo|vamos usar esse padrao)')
  ) then return new; end if;
  perform agency_ops.capture_meeting_agenda_message(new.id,new.message_id,new.chat_id,new.chat_name,new.sender_phone,new.sender_name,new.from_me,v_text,new.event_at,new.received_at);
  return new;
end
$$;

drop trigger if exists trg_capture_meeting_agenda on agency_ops.whatsapp_messages;
create trigger trg_capture_meeting_agenda
after insert or update of text_body,caption,chat_id,chat_name,sender_phone,sender_name,event_at,received_at
on agency_ops.whatsapp_messages
for each row execute function agency_ops.capture_meeting_agenda_from_whatsapp();

insert into agency_ops.dashboard_view_permissions(view_key,scope_type,scope_value,allowed,note)
select 'agenda','ROLE',role_name,true,'agenda pessoal automatica; Adler recebe consolidado'
from (values ('MGMT'),('AI'),('CS'),('GT'),('DESIGN'),('COMMERCIAL')) roles(role_name)
on conflict (view_key,scope_type,scope_value)
do update set allowed=excluded.allowed,note=excluded.note,updated_at=now();

create or replace function public.agenda_for_current_user(
  p_from timestamptz default now()-interval '90 days',
  p_to timestamptz default now()+interval '180 days'
) returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public','agency_ops'
as $$
declare
  v_uid uuid := auth.uid();
  v_person text;
  v_role text;
  v_views text[];
  v_all boolean := false;
  v_from timestamptz := coalesce(p_from,now()-interval '90 days');
  v_to timestamptz := coalesce(p_to,now()+interval '180 days');
  v_events jsonb;
  v_people jsonb;
begin
  if v_uid is null then raise exception 'unauthorized' using errcode='42501'; end if;
  select nullif(trim(up.collaborator_person),'') into v_person from agency_ops.user_preferences up where up.user_key=v_uid::text limit 1;
  if v_person is null then raise exception 'profile_not_linked' using errcode='42501'; end if;
  select tr.role into v_role from agency_ops.team_roster tr where tr.person=v_person and coalesce(tr.is_former,false)=false limit 1;
  if v_role is null then raise exception 'profile_not_active' using errcode='42501'; end if;
  v_views := agency_ops.dashboard_allowed_views(v_person,v_role);
  if not ('agenda'=any(coalesce(v_views,'{}'::text[]))) then raise exception 'forbidden' using errcode='42501'; end if;
  v_all := v_person='Adler Furtado';
  if v_from > v_to then declare v_swap timestamptz := v_from; begin v_from:=v_to; v_to:=v_swap; end; end if;
  if v_to-v_from > interval '370 days' then v_to:=v_from+interval '370 days'; end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id',q.id,'person',q.person,'client_id',q.client_id,'client_name',q.client_name,'client_lifecycle',q.client_lifecycle,
    'scheduled_for',q.scheduled_for,'duration_minutes',q.duration_minutes,'topic',q.topic,'meet_url',q.meet_url,'source',q.source,
    'confidence',q.confidence,'effective_status',q.effective_status,'actual_started_at',q.actual_started_at,'actual_ended_at',q.actual_ended_at,
    'presence_source',q.presence_source,'transcript_available',q.transcript_available,'context_available',q.context_available
  ) order by q.scheduled_for),'[]'::jsonb) into v_events
  from (
    select e.id,e.person,e.client_id,c.display_name as client_name,c.lifecycle as client_lifecycle,e.scheduled_for,e.duration_minutes,
      coalesce(nullif(e.topic,''),nullif(mp.topic,''),'Reunião / alinhamento') as topic,coalesce(e.meet_url,mp.meet_url) as meet_url,e.source,e.confidence,
      case
        when mp.id is not null and mp.ended_at is null and mp.status='IN_PROGRESS' and mp.started_at between now()-interval '3 hours' and now()+interval '30 minutes' then 'IN_PROGRESS'
        when mp.id is not null and (mp.ended_at is not null or mp.transcript_id is not null or mp.status in ('CONTEXT_AVAILABLE','COMPLETED')) then 'COMPLETED'
        when e.scheduled_for < now()-interval '3 hours' then 'NO_EVIDENCE'
        else 'SCHEDULED'
      end as effective_status,
      mp.started_at as actual_started_at,mp.ended_at as actual_ended_at,mp.source as presence_source,
      (mp.transcript_id is not null) as transcript_available,
      (mp.summary is not null or mp.transcript_id is not null or mp.status='CONTEXT_AVAILABLE') as context_available
    from agency_ops.meeting_agenda_events e
    left join agency_ops.clients c on c.id=e.client_id
    left join lateral (
      select p.* from agency_ops.meeting_presence_events p
      where p.person=e.person and p.status<>'CANCELLED'
        and p.started_at between e.scheduled_for-interval '4 hours' and e.scheduled_for+interval '4 hours'
      order by case when e.client_id is not null and p.client_id=e.client_id then 0 when e.client_id is null or p.client_id is null then 1 else 2 end,
        abs(extract(epoch from (p.started_at-e.scheduled_for))) limit 1
    ) mp on true
    where e.status='SCHEDULED' and e.scheduled_for between v_from and v_to and (v_all or e.person=v_person)
    order by e.scheduled_for limit 1200
  ) q;

  select coalesce(jsonb_agg(jsonb_build_object('person',x.person,'role',x.role) order by x.person),'[]'::jsonb) into v_people
  from (select tr.person,tr.role from agency_ops.team_roster tr where coalesce(tr.is_former,false)=false and (v_all or tr.person=v_person)) x;

  return jsonb_build_object('ok',true,'profile',jsonb_build_object('person',v_person,'role',v_role,'can_view_all',v_all),
    'scope',case when v_all then 'ALL_TEAM' else 'SELF_ONLY' end,'events',v_events,'people',v_people,
    'range',jsonb_build_object('from',v_from,'to',v_to),'generated_at',now());
end
$$;

revoke all on function public.agenda_for_current_user(timestamptz,timestamptz) from public;
revoke all on function public.agenda_for_current_user(timestamptz,timestamptz) from anon;
grant execute on function public.agenda_for_current_user(timestamptz,timestamptz) to authenticated;
