-- Radar de reuniões: detecta início por evidência operacional (WhatsApp/Meet)
-- e enriquece depois com cliente/assunto/resumo vindo do Donnah.

create table if not exists agency_ops.meeting_presence_events (
  id bigint generated by default as identity primary key,
  person text not null,
  client_id uuid references agency_ops.clients(id),
  status text not null default 'DETECTED'
    check (status in ('DETECTED','IN_PROGRESS','CONTEXT_AVAILABLE','COMPLETED','CANCELLED')),
  started_at timestamptz not null,
  ended_at timestamptz,
  meet_url text,
  meeting_code text,
  source text not null,
  source_record_id text,
  confidence numeric,
  topic text,
  summary text,
  transcript_id bigint references agency_ops.meeting_transcripts(id),
  evidence jsonb not null default '{}'::jsonb,
  start_notified_at timestamptz,
  context_notified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source, source_record_id)
);

create index if not exists meeting_presence_events_person_started_idx
  on agency_ops.meeting_presence_events(person, started_at desc);
create index if not exists meeting_presence_events_client_started_idx
  on agency_ops.meeting_presence_events(client_id, started_at desc)
  where client_id is not null;
create index if not exists meeting_presence_events_meeting_code_idx
  on agency_ops.meeting_presence_events(meeting_code)
  where meeting_code is not null;

create or replace function agency_ops.resolve_team_person_from_whatsapp(
  p_phone text,
  p_name text
) returns text
language plpgsql
stable
security definer
set search_path to 'agency_ops','public','extensions'
as $$
declare
  v_phone text := regexp_replace(coalesce(p_phone,''),'\D','','g');
  v_name text := agency_ops.normalize_sender_identity(coalesce(p_name,''));
  v_person text;
begin
  if v_phone <> '' then
    select ti.person into v_person
    from agency_ops.team_identities ti
    where ti.verified
      and ti.system='WHATSAPP_PHONE'
      and regexp_replace(coalesce(ti.external_id,''),'\D','','g')=v_phone
    order by ti.updated_at desc
    limit 1;
    if v_person is not null then return v_person; end if;
  end if;

  if v_name <> '' then
    select ti.person into v_person
    from agency_ops.team_identities ti
    where ti.verified
      and ti.system='WHATSAPP_NAME'
      and agency_ops.normalize_sender_identity(coalesce(ti.external_id,ti.external_name,''))=v_name
    order by case when agency_ops.normalize_sender_identity(coalesce(ti.external_id,''))=v_name then 0 else 1 end,
             ti.updated_at desc
    limit 1;
    if v_person is not null then return v_person; end if;

    select ti.person into v_person
    from agency_ops.team_identities ti
    where ti.verified
      and agency_ops.normalize_sender_identity(coalesce(ti.external_name,''))=v_name
    order by ti.updated_at desc
    limit 1;
  end if;

  return v_person;
end
$$;

create or replace function agency_ops.infer_meeting_topic(
  p_client_id uuid,
  p_chat_id text,
  p_at timestamptz
) returns text
language plpgsql
stable
security definer
set search_path to 'agency_ops','public','extensions'
as $$
declare
  v_stage text;
  v_text text;
begin
  if p_client_id is not null then
    select oc.current_stage into v_stage
    from agency_ops.onboarding_cases oc
    where oc.client_id=p_client_id and oc.status='OPEN'
    order by oc.updated_at desc,oc.id desc
    limit 1;

    if v_stage='INTEGRATION_MEETING' then return 'Reunião de integração com GT'; end if;
    if v_stage='INTRO_MEETING' then return '1ª reunião de apresentação'; end if;
    if v_stage='PRODUCT_PERSONA_MEETING' then return 'Reunião de Produto e Persona'; end if;
  end if;

  if p_chat_id is not null then
    select lower(extensions.unaccent(string_agg(coalesce(m.text_body,'')||' '||coalesce(m.caption,''),' ' order by coalesce(m.event_at,m.received_at))))
      into v_text
    from agency_ops.whatsapp_messages m
    where m.chat_id=p_chat_id
      and coalesce(m.event_at,m.received_at) between p_at-interval '45 minutes' and p_at+interval '2 minutes';

    if v_text ~ '(integracao|reuniao de integracao)' then return 'Reunião de integração'; end if;
    if v_text ~ '(produto.{0,15}persona|persona.{0,15}produto)' then return 'Produto e Persona'; end if;
    if v_text ~ '(apresentacao|primeira reuniao|1a reuniao)' then return 'Apresentação / onboarding'; end if;
    if v_text ~ '(performance|resultado|campanha|lead|otimiz)' then return 'Performance / campanhas'; end if;
    if v_text ~ '(criativ|design|video|roteiro)' then return 'Criativos / conteúdo'; end if;
    if v_text ~ '(crm|atendimento|follow.?up|roleta)' then return 'CRM / atendimento'; end if;
    if v_text ~ '(financeiro|saldo|pagamento|boleto)' then return 'Financeiro'; end if;
  end if;

  return null;
end
$$;

create or replace function agency_ops.capture_meeting_presence_from_whatsapp()
returns trigger
language plpgsql
security definer
set search_path to 'agency_ops','public','extensions'
as $$
declare
  v_text text;
  v_url text;
  v_code text;
  v_person text;
  v_client uuid;
  v_client_name text;
  v_topic text;
  v_at timestamptz;
  v_explicit_dt timestamptz;
  v_existing bigint;
  v_event_id bigint;
  v_conf numeric := 0.82;
  v_notification bigint;
begin
  if coalesce(new.is_group,false) is not true then return new; end if;

  v_text := trim(coalesce(new.text_body,'')||' '||coalesce(new.caption,''));
  v_url := agency_ops.extract_google_meet_url(v_text);
  if v_url is null then return new; end if;

  v_person := agency_ops.resolve_team_person_from_whatsapp(new.sender_phone,new.sender_name);
  if v_person is null then return new; end if;

  v_at := coalesce(new.event_at,new.received_at,now());
  v_explicit_dt := agency_ops.extract_ptbr_meeting_datetime(v_text,v_at);

  if v_explicit_dt is not null and abs(extract(epoch from (v_explicit_dt-v_at))) > 45*60 then
    return new;
  end if;

  v_code := lower((regexp_match(v_url,'meet\.google\.com/([a-z]{3}-[a-z]{4}-[a-z]{3})','i'))[1]);

  select reg.client_id into v_client
  from agency_ops.whatsapp_chat_registry reg
  where reg.chat_id=new.chat_id
  limit 1;

  if v_client is not null then
    select c.display_name into v_client_name from agency_ops.clients c where c.id=v_client;
    v_conf := 0.91;
  end if;

  v_topic := agency_ops.infer_meeting_topic(v_client,new.chat_id,v_at);
  if v_topic is not null then v_conf := least(0.98,v_conf+0.04); end if;

  select e.id into v_existing
  from agency_ops.meeting_presence_events e
  where e.person=v_person
    and e.started_at between v_at-interval '3 hours' and v_at+interval '10 minutes'
    and (
      (v_code is not null and e.meeting_code=v_code)
      or (v_code is null and e.meet_url=v_url)
    )
    and e.status <> 'CANCELLED'
  order by e.started_at desc
  limit 1;

  if v_existing is not null then
    update agency_ops.meeting_presence_events
       set client_id=coalesce(client_id,v_client),
           topic=coalesce(topic,v_topic),
           meet_url=coalesce(meet_url,v_url),
           evidence=coalesce(evidence,'{}'::jsonb)||jsonb_build_object(
             'last_whatsapp_message_id',new.message_id,
             'last_whatsapp_message_db_id',new.id,
             'last_whatsapp_at',v_at,
             'chat_id',new.chat_id,
             'chat_name',new.chat_name
           ),
           updated_at=now()
     where id=v_existing;
    return new;
  end if;

  insert into agency_ops.meeting_presence_events(
    person,client_id,status,started_at,meet_url,meeting_code,source,source_record_id,
    confidence,topic,evidence
  ) values (
    v_person,v_client,'IN_PROGRESS',v_at,v_url,v_code,'WHATSAPP_MEET',new.id::text,
    v_conf,v_topic,jsonb_build_object(
      'message_id',new.message_id,
      'chat_id',new.chat_id,
      'chat_name',new.chat_name,
      'sender_name',new.sender_name,
      'sender_phone',new.sender_phone,
      'explicit_schedule',v_explicit_dt,
      'evidence_type','TEAM_SENT_GOOGLE_MEET_LINK_NEAR_START'
    )
  ) returning id into v_event_id;

  v_notification := agency_ops.enqueue_notification(
    'meeting-radar:start:'||v_event_id::text,
    v_client,
    null,
    'MEETING_RADAR',
    'MEETING_STARTED',
    'INFO',
    '🔵 REUNIÃO INICIADA',
    'Colaborador: '||v_person||E'\n'
      ||'Cliente: '||coalesce(v_client_name,'Não identificado / reunião interna')||E'\n'
      ||'Assunto: '||coalesce(v_topic,'Ainda não identificado')||E'\n'
      ||'Fonte: WhatsApp + Google Meet'||E'\n'
      ||'Donnah: aguardando contexto/transcrição.',
    'OPS_INTERNAL',
    jsonb_build_object(
      'meeting_presence_event_id',v_event_id,
      'person',v_person,
      'client_id',v_client,
      'meet_url',v_url,
      'meeting_code',v_code,
      'confidence',v_conf,
      'source','WHATSAPP_MEET'
    )
  );

  if v_notification is not null then
    update agency_ops.meeting_presence_events set start_notified_at=now(),updated_at=now() where id=v_event_id;
  end if;

  return new;
end
$$;

drop trigger if exists trg_capture_meeting_presence on agency_ops.whatsapp_messages;
create trigger trg_capture_meeting_presence
after insert on agency_ops.whatsapp_messages
for each row execute function agency_ops.capture_meeting_presence_from_whatsapp();

create or replace function agency_ops.enrich_meeting_presence_from_transcript()
returns trigger
language plpgsql
security definer
set search_path to 'agency_ops','public','extensions'
as $$
declare
  v_person text;
  v_started timestamptz;
  v_topic text;
  v_summary text;
  v_event agency_ops.meeting_presence_events%rowtype;
  v_event_id bigint;
  v_client uuid;
  v_client_name text;
  v_notification bigint;
  v_is_new boolean := false;
begin
  if new.processed_at is null then return new; end if;
  if tg_op='UPDATE' and old.processed_at is not null
     and old.client_id is not distinct from new.client_id
     and coalesce(old.metadata->>'tipo_reuniao','')=coalesce(new.metadata->>'tipo_reuniao','')
     and coalesce(old.summary,'')=coalesce(new.summary,'') then
    return new;
  end if;

  v_person := nullif(new.metadata->>'mcp_owner_person','');
  if v_person is null then return new; end if;

  v_started := coalesce(new.meeting_started_at,new.source_created_at,new.ingested_at,new.created_at,now());
  v_topic := nullif(new.metadata->>'tipo_reuniao','');
  v_summary := coalesce(nullif(new.metadata->>'donnah_summary',''),nullif(new.summary,''));

  select e.* into v_event
  from agency_ops.meeting_presence_events e
  where e.person=v_person
    and e.status<>'CANCELLED'
    and e.started_at between v_started-interval '90 minutes' and v_started+interval '3 hours'
  order by
    case when new.meeting_code is not null and e.meeting_code=new.meeting_code then 0
         when new.client_id is not null and e.client_id=new.client_id then 1
         else 2 end,
    abs(extract(epoch from (e.started_at-v_started))) asc
  limit 1;

  if v_event.id is null then
    insert into agency_ops.meeting_presence_events(
      person,client_id,status,started_at,meeting_code,source,source_record_id,
      confidence,topic,summary,transcript_id,evidence
    ) values (
      v_person,new.client_id,'CONTEXT_AVAILABLE',v_started,new.meeting_code,'DONNAH_TRANSCRIPT',new.id::text,
      case when new.client_id is not null then 0.88 else 0.72 end,
      v_topic,v_summary,new.id,
      jsonb_build_object(
        'donnah_feed_id',new.metadata->>'mcp_feed_id',
        'donnah_document_id',new.metadata->>'mcp_document_id',
        'participants',coalesce(new.participants,'[]'::jsonb),
        'match_status',new.match_status,
        'evidence_type','DONNAH_TRANSCRIPT_AVAILABLE'
      )
    ) returning id into v_event_id;
    v_is_new := true;
  else
    v_event_id := v_event.id;
    update agency_ops.meeting_presence_events
       set client_id=coalesce(client_id,new.client_id),
           status=case when status='IN_PROGRESS' then 'CONTEXT_AVAILABLE' else status end,
           meeting_code=coalesce(meeting_code,new.meeting_code),
           topic=coalesce(v_topic,topic),
           summary=coalesce(v_summary,summary),
           transcript_id=new.id,
           confidence=greatest(coalesce(confidence,0),case when coalesce(client_id,new.client_id) is not null then 0.92 else 0.78 end),
           evidence=coalesce(evidence,'{}'::jsonb)||jsonb_build_object(
             'donnah_feed_id',new.metadata->>'mcp_feed_id',
             'donnah_document_id',new.metadata->>'mcp_document_id',
             'participants',coalesce(new.participants,'[]'::jsonb),
             'transcript_match_status',new.match_status,
             'transcript_client_id',new.client_id,
             'donnah_context_at',now()
           ),
           updated_at=now()
     where id=v_event_id;
  end if;

  select e.client_id,e.context_notified_at into v_client,v_event.context_notified_at
  from agency_ops.meeting_presence_events e where e.id=v_event_id;
  if v_client is not null then
    select c.display_name into v_client_name from agency_ops.clients c where c.id=v_client;
  end if;

  if v_is_new then
    v_notification := agency_ops.enqueue_notification(
      'meeting-radar:start-donnah:'||v_event_id::text,
      v_client,
      null,
      'MEETING_RADAR',
      'MEETING_DETECTED_DONNAH',
      'INFO',
      '🟣 REUNIÃO DETECTADA PELO DONNAH',
      'Colaborador: '||v_person||E'\n'
        ||'Cliente: '||coalesce(v_client_name,'Ainda não identificado')||E'\n'
        ||'Assunto: '||coalesce(v_topic,'Ainda não identificado')||E'\n'
        ||'Início estimado: '||to_char(v_started at time zone 'America/Sao_Paulo','DD/MM HH24:MI')||E'\n'
        ||'Observação: detectada quando o Donnah disponibilizou a transcrição.',
      'OPS_INTERNAL',
      jsonb_build_object('meeting_presence_event_id',v_event_id,'person',v_person,'transcript_id',new.id,'source','DONNAH_TRANSCRIPT')
    );
    if v_notification is not null then
      update agency_ops.meeting_presence_events set start_notified_at=coalesce(start_notified_at,now()),updated_at=now() where id=v_event_id;
    end if;
  end if;

  if v_event.context_notified_at is null
     and (v_client is not null or v_topic is not null or v_summary is not null) then
    v_notification := agency_ops.enqueue_notification(
      'meeting-radar:context:'||v_event_id::text,
      v_client,
      null,
      'MEETING_RADAR',
      'MEETING_CONTEXT_IDENTIFIED',
      'INFO',
      '🧠 CONTEXTO DA REUNIÃO',
      'Colaborador: '||v_person||E'\n'
        ||'Cliente: '||coalesce(v_client_name,'Não identificado')||E'\n'
        ||'Assunto: '||coalesce(v_topic,'Não classificado')||E'\n'
        ||case when v_summary is not null then 'Resumo: '||left(regexp_replace(v_summary,E'[\r\n]+',' ','g'),500) else 'Resumo: aguardando dados suficientes' end,
      'OPS_INTERNAL',
      jsonb_build_object(
        'meeting_presence_event_id',v_event_id,
        'person',v_person,
        'client_id',v_client,
        'topic',v_topic,
        'transcript_id',new.id,
        'source','DONNAH_TRANSCRIPT'
      )
    );
    if v_notification is not null then
      update agency_ops.meeting_presence_events set context_notified_at=now(),updated_at=now() where id=v_event_id;
    end if;
  end if;

  return new;
end
$$;

drop trigger if exists trg_enrich_meeting_presence_from_transcript on agency_ops.meeting_transcripts;
create trigger trg_enrich_meeting_presence_from_transcript
after insert or update of processed_at,client_id,summary,metadata on agency_ops.meeting_transcripts
for each row execute function agency_ops.enrich_meeting_presence_from_transcript();

comment on table agency_ops.meeting_presence_events is
'Radar operacional de reuniões. Início imediato quando há evidência de Meet no WhatsApp; contexto e cliente são enriquecidos depois pelo Donnah quando disponível.';