-- Radar gerencial: contexto consolidado e historico de execucoes.
-- Objetivo: gerar um digest para a gestao sem tratar task aberta como prova isolada.

create table if not exists agency_ops.manager_attention_digest_runs (
  id bigint generated by default as identity primary key,
  run_date date not null default ((now() at time zone 'America/Sao_Paulo')::date),
  slot text not null,
  status text not null default 'RUNNING' check (status in ('RUNNING','DONE','ERROR')),
  provider text,
  summary_text text,
  analysis jsonb not null default '{}'::jsonb,
  context_stats jsonb not null default '{}'::jsonb,
  notification_id bigint references agency_ops.notification_outbox(id),
  error text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (run_date, slot)
);

create index if not exists manager_attention_digest_runs_latest_idx
  on agency_ops.manager_attention_digest_runs(run_date desc, started_at desc);

alter table agency_ops.manager_attention_digest_runs enable row level security;
revoke all on agency_ops.manager_attention_digest_runs from anon, authenticated;

create or replace function agency_ops.manager_attention_digest_context(
  p_since timestamptz,
  p_limit integer default 30
) returns jsonb
language sql
stable
security definer
set search_path to 'agency_ops','public','extensions'
as $function$
with base as (
  select c.id,c.display_name,c.lifecycle,c.cs_owner,c.gt_owner,c.designer_owner,c.service,c.entrada
  from agency_ops.clients c
  where c.lifecycle in ('ACTIVE','ONBOARDING')
), signal_rows as (
  select cs.client_id, 100 as score, 'CONVERSATION_WAITING_AGENCY'::text as reason
  from agency_ops.conversation_state cs
  join base b on b.id=cs.client_id
  where cs.waiting_for_agency is true

  union all
  select cs.client_id, 28, 'CONVERSATION_WAITING_CLIENT'
  from agency_ops.conversation_state cs
  join base b on b.id=cs.client_id
  where cs.waiting_for_client is true

  union all
  select wi.client_id,
         case when wi.due_at is not null and wi.due_at < now() then 92
              when wi.priority='CRITICAL' then 88
              when wi.priority='HIGH' then 76 else 52 end,
         'WORK_ITEM_ACTIVE'
  from agency_ops.work_items wi
  join base b on b.id=wi.client_id
  where wi.status in ('OPEN','IN_PROGRESS','WAITING','SNOOZED')
    and (
      wi.due_at is not null and wi.due_at <= now()+interval '1 day'
      or wi.updated_at >= p_since-interval '2 days'
      or wi.created_at >= p_since-interval '2 days'
    )

  union all
  select ct.client_id,
         case when (ct.due_date at time zone 'America/Sao_Paulo')::date < (now() at time zone 'America/Sao_Paulo')::date then 82
              when (ct.due_date at time zone 'America/Sao_Paulo')::date = (now() at time zone 'America/Sao_Paulo')::date then 66
              else 44 end,
         'CLICKUP_OPEN'
  from agency_ops.clickup_tasks ct
  join base b on b.id=ct.client_id
  where coalesce(ct.is_closed,false) is false
    and (
      ct.date_updated >= p_since-interval '2 days'
      or ct.due_date is not null and (ct.due_date at time zone 'America/Sao_Paulo')::date <= ((now() at time zone 'America/Sao_Paulo')::date + 1)
    )

  union all
  select cm.client_id,
         case when cm.due_at is not null and cm.due_at < now() then 94
              when cm.confirmed_by_human then 80 else 55 end,
         'COMMITMENT_OPEN'
  from agency_ops.commitments cm
  join base b on b.id=cm.client_id
  where cm.status in ('OPEN','IN_PROGRESS')
    and (
      cm.due_at is not null and cm.due_at <= now()+interval '2 days'
      or cm.updated_at >= p_since-interval '3 days'
      or cm.created_at >= p_since-interval '3 days'
    )

  union all
  select oa.client_id,
         case when oa.severity='CRITICAL' then 90 when oa.severity='HIGH' then 76 else 50 end,
         'OPERATIONAL_ALERT'
  from agency_ops.operational_alerts oa
  join base b on b.id=oa.client_id
  where oa.status='ACTIVE'
    and oa.type not in ('STALE_NOTION','META_BALANCE_LOW','META_BALANCE_ZERO','UNMATCHED_HIGH_RISK')
    and (oa.last_detected_at >= p_since-interval '2 days' or oa.first_detected_at >= p_since-interval '2 days')

  union all
  select oc.client_id,
         case when oc.onboarding_risk in ('CRITICAL','RED') then 88
              when oc.next_action_due is not null and oc.next_action_due < now() then 84
              when oc.onboarding_risk in ('ATTENTION','YELLOW') then 60 else 45 end,
         'ONBOARDING_OPEN'
  from agency_ops.onboarding_cases oc
  join base b on b.id=oc.client_id
  where oc.status='OPEN'
    and (
      oc.onboarding_risk in ('CRITICAL','RED','ATTENTION','YELLOW')
      or oc.next_action_due is not null and oc.next_action_due <= now()+interval '1 day'
      or oc.updated_at >= p_since-interval '1 day'
    )

  union all
  select reg.client_id, 88, 'RECENT_CLIENT_REQUEST_OR_COMPLAINT'
  from agency_ops.whatsapp_messages m
  join agency_ops.whatsapp_chat_registry reg on reg.chat_id=m.chat_id and reg.client_id is not null
  join base b on b.id=reg.client_id
  left join agency_ops.whatsapp_message_actor a on a.id=m.id
  where coalesce(m.event_at,m.received_at) >= p_since-interval '36 hours'
    and coalesce(a.da_equipe,false) is false
    and lower(extensions.unaccent(trim(coalesce(m.text_body,'')||' '||coalesce(m.caption,'')))) ~
      '(precis|podem|poderia|consegue|quero|ajust|alter|trocar|nao chega|nao entra|sem lead|sem leads|erro|problema|retorno|previs|quando|subir|campanh|criativ|formular|whats|resultado|investid|metrica|demora|atras|funcion|qualidade)'

  union all
  select reg.client_id, 72, 'RECENT_TEAM_COMMITMENT'
  from agency_ops.whatsapp_messages m
  join agency_ops.whatsapp_chat_registry reg on reg.chat_id=m.chat_id and reg.client_id is not null
  join base b on b.id=reg.client_id
  left join agency_ops.whatsapp_message_actor a on a.id=m.id
  where coalesce(m.event_at,m.received_at) >= p_since-interval '36 hours'
    and coalesce(a.da_equipe,false) is true
    and lower(extensions.unaccent(trim(coalesce(m.text_body,'')||' '||coalesce(m.caption,'')))) ~
      '(vou |vamos |iremos |irei |podemos enviar|assim que|solicitei|repassarei|vou pedir|irei solicitar|estamos resolvendo|faremos|ajustaremos|vamos ajustar|vamos subir|irei trazer|vamos trazer|vou enviar|iremos enviar)'
), candidates as (
  select s.client_id,max(s.score) as score,array_agg(distinct s.reason order by s.reason) as reasons
  from signal_rows s
  where s.client_id is not null
  group by s.client_id
  order by max(s.score) desc,s.client_id
  limit greatest(1,least(coalesce(p_limit,30),50))
), enriched as (
  select
    b.id as client_id,
    b.display_name,
    b.lifecycle,
    b.cs_owner,
    b.gt_owner,
    b.designer_owner,
    b.service,
    b.entrada,
    c.score,
    c.reasons,
    coalesce((
      select jsonb_agg(to_jsonb(msg) order by msg.event_at)
      from (
        select *
        from (
          select
            coalesce(m.event_at,m.received_at) as event_at,
            m.id as message_db_id,
            m.message_id,
            m.chat_id,
            m.chat_name,
            coalesce(nullif(m.sender_name,''),a.pessoa,'Não identificado') as sender_name,
            coalesce(a.papel,'') as sender_role,
            coalesce(a.da_equipe,false) as is_team,
            m.message_type,
            left(trim(coalesce(m.text_body,'')||case when m.caption is not null then ' '||m.caption else '' end),1400) as body
          from agency_ops.whatsapp_messages m
          join agency_ops.whatsapp_chat_registry reg on reg.chat_id=m.chat_id and reg.client_id=b.id
          left join agency_ops.whatsapp_message_actor a on a.id=m.id
          where coalesce(m.event_at,m.received_at) >= p_since-interval '2 days'
            and coalesce(m.is_group,false) is true
          order by coalesce(m.event_at,m.received_at) desc
          limit 28
        ) recent_desc
        order by event_at asc
      ) msg
    ),'[]'::jsonb) as whatsapp_messages,
    coalesce((
      select jsonb_agg(to_jsonb(w) order by w.updated_at desc)
      from (
        select wi.id,wi.title,wi.status,wi.priority,wi.target_role,wi.target_person,wi.due_at,
               wi.snoozed_until,wi.waiting_reason,wi.waiting_since,wi.source,wi.created_at,wi.updated_at,
               left(coalesce(wi.description,''),1200) as description
        from agency_ops.work_items wi
        where wi.client_id=b.id and wi.status in ('OPEN','IN_PROGRESS','WAITING','SNOOZED')
        order by coalesce(wi.due_at,wi.updated_at) desc
        limit 12
      ) w
    ),'[]'::jsonb) as work_items,
    coalesce((
      select jsonb_agg(to_jsonb(t) order by t.date_updated desc)
      from (
        select ct.task_id,ct.name,ct.status,ct.due_date,ct.assignee_names,ct.date_created,ct.date_updated,ct.url
        from agency_ops.clickup_tasks ct
        where ct.client_id=b.id and coalesce(ct.is_closed,false) is false
        order by ct.date_updated desc
        limit 12
      ) t
    ),'[]'::jsonb) as clickup_tasks,
    coalesce((
      select jsonb_agg(to_jsonb(cm) order by cm.updated_at desc)
      from (
        select x.id,x.descricao,x.owner,x.due_at,x.status,x.task_id,x.evidencia,x.confirmed_by_human,x.created_at,x.updated_at
        from agency_ops.commitments x
        where x.client_id=b.id and x.status in ('OPEN','IN_PROGRESS')
        order by x.updated_at desc
        limit 10
      ) cm
    ),'[]'::jsonb) as commitments,
    coalesce((
      select jsonb_agg(to_jsonb(al) order by al.last_detected_at desc)
      from (
        select oa.id,oa.type,oa.severity,oa.title,oa.description,oa.next_action,oa.owner,oa.first_detected_at,oa.last_detected_at
        from agency_ops.operational_alerts oa
        where oa.client_id=b.id and oa.status='ACTIVE'
          and oa.type not in ('STALE_NOTION','META_BALANCE_LOW','META_BALANCE_ZERO','UNMATCHED_HIGH_RISK')
        order by oa.last_detected_at desc
        limit 10
      ) al
    ),'[]'::jsonb) as alerts,
    coalesce((
      select jsonb_agg(to_jsonb(cs) order by cs.updated_at desc)
      from (
        select s.chat_id,s.last_client_message_at,s.last_team_message_at,s.waiting_for_agency,s.waiting_since,
               s.waiting_for_client,s.open_question,s.conversation_status,s.sla_level,s.last_summary,
               s.last_actor,s.last_message_requires_response,s.classification_basis,s.updated_at
        from agency_ops.conversation_state s
        where s.client_id=b.id
        order by s.updated_at desc
        limit 6
      ) cs
    ),'[]'::jsonb) as conversation_states,
    coalesce((
      select jsonb_build_object(
        'case',to_jsonb(oc),
        'stages',coalesce((
          select jsonb_agg(to_jsonb(st) order by st.id)
          from (
            select os.stage_code,os.status,os.started_at,os.completed_at,os.due_at,os.blocked_type,os.notes
            from agency_ops.onboarding_stages os
            where os.case_id=oc.id and os.status not in ('DONE','SKIPPED')
            order by os.id
          ) st
        ),'[]'::jsonb)
      )
      from (
        select x.id,x.status,x.current_stage,x.onboarding_risk,x.blocked_by,x.next_action,x.next_action_due,
               x.creative_input_ready_at,x.creative_sla_started_at,x.creative_due_at,x.updated_at
        from agency_ops.onboarding_cases x
        where x.client_id=b.id and x.status='OPEN'
        order by x.updated_at desc
        limit 1
      ) oc
    ),'{}'::jsonb) as onboarding
  from candidates c
  join base b on b.id=c.client_id
)
select jsonb_build_object(
  'generated_at',now(),
  'local_time',to_char(now() at time zone 'America/Sao_Paulo','YYYY-MM-DD HH24:MI:SS'),
  'since',p_since,
  'candidate_count',(select count(*) from candidates),
  'clients',coalesce(jsonb_agg(to_jsonb(e) order by e.score desc,e.display_name),'[]'::jsonb)
)
from enriched e;
$function$;

revoke all on function agency_ops.manager_attention_digest_context(timestamptz,integer) from public, anon, authenticated;
grant execute on function agency_ops.manager_attention_digest_context(timestamptz,integer) to service_role;
