alter table agency_ops.generated_tasks
  add column if not exists grounding_score numeric(5,4),
  add column if not exists grounding_reason text,
  add column if not exists source_excerpt_hash text,
  add column if not exists validation_version text;

create table if not exists agency_ops.system_review_events (
  id bigint generated by default as identity primary key,
  source_event_id bigint not null references agency_ops.task_generation_events(id) on delete cascade,
  client_id uuid,
  chat_id text,
  proposed_title text not null,
  proposed_title_norm text not null,
  proposed_description text,
  reason text not null,
  validation_version text not null,
  source_excerpt_hash text,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'PENDING'
    check (status in ('PENDING', 'RESOLVED', 'IGNORED')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create unique index if not exists system_review_events_event_reason_title_uidx
  on agency_ops.system_review_events (source_event_id, reason, proposed_title_norm);
create index if not exists system_review_events_status_created_idx
  on agency_ops.system_review_events (status, created_at desc);

alter table agency_ops.system_review_events enable row level security;