-- Radar gerencial: historico das analises enviadas para a gestao.
-- A montagem do contexto e a verificacao cruzada ficam na Edge Function,
-- evitando transformar task aberta em prova isolada de pendencia.

create table if not exists agency_ops.manager_attention_digest_runs (
  id bigint generated by default as identity primary key,
  run_date date not null default ((now() at time zone 'America/Sao_Paulo')::date),
  slot text not null,
  status text not null default 'RUNNING' check (status in ('RUNNING','DONE','ERROR')),
  provider text,
  summary_text text,
  analysis jsonb not null default '{}'::jsonb,
  context_stats jsonb not null default '{}'::jsonb,
  notification_id bigint references agency_ops.notification_outbox(id),
  error text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (run_date, slot)
);

create index if not exists manager_attention_digest_runs_latest_idx
  on agency_ops.manager_attention_digest_runs(run_date desc, started_at desc);

alter table agency_ops.manager_attention_digest_runs enable row level security;
revoke all on agency_ops.manager_attention_digest_runs from anon, authenticated;
