create table if not exists agency_ops.task_engine_gt_clickup_map (
  gt_owner text primary key,
  clickup_user_id bigint not null unique,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into agency_ops.task_engine_gt_clickup_map (gt_owner, clickup_user_id, active, updated_at)
values
  ('Felipe Oliveira', 101700446, true, now()),
  ('Yuri Melo', 228200406, true, now()),
  ('Rodrigo Cavalheiro', 234082138, true, now())
on conflict (gt_owner) do update
set clickup_user_id = excluded.clickup_user_id,
    active = true,
    updated_at = now();

create table if not exists agency_ops.task_engine_gt_assignment_audit (
  id bigint generated by default as identity primary key,
  generated_task_id bigint not null references agency_ops.generated_tasks(id) on delete cascade,
  clickup_task_id text not null,
  client_id uuid,
  gt_owner text,
  clickup_user_id bigint,
  status text not null check (status in ('QUEUED','APPLIED','SKIPPED','FAILED')),
  detail text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists task_engine_gt_assignment_audit_task_idx
  on agency_ops.task_engine_gt_assignment_audit (generated_task_id, created_at desc);

alter table agency_ops.task_engine_gt_clickup_map enable row level security;
alter table agency_ops.task_engine_gt_assignment_audit enable row level security;
revoke all on agency_ops.task_engine_gt_clickup_map from anon, authenticated;
revoke all on agency_ops.task_engine_gt_assignment_audit from anon, authenticated;
grant select, insert, update on agency_ops.task_engine_gt_clickup_map to service_role;
grant select, insert, update on agency_ops.task_engine_gt_assignment_audit to service_role;

select vault.create_secret(
  encode(gen_random_bytes(32), 'hex'),
  'CLICKUP_GT_ASSIGNMENT_SECRET',
  'Internal secret for post-create GT routing in ClickUp'
)
where not exists (
  select 1 from vault.decrypted_secrets where name = 'CLICKUP_GT_ASSIGNMENT_SECRET'
);

create or replace function agency_ops.enqueue_clickup_gt_assignment()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, agency_ops, extensions, net
as $$
declare
  v_secret text;
begin
  if new.status <> 'ENVIADA'
     or new.clickup_task_id is null
     or lower(extensions.unaccent(coalesce(new.area, ''))) not in ('gestor de trafego', 'trafego pago') then
    return new;
  end if;

  v_secret := agency_ops.get_secret('CLICKUP_GT_ASSIGNMENT_SECRET');
  if v_secret is null then
    insert into agency_ops.task_engine_gt_assignment_audit (generated_task_id, clickup_task_id, client_id, status, detail)
    values (new.id, new.clickup_task_id, new.client_id, 'FAILED', 'missing_internal_secret');
    return new;
  end if;

  insert into agency_ops.task_engine_gt_assignment_audit (generated_task_id, clickup_task_id, client_id, status, detail)
  values (new.id, new.clickup_task_id, new.client_id, 'QUEUED', 'post_create_gt_routing');

  perform net.http_post(
    url := 'https://bfzdetibfcwihfkltbkp.supabase.co/functions/v1/agency-ops-clickup-gt-assignment',
    body := jsonb_build_object('generated_task_id', new.id),
    params := '{}'::jsonb,
    headers := jsonb_build_object('Content-Type', 'application/json', 'x-clickup-gt-routing-key', v_secret),
    timeout_milliseconds := 30000
  );
  return new;
end;
$$;

revoke all on function agency_ops.enqueue_clickup_gt_assignment() from public, anon, authenticated;
grant execute on function agency_ops.enqueue_clickup_gt_assignment() to service_role;

drop trigger if exists trg_generated_tasks_clickup_gt_assignment on agency_ops.generated_tasks;
create trigger trg_generated_tasks_clickup_gt_assignment
after update of status, clickup_task_id on agency_ops.generated_tasks
for each row
when (new.status = 'ENVIADA' and new.clickup_task_id is not null)
execute function agency_ops.enqueue_clickup_gt_assignment();