begin;

create table if not exists agency_ops.video_approved_references (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references agency_ops.clients(id) on delete cascade,
  product_name text,
  product_type text not null,
  market_tier text,
  aspect_ratio text not null default '9:16',
  drive_file_id text not null,
  drive_url text,
  source_folder_id text,
  duration_seconds numeric,
  width integer,
  height integer,
  fps numeric,
  reference_kind text not null default 'CLIENT_APPROVED',
  status text not null default 'ACTIVE',
  dna_features jsonb not null default '{}'::jsonb,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(drive_file_id)
);

create index if not exists video_approved_refs_lookup_idx
  on agency_ops.video_approved_references(client_id, product_type, status);
alter table agency_ops.video_approved_references enable row level security;

create table if not exists agency_ops.video_edit_dna_profiles (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references agency_ops.clients(id) on delete cascade,
  profile_key text not null,
  product_type text not null,
  market_tier text,
  aspect_ratio text not null default '9:16',
  version integer not null default 1,
  status text not null default 'ACTIVE',
  confidence numeric not null default 0.70,
  reference_count integer not null default 0,
  reference_ids uuid[] not null default '{}'::uuid[],
  dna jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists video_edit_dna_client_key_uq
  on agency_ops.video_edit_dna_profiles(client_id, profile_key, version)
  where client_id is not null;
create unique index if not exists video_edit_dna_global_key_uq
  on agency_ops.video_edit_dna_profiles(profile_key, version)
  where client_id is null;
create index if not exists video_edit_dna_lookup_idx
  on agency_ops.video_edit_dna_profiles(client_id, product_type, status, confidence desc);
alter table agency_ops.video_edit_dna_profiles enable row level security;

create table if not exists agency_ops.video_critic_runs (
  id bigint generated by default as identity primary key,
  job_id uuid not null references agency_ops.video_edit_jobs(id) on delete cascade,
  render_job_id uuid references agency_ops.video_v4_render_jobs(id) on delete cascade,
  output_id bigint references agency_ops.video_edit_job_outputs(id) on delete set null,
  attempt_no integer not null default 1,
  status text not null check (status in ('PASS','REVISE','FAIL')),
  critic_version text not null,
  score numeric not null default 0,
  checks jsonb not null default '[]'::jsonb,
  reference_ids uuid[] not null default '{}'::uuid[],
  comparison jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists video_critic_runs_job_idx
  on agency_ops.video_critic_runs(job_id, created_at desc);
alter table agency_ops.video_critic_runs enable row level security;

insert into agency_ops.automation_settings(key,value,description,updated_at) values
('VIDEO_APPROVED_REFERENCE_DNA_ENABLED','true'::jsonb,'Ground video V4.5 editing in approved client references',now()),
('VIDEO_FINAL_AUTO_APPROVE_ON_CRITIC_PASS','true'::jsonb,'Mark automatic V4.5 outputs final only after critic PASS',now()),
('VIDEO_CRITIC_MIN_SCORE','82'::jsonb,'Minimum approved-reference critic score for final delivery',now())
on conflict (key) do update
set value=excluded.value, description=excluded.description, updated_at=now();
insert into agency_ops.video_approved_references
(id,client_id,product_name,product_type,market_tier,aspect_ratio,drive_file_id,drive_url,source_folder_id,duration_seconds,width,height,fps,dna_features,approved_at)
values
('45000000-0000-4000-8000-000000000001','40fd76d2-be7e-4199-a91c-53bdbb7c2efc','CA01240','PROPERTY_TOUR','MID','9:16',
 '176WTMmxN8W_0umNt2RMJ3X4xrybYwHPu','https://drive.google.com/file/d/176WTMmxN8W_0umNt2RMJ3X4xrybYwHPu/view','1FFNz_Od8h9dCgeg8x3Lvj9_oqS00wvbE',
 32.902,1080,1920,30,
 '{"style":"ARCHITECTURAL","target_duration_seconds":33,"avg_shot_duration":3.2,"max_visible_transitions":1,"text_mode":"DUAL_HIERARCHY_LOWER","price_start_ratio":0.76,"cta_start_ratio":0.91}'::jsonb,now()),
('45000000-0000-4000-8000-000000000002','da855fbb-0952-4774-bafa-1a2a0dd00599','Sobrado Novo Hamburgo','PROPERTY_TOUR','MID','3:4',
 '1mWH6tXvZa02AJxYErE7GzFeK9PEvr5zi','https://drive.google.com/file/d/1mWH6tXvZa02AJxYErE7GzFeK9PEvr5zi/view',null,
 59.768,1080,1440,30,
 '{"style":"ARCHITECTURAL","target_duration_seconds":60,"avg_shot_duration":8.0,"max_visible_transitions":0,"text_mode":"PERSISTENT_TOP_SPECS","price_start_ratio":0.20,"cta_start_ratio":0.93}'::jsonb,now())
on conflict (id) do update set
dna_features=excluded.dna_features, duration_seconds=excluded.duration_seconds, updated_at=now();
insert into agency_ops.video_approved_references
(id,client_id,product_name,product_type,market_tier,aspect_ratio,drive_file_id,drive_url,source_folder_id,duration_seconds,width,height,fps,dna_features,approved_at)
values
('45000000-0000-4000-8000-000000000003','f1a41a2b-9c86-4372-8528-2d2c0861eb0c','Helbor Vila Itapety','DEVELOPMENT_LIFESTYLE','PREMIUM','9:16',
 '1R8_-dVNFpoHvHJ6no7kcrKjuk_5Ji-JR','https://drive.google.com/file/d/1R8_-dVNFpoHvHJ6no7kcrKjuk_5Ji-JR/view','1G1lmM_dlmXnNxl9x8lPOruGBIvhKfRlM',
 30,1080,1920,30,
 '{"style":"LAUNCH","target_duration_seconds":30,"avg_shot_duration":3.4,"max_visible_transitions":1,"text_mode":"DUAL_HIERARCHY_LOWER","price_start_ratio":0.80,"cta_start_ratio":0.91}'::jsonb,now()),
('45000000-0000-4000-8000-000000000004','41d70cb8-2160-4abe-9b96-a2cae27e91b6','Lago Azul 2','DEVELOPMENT_LIFESTYLE','PREMIUM','9:16',
 '1OHrqvEo7RaXCnRLPJ-EtmeGZA5mLm0Hw','https://drive.google.com/file/d/1OHrqvEo7RaXCnRLPJ-EtmeGZA5mLm0Hw/view','1ey23VUQpN1l-xVVTyZ6RISkYqtJmqxdn',
 59.141,1080,1920,30,
 '{"style":"LIFESTYLE","target_duration_seconds":59,"avg_shot_duration":2.0,"max_visible_transitions":1,"text_mode":"PREMIUM_TOP_BAND","price_start_ratio":0.84,"cta_start_ratio":0.92}'::jsonb,now())
on conflict (id) do update set
dna_features=excluded.dna_features, duration_seconds=excluded.duration_seconds, updated_at=now();
insert into agency_ops.video_edit_dna_profiles
(id,client_id,profile_key,product_type,market_tier,aspect_ratio,version,status,confidence,reference_count,reference_ids,dna)
values
('45100000-0000-4000-8000-000000000001','40fd76d2-be7e-4199-a91c-53bdbb7c2efc','trilar-property-tour','PROPERTY_TOUR','MID','9:16',1,'ACTIVE',0.96,1,
 array['45000000-0000-4000-8000-000000000001'::uuid],
 '{"style":"ARCHITECTURAL","target_duration_seconds":33,"avg_shot_duration":3.2,"max_visible_transitions":1,"text_mode":"DUAL_HIERARCHY_LOWER","price_start_ratio":0.76,"cta_start_ratio":0.91}'::jsonb),
('45100000-0000-4000-8000-000000000002','da855fbb-0952-4774-bafa-1a2a0dd00599','wallstreet-property-tour','PROPERTY_TOUR','MID','9:16',1,'ACTIVE',0.95,1,
 array['45000000-0000-4000-8000-000000000002'::uuid],
 '{"style":"ARCHITECTURAL","target_duration_seconds":60,"avg_shot_duration":8.0,"max_visible_transitions":0,"text_mode":"PERSISTENT_TOP_SPECS","price_start_ratio":0.20,"cta_start_ratio":0.93}'::jsonb),
('45100000-0000-4000-8000-000000000003','f1a41a2b-9c86-4372-8528-2d2c0861eb0c','nexus-development','DEVELOPMENT_LIFESTYLE','PREMIUM','9:16',1,'ACTIVE',0.96,1,
 array['45000000-0000-4000-8000-000000000003'::uuid],
 '{"style":"LAUNCH","target_duration_seconds":30,"avg_shot_duration":3.4,"max_visible_transitions":1,"text_mode":"DUAL_HIERARCHY_LOWER","price_start_ratio":0.80,"cta_start_ratio":0.91}'::jsonb)
on conflict (id) do update set dna=excluded.dna,confidence=excluded.confidence,updated_at=now();
insert into agency_ops.video_edit_dna_profiles
(id,client_id,profile_key,product_type,market_tier,aspect_ratio,version,status,confidence,reference_count,reference_ids,dna)
values
('45100000-0000-4000-8000-000000000004','41d70cb8-2160-4abe-9b96-a2cae27e91b6','renata-development-lifestyle','DEVELOPMENT_LIFESTYLE','PREMIUM','9:16',1,'ACTIVE',0.97,1,
 array['45000000-0000-4000-8000-000000000004'::uuid],
 '{"style":"LIFESTYLE","target_duration_seconds":59,"avg_shot_duration":2.0,"max_visible_transitions":1,"text_mode":"PREMIUM_TOP_BAND","price_start_ratio":0.84,"cta_start_ratio":0.92}'::jsonb),
('45100000-0000-4000-8000-000000000101',null,'global-property-tour','PROPERTY_TOUR',null,'9:16',1,'ACTIVE',0.72,2,
 array['45000000-0000-4000-8000-000000000001'::uuid,'45000000-0000-4000-8000-000000000002'::uuid],
 '{"style":"ARCHITECTURAL","target_duration_seconds":38,"avg_shot_duration":3.8,"max_visible_transitions":1,"text_mode":"DUAL_HIERARCHY_LOWER","price_start_ratio":0.78,"cta_start_ratio":0.91}'::jsonb),
('45100000-0000-4000-8000-000000000102',null,'global-development-lifestyle','DEVELOPMENT_LIFESTYLE',null,'9:16',1,'ACTIVE',0.74,2,
 array['45000000-0000-4000-8000-000000000003'::uuid,'45000000-0000-4000-8000-000000000004'::uuid],
 '{"style":"LIFESTYLE","target_duration_seconds":45,"avg_shot_duration":2.3,"max_visible_transitions":1,"text_mode":"PREMIUM_TOP_BAND","price_start_ratio":0.82,"cta_start_ratio":0.92}'::jsonb)
on conflict (id) do update set dna=excluded.dna,confidence=excluded.confidence,updated_at=now();
create or replace function agency_ops.sync_v4_auto_source_job_status()
returns trigger language plpgsql security definer
set search_path to 'agency_ops','public','pg_catalog' as $$
begin
  if new.variant<>'v4_auto' then return new; end if;
  if new.status in ('CLAIMED','RENDERING') then
    update agency_ops.video_edit_jobs
       set status='RENDERING', current_stage='V4_'||coalesce(new.current_stage,new.status),
           progress_pct=greatest(progress_pct,least(99,new.progress_pct)),
           worker_id=new.worker_id, heartbeat_at=coalesce(new.heartbeat_at,now()), updated_at=now()
     where id=new.source_job_id;
  elsif new.status='UPLOADING' then
    update agency_ops.video_edit_jobs
       set status='UPLOADING',current_stage='V4_UPLOADING',
           progress_pct=greatest(progress_pct,90),worker_id=new.worker_id,updated_at=now()
     where id=new.source_job_id;
  elsif new.status='QA' then
    update agency_ops.video_edit_jobs
       set status='QA',current_stage='V4_QA',
           progress_pct=greatest(progress_pct,84),worker_id=new.worker_id,updated_at=now()
     where id=new.source_job_id;
  elsif new.status='COMPLETED' then
    if coalesce(new.renderer_version,'') like '4.5%' then
      update agency_ops.video_edit_jobs
         set status='DONE',current_stage='FINAL_READY',progress_pct=100,
             finished_at=coalesce(finished_at,now()),worker_id=new.worker_id,heartbeat_at=now(),
             renderer_version=new.renderer_version,review_mode='AUTO_APPROVED',approval_status='NOT_REQUIRED',
             last_error=null,updated_at=now()
       where id=new.source_job_id;
    else
      update agency_ops.video_edit_jobs
         set status='REVIEW_REQUIRED',current_stage='REVIEW_REQUIRED',progress_pct=100,
             finished_at=coalesce(finished_at,now()),worker_id=new.worker_id,heartbeat_at=now(),
             renderer_version=new.renderer_version,last_error=null,updated_at=now()
       where id=new.source_job_id;
    end if;
  elsif new.status='FAILED' then
    update agency_ops.video_edit_jobs
       set status='FAILED',current_stage='V4_FAILED',finished_at=coalesce(finished_at,now()),
           worker_id=new.worker_id,heartbeat_at=now(),
           last_error=coalesce(new.last_error,'v4_auto_failed'),updated_at=now()
     where id=new.source_job_id;
  elsif new.status='CANCELLED' then
    update agency_ops.video_edit_jobs
       set status='CANCELLED',current_stage='V4_CANCELLED',
           finished_at=coalesce(finished_at,now()),updated_at=now()
     where id=new.source_job_id;
  elsif new.status='RETRY' then
    update agency_ops.video_edit_jobs
       set status='RENDERING',current_stage='V4_RETRY',
           last_error=new.last_error,updated_at=now()
     where id=new.source_job_id;
  end if;
  return new;
end $$;

commit;
