create table if not exists agency_ops.meta_creative_history (
  id bigint generated by default as identity primary key,
  snapshot_date date not null default ((now() at time zone 'America/Sao_Paulo')::date),
  client_id uuid not null,
  client_name text,
  gt_owner text,
  period_days smallint not null,
  date_from date,
  date_to date,
  meta_ad_account_id text not null default '',
  ad_id text not null,
  ad_name text,
  ad_status text,
  adset_id text,
  adset_name text,
  campaign_id text,
  campaign_name text,
  creative_id text,
  creative_name text,
  preview_storage_path text,
  spend numeric,
  impressions bigint,
  reach bigint,
  clicks bigint,
  ctr numeric,
  cpc numeric,
  cpm numeric,
  frequency numeric,
  leads numeric,
  results numeric,
  cpl numeric,
  cost_per_result numeric,
  result_type text,
  result_source text,
  data_status text,
  captured_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (client_id, snapshot_date, period_days, meta_ad_account_id, ad_id)
);

create index if not exists meta_creative_history_client_date_idx on agency_ops.meta_creative_history(client_id, snapshot_date desc);
create index if not exists meta_creative_history_gt_date_idx on agency_ops.meta_creative_history(gt_owner, snapshot_date desc);
create index if not exists meta_creative_history_date_results_idx on agency_ops.meta_creative_history(snapshot_date desc, results desc);

create or replace function agency_ops.archive_meta_creative_snapshot()
returns trigger
language plpgsql
security definer
set search_path = agency_ops, public
as $$
begin
  insert into agency_ops.meta_creative_history (
    snapshot_date, client_id, client_name, gt_owner, period_days, date_from, date_to,
    meta_ad_account_id, ad_id, ad_name, ad_status, adset_id, adset_name,
    campaign_id, campaign_name, creative_id, creative_name, preview_storage_path,
    spend, impressions, reach, clicks, ctr, cpc, cpm, frequency, leads, results,
    cpl, cost_per_result, result_type, result_source, data_status, captured_at, metadata, updated_at
  ) values (
    ((coalesce(new.captured_at, now()) at time zone 'America/Sao_Paulo')::date),
    new.client_id, new.client_name, new.gt_owner, new.period_days, new.date_from, new.date_to,
    coalesce(new.meta_ad_account_id,''), new.ad_id, new.ad_name, new.ad_status, new.adset_id, new.adset_name,
    new.campaign_id, new.campaign_name, new.creative_id, new.creative_name,
    nullif(new.metadata->>'preview_storage_path',''),
    new.spend, new.impressions, new.reach, new.clicks, new.ctr, new.cpc, new.cpm, new.frequency,
    new.leads, new.results, new.cpl, new.cost_per_result, new.result_type, new.result_source,
    new.data_status, new.captured_at, coalesce(new.metadata,'{}'::jsonb), now()
  )
  on conflict (client_id, snapshot_date, period_days, meta_ad_account_id, ad_id)
  do update set
    client_name=excluded.client_name, gt_owner=excluded.gt_owner, date_from=excluded.date_from, date_to=excluded.date_to,
    ad_name=excluded.ad_name, ad_status=excluded.ad_status, adset_id=excluded.adset_id, adset_name=excluded.adset_name,
    campaign_id=excluded.campaign_id, campaign_name=excluded.campaign_name, creative_id=excluded.creative_id,
    creative_name=excluded.creative_name, preview_storage_path=excluded.preview_storage_path,
    spend=excluded.spend, impressions=excluded.impressions, reach=excluded.reach, clicks=excluded.clicks,
    ctr=excluded.ctr, cpc=excluded.cpc, cpm=excluded.cpm, frequency=excluded.frequency, leads=excluded.leads,
    results=excluded.results, cpl=excluded.cpl, cost_per_result=excluded.cost_per_result,
    result_type=excluded.result_type, result_source=excluded.result_source, data_status=excluded.data_status,
    captured_at=excluded.captured_at, metadata=excluded.metadata, updated_at=now();
  return new;
end;
$$;

drop trigger if exists trg_archive_meta_creative_snapshot on agency_ops.meta_creative_snapshots;
create trigger trg_archive_meta_creative_snapshot
after insert or update on agency_ops.meta_creative_snapshots
for each row execute function agency_ops.archive_meta_creative_snapshot();

insert into agency_ops.meta_creative_history (
  snapshot_date, client_id, client_name, gt_owner, period_days, date_from, date_to,
  meta_ad_account_id, ad_id, ad_name, ad_status, adset_id, adset_name,
  campaign_id, campaign_name, creative_id, creative_name, preview_storage_path,
  spend, impressions, reach, clicks, ctr, cpc, cpm, frequency, leads, results,
  cpl, cost_per_result, result_type, result_source, data_status, captured_at, metadata
)
select
  ((coalesce(captured_at, now()) at time zone 'America/Sao_Paulo')::date), client_id, client_name, gt_owner, period_days, date_from, date_to,
  coalesce(meta_ad_account_id,''), ad_id, ad_name, ad_status, adset_id, adset_name,
  campaign_id, campaign_name, creative_id, creative_name, nullif(metadata->>'preview_storage_path',''),
  spend, impressions, reach, clicks, ctr, cpc, cpm, frequency, leads, results,
  cpl, cost_per_result, result_type, result_source, data_status, captured_at, coalesce(metadata,'{}'::jsonb)
from agency_ops.meta_creative_snapshots
on conflict (client_id, snapshot_date, period_days, meta_ad_account_id, ad_id)
do nothing;