import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const CORS={"access-control-allow-origin":"*","access-control-allow-headers":"content-type,authorization,apikey","access-control-allow-methods":"GET,POST,OPTIONS","access-control-max-age":"86400"};
const respond=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
type Identity={person:string;role:string};
const identityCache=new Map<string,{expires:number,value:Identity}>();
const getCache=new Map<string,{expires:number,body:any}>();
let gtCache:{expires:number,value:any[]}|null=null;
function jwtSub(req:Request){try{const raw=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");const part=raw.split(".")[1];if(!part)return null;const normalized=part.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(part.length/4)*4,"=");const payload=JSON.parse(atob(normalized));return typeof payload?.sub==="string"?payload.sub:null;}catch{return null;}}

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});if(!["GET","POST"].includes(req.method))return respond({error:"method_not_allowed"},405);
 const userId=jwtSub(req);if(!userId)return respond({error:"unauthorized"},401);
 const supabaseUrl=Deno.env.get("SUPABASE_URL")||"",serviceRole=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!supabaseUrl||!serviceRole)return respond({error:"server_configuration"},500);
 const ops=createClient(supabaseUrl,serviceRole,{auth:{persistSession:false,autoRefreshToken:false}}).schema("agency_ops");
 async function identity():Promise<Identity|null>{const cached=identityCache.get(userId);if(cached&&cached.expires>Date.now())return cached.value;const[{data:pref,error:prefError},{data:approvals,error:approvalError}]=await Promise.all([ops.from("user_preferences").select("collaborator_person").eq("user_key",userId).maybeSingle(),ops.from("access_requests").select("kind").eq("user_key",userId).eq("status","APPROVED")]);if(prefError||approvalError||!(approvals??[]).some((r:any)=>r.kind==="SIGNUP"))return null;const person=String(pref?.collaborator_person||"").trim();if(!person)return null;const{data:roster,error}=await ops.from("team_roster").select("person,role").eq("person",person).eq("is_former",false).maybeSingle();if(error||!roster)return null;const value={person:String(roster.person),role:String(roster.role||"")};identityCache.set(userId,{expires:Date.now()+120000,value});return value;}
 async function gtOptions(){if(gtCache&&gtCache.expires>Date.now())return gtCache.value;const[{data:walletRows},{data:activeGts}]=await Promise.all([ops.from("wallet_registry").select("gt_owner,carteira,ordem").order("ordem"),ops.from("team_roster").select("person").eq("role","GT").eq("is_former",false)]);const active=new Set((activeGts??[]).map((r:any)=>String(r.person)));const value=(walletRows??[]).filter((r:any)=>active.has(String(r.gt_owner))).slice(0,3).map((r:any)=>({person:r.gt_owner,carteira:r.carteira,ordem:r.ordem}));gtCache={expires:Date.now()+300000,value};return value;}
 const who=await identity();if(!who)return respond({error:"forbidden"},403);const isAdler=who.person==="Adler Furtado",canAssign=isAdler||who.role==="CS",canWork=canAssign||who.role==="GT";
 if(req.method==="POST"){
   if(!canAssign)return respond({error:"forbidden"},403);const body=await req.json().catch(()=>({}));const requestId=String(body.request_id??""),clientId=String(body.client_id??""),gtOwner=String(body.gt_owner??"").trim();if(!requestId||!clientId||!gtOwner)return respond({error:"missing_fields",required:["request_id","client_id","gt_owner"]},400);const options=await gtOptions();if(!options.some((o:any)=>o.person===gtOwner))return respond({error:"gt_not_allowed"},400);const{data,error}=await ops.rpc("assign_onboarding_gt",{p_request_id:requestId,p_client_id:clientId,p_gt_owner:gtOwner,p_actor:who.person});if(error){const known=String(error.message??"");const status=known.includes("REQUEST_ALREADY_RESOLVED")?409:known.includes("NOT_FOUND")?404:known.includes("MISMATCH")||known.includes("NOT_ALLOWED")?400:500;return respond({error:"assignment_failed",detail:known},status);}getCache.clear();return respond(data??{ok:true});
 }
 if(!canWork)return respond({worklist:[],assignment_notifications:[],gt_options:[],playbook_slas:[],sla_summary:{},profile:{person:who.person,role:who.role,can_assign_gt:false},generated_at:new Date().toISOString()});
 const cached=getCache.get(userId);if(cached&&cached.expires>Date.now())return respond(cached.body);
 let workQuery=ops.from("gt_onboarding_worklist").select("*").order("integration_due_at",{ascending:true,nullsFirst:false}).order("display_name",{ascending:true});if(who.role==="GT"&&!isAdler)workQuery=workQuery.eq("gt_owner",who.person);
 let slaQuery=ops.from("onboarding_sla_board").select("*").order("due_at",{ascending:true});if(who.role==="GT"&&!isAdler)slaQuery=slaQuery.eq("gt_owner",who.person);
 const[workResult,slaResult]=await Promise.all([workQuery,slaQuery]);if(workResult.error)return respond({error:"query_failed",detail:workResult.error.message},500);if(slaResult.error)return respond({error:"sla_query_failed",detail:slaResult.error.message},500);
 let assignmentNotifications:any[]=[];let options:any[]=[];
 if(canAssign){options=await gtOptions();const{data:requests,error:requestError}=await ops.from("onboarding_gt_assignment_requests").select("id,case_id,client_id,status,trigger_status,requested_at,metadata").eq("status","PENDING").order("requested_at",{ascending:false}).limit(100);if(requestError)return respond({error:"query_failed",detail:requestError.message},500);const ids=Array.from(new Set((requests??[]).map((r:any)=>String(r.client_id)).filter(Boolean)));const names=new Map<string,string>();if(ids.length){const{data:clientRows,error:clientError}=await ops.from("clients").select("id,display_name").in("id",ids);if(clientError)return respond({error:"query_failed",detail:clientError.message},500);for(const c of clientRows??[])names.set(String(c.id),String(c.display_name??"Cliente"));}assignmentNotifications=(requests??[]).map((r:any)=>{const clientName=names.get(String(r.client_id))??"Cliente",confirmed=r.trigger_status==="DONE";return{id:`gt-assignment:${r.id}`,type:"ONBOARDING_GT_ASSIGNMENT_REQUIRED",level:"HIGH",title:"Selecionar gestor de tráfego",description:confirmed?`A 1ª reunião de apresentação de ${clientName} foi concluída. Selecione o GT para liberar a integração e a carteira.`:`${clientName} já avançou além da 1ª apresentação. Selecione o GT para liberar a integração e a carteira.`,client_id:r.client_id,client_display_name:clientName,source:"onboarding",occurred_at:r.requested_at,read_at:null,metadata:{...(r.metadata??{}),request_id:r.id,onboarding_case_id:r.case_id,action_type:"ASSIGN_GT",action_status:"PENDING",gt_options:options}};});}
 const slas=slaResult.data??[],open=slas.filter((r:any)=>r.status==="OPEN"),summary={total:slas.length,open:open.length,overdue:open.filter((r:any)=>r.sla_status==="OVERDUE").length,due_soon:open.filter((r:any)=>r.sla_status==="DUE_SOON").length,completed_late:slas.filter((r:any)=>r.sla_status==="DONE_LATE").length,production_open:open.filter((r:any)=>r.event_type==="CREATIVE_PRODUCTION").length,revision_open:open.filter((r:any)=>r.event_type==="CREATIVE_REVISION").length,launch_open:open.filter((r:any)=>r.event_type==="CAMPAIGN_LAUNCH").length};
 const result={worklist:workResult.data??[],assignment_notifications:assignmentNotifications,gt_options:canAssign?options:[],playbook_slas:slas,sla_summary:summary,profile:{person:who.person,role:who.role,can_assign_gt:canAssign},generated_at:new Date().toISOString()};getCache.set(userId,{expires:Date.now()+60000,body:result});return respond(result);
});